Repository epam/ai-dial-chat, pull requests merged in 2023-11, with the labels that each got.

#54 fix: fix overlapping of confirmation buttons by prompt name when user deletes the prompt
  .gitattributes
  src/components/Chatbar/components/Conversation.tsx
  src/components/Promptbar/components/Prompt.tsx
Labels: bug

#61 fix: fix extra space between text and attached docs in comparison mode when expand attached documents on other side
  src/components/Markdown/ChatMDComponent.tsx
Labels: bug

#63 fix: fix no scroll in playback textbox for long message, blinking scroll down icon and auto-scroll for long list responses
  docs/OVERLAY.md
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatInput.tsx
  src/components/Chat/PlaybackControls.tsx
  src/types/chat.ts
Labels: bug

#69 fix: replay as is stops working when previous message was based on gpt model and any addon
  src/components/Chat/Chat.tsx
  src/store/conversations/conversations.epics.ts
  src/store/models/models.reducers.ts
  src/utils/app/clear-messages-state.ts
  src/utils/app/conversation.ts
Labels: bug

#70 chore: unit-tests init commit
  .gitignore
  package-lock.json
  package.json
  src/components/Chat/__tests__/ErrorMessageDiv.test.tsx
  src/components/Chat/__tests__/ScrollDownButton.test.tsx
  src/utils/app/__tests__/importExports.test.ts
  tests/setupTests.ts
  tsconfig.json
  vitest.config.ts
Labels: enhancement

#105 fix: Disable the input field
  src/components/Chat/ChatInput.tsx
  src/components/Chat/SendMessageButton.tsx
  src/store/conversations/conversations.reducers.ts
Labels: bug

#121 chore: redesign Playback feature
  package.json
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ChatInput.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Chat/FooterMessage.tsx
  src/components/Chat/PlaybackControls.tsx
  src/components/Chat/PlaybackEmptyInfo.tsx
  src/components/Chat/ReportIssueDialog.tsx
  src/components/Chat/RequestApiKeyDialog.tsx
  src/components/Chat/ScrollDownButton.tsx
  src/components/Chat/__tests__/ErrorMessageDiv.test.tsx
  src/components/Chat/__tests__/FooterMessage.test.tsx
  src/components/Chat/__tests__/PlaybackControls.test.tsx
  src/components/Chat/__tests__/ScrollDownButton.test.tsx
  src/components/Header/User/UserMobile.tsx
  src/components/Markdown/ChatMDComponent.tsx
  src/store/index.ts
  tests/setupTests.ts
  vitest.config.ts
Labels: enhancement, design

#183 chore: removed extra wrappers for home page and rename health endpoint
  src/pages/api/health.ts
  src/pages/api/home/home.tsx
  src/pages/api/home/index.ts
  src/pages/index.tsx
Labels: enhancement, technical debt

#189 feature: add "share" option in context menu for conversation and for prompt
  .env.development
  .eslintrc.json
  e2e/src/testData/expectedConstants.ts
  e2e/src/tests/chatBarConversation.test.ts
  e2e/src/tests/prompts.test.ts
  next.config.js
  package-lock.json
  package.json
  public/images/icons/clone.svg
  public/locales/en/sidebar.json
  src/components/Chat/ChatMessage.tsx
  src/components/Chat/ShareModal.tsx
  src/components/Chat/__tests__/ErrorMessageDiv.test.tsx
  src/components/Chat/__tests__/FooterMessage.test.tsx
  src/components/Chat/__tests__/PlaybackControls.test.tsx
  src/components/Chat/__tests__/ScrollDownButton.test.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/ContextMenu.tsx
  src/components/Common/Tooltip.tsx
  src/components/Header/User/ProfileButton.tsx
  src/components/Markdown/CodeBlock.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/components/Promptbar/components/PromptModal.tsx
  src/pages/api/addons.ts
  src/store/conversations/conversations.reducers.ts
  src/store/prompts/prompts.reducers.ts
  src/types/chat.ts
  src/types/features.ts
  src/types/prompt.ts
  src/utils/app/clean.ts
  src/utils/server/get-entities.ts
  src/utils/server/get-sorted-entities.ts
  tsconfig.json
Labels: enhancement, _priority_1

#197 fix: shared icon appears for replay and playback
  src/components/Common/DropdownMenu.tsx
  src/store/conversations/conversations.reducers.ts
Labels: bug

#203 fix: handle not allowed addon
  public/locales/en/chat.json
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/NotAllowedModel.tsx
  src/types/common.ts
Labels: bug, enhancement

#206 fix: remove incorrect addons when change model in replay mode
  src/components/Chat/Chat.tsx
Labels: bug

#204 chore: use enums and css helper
  .eslintrc.json
  e2e/src/testData/conversationHistory/conversationData.ts
  overlay/ChatOverlayManager.ts
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatCompareSelect.tsx
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ChatInfoTooltip.tsx
  src/components/Chat/ChatInput/ChatInputMessage.tsx
  src/components/Chat/ChatInput/PromptList.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Chat/ConversationSettings.tsx
  src/components/Chat/ModelsDialog.tsx
  src/components/Chat/__tests__/PlaybackControls.test.tsx
  src/components/Chatbar/Chatbar.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Chatbar/components/ChatbarSettings.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Chatbar/components/ModelIcon.tsx
  src/components/Common/ContextMenu.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Files/FileFolderSelect.tsx
  src/components/Files/FileSelect.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Folder/Folder.tsx
  src/components/Header/User/ProfileButton.tsx
  src/components/Promptbar/Promptbar.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/components/Promptbar/components/PromptbarSettings.tsx
  src/components/Settings/Import.tsx
  src/components/Sidebar/BetweenFoldersLine.tsx
  src/components/Sidebar/Sidebar.tsx
  src/pages/api/addons.ts
  src/pages/api/chat.ts
  src/store/conversations/conversations.epics.ts
  src/store/conversations/conversations.reducers.ts
  src/store/models/models.reducers.ts
  src/store/overlay/overlay.epics.ts
  src/types/chat.ts
  src/types/common.ts
  src/types/components.ts
  src/types/openai.ts
  src/utils/app/__tests__/importExports.test.ts
  src/utils/app/conversation.ts
  src/utils/app/data/storages/api-mock-storage.ts
  src/utils/app/folders.ts
  src/utils/app/stages.ts
  src/utils/server/get-entities.ts
  src/utils/server/get-sorted-entities.ts
  src/utils/server/index.ts
Labels: enhancement, technical debt

#218 fix: hide empty Selected section(addons)
  src/components/Chat/Addons.tsx
  src/components/Chat/AddonsDialog.tsx
Labels: bug

#231 fix: fix system prompt scrollbar displaying (#106)
  src/components/Chat/SystemPrompt.tsx
Labels: bug

#238 fix: fix displaying the prompt context menu
  src/components/Chatbar/components/Conversation.tsx
  src/components/Promptbar/components/Prompt.tsx
Labels: bug

#246 fix: fix send message by enter when message is empty
  src/components/Chat/ChatInput/ChatInputMessage.tsx
  src/components/Chat/ChatInput/SendMessageButton.tsx
  src/components/Files/FileItem.tsx
  src/components/Files/FileManagerModal.tsx
  src/components/Files/SelectFolderModal.tsx
  src/components/Folder/Folder.tsx
  src/store/files/files.reducers.ts
  src/utils/app/folders.ts
Labels: bug

#249 feat: redesign tooltips
  .eslintrc.json
  src/components/Chat/Addons.tsx
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ChatInput/SendMessageButton.tsx
  src/components/Chat/ChatSettings.tsx
  src/components/Chat/ConversationSettingsModels.tsx
  src/components/Chat/IconNonModelWithTooltip.tsx
  src/components/Chat/MessageAttachments.tsx
  src/components/Chat/MessageStage.tsx
  src/components/Chat/ShareModal.tsx
  src/components/Chatbar/components/ChatbarSettings.tsx
  src/components/Chatbar/components/ModelIcon.tsx
  src/components/Common/Tooltip.tsx
  src/components/Files/AttachButton.tsx
  src/components/Files/FileItem.tsx
  src/components/Files/FileManagerModal.tsx
  src/components/Header/CreateNewChatMobile.tsx
  src/components/Header/Header.tsx
  src/components/Markdown/CodeBlock.tsx
  src/components/Promptbar/components/PromptbarSettings.tsx
Labels: enhancement

#261 fix: fix MoveTo
  src/components/Common/ItemContextMenu.tsx
Labels: bug

#263 fix: fix "Move To" color (#264)
  src/components/Common/ContextMenu.tsx
Labels: bug
