Repository epam/ai-dial-chat, pull requests merged in 2023-12, with the labels that each got.

#298 chore: bump vitest from 0.34.6 to 1.0.1
  package-lock.json
  package.json
  vitest.config.mts
Labels: enhancement, technical debt

#305 fix: e2e tests
  e2e/src/tests/compareMode.test.ts
  e2e/src/tests/defaultModelSettings.test.ts
  e2e/src/ui/selectors/sideBarSelectors.ts
  e2e/src/ui/webElements/conversations.ts
Labels: bug, technical debt

#307 fix: fix numeration after 10
  src/utils/app/folders.ts
Labels: bug, enhancement

#286 feat: add search filters (#276)
  public/images/icons/arrow-up-right.svg
  public/images/icons/search.svg
  public/images/icons/world.svg
  src/components/Chat/ChatCompareSelect.tsx
  src/components/Chatbar/Chatbar.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/ShareIcon.tsx
  src/components/Promptbar/Promptbar.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/components/Promptbar/components/PromptbarSettings.tsx
  src/components/Promptbar/components/Prompts.tsx
  src/components/Search/Search.tsx
  src/components/Search/SearchFilterRenderer.tsx
  src/components/Search/SearchFiltersView.tsx
  src/components/Sidebar/Sidebar.tsx
  src/store/conversations/conversations.reducers.ts
  src/store/conversations/conversations.selectors.ts
  src/store/conversations/conversations.types.ts
  src/store/prompts/prompts.reducers.ts
  src/store/prompts/prompts.selectors.ts
  src/store/prompts/prompts.types.ts
  src/store/settings/settings.reducers.ts
  src/styles/globals.css
  src/types/chat.ts
  src/types/features.ts
  src/types/folder.ts
  src/types/search.ts
  src/utils/app/search.ts
Labels: enhancement, design, _priority_1

#299 feat: add folder sharing, fix "shared with me" displaying (#291)
  package-lock.json
  public/locales/en/sidebar.json
  src/components/Chat/ShareModal.tsx
  src/components/Chatbar/Chatbar.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Common/ShareIcon.tsx
  src/components/Folder/Folder.tsx
  src/components/Promptbar/Promptbar.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/components/Search/SearchFiltersView.tsx
  src/store/addons/addons.reducers.ts
  src/store/conversations/conversations.epics.ts
  src/store/conversations/conversations.reducers.ts
  src/store/conversations/conversations.selectors.ts
  src/store/files/files.epics.ts
  src/store/models/models.reducers.ts
  src/store/prompts/prompts.epics.ts
  src/store/prompts/prompts.reducers.ts
  src/store/prompts/prompts.selectors.ts
  src/store/settings/settings.reducers.ts
  src/types/chat.ts
  src/types/common.ts
  src/types/folder.ts
  src/types/prompt.ts
  src/types/search.ts
  src/types/share.ts
  src/utils/app/clean.ts
  src/utils/app/search.ts
Labels: enhancement, design, _priority_1

#324 feat: added tooltips for share modal and icon
  src/components/Chat/ShareModal.tsx
  src/components/Common/ShareIcon.tsx
Labels: enhancement

#312 feat: add Publish options in context menu and Organization section
  .env.development
  e2e/src/testData/expectedConstants.ts
  e2e/src/tests/chatBarConversation.test.ts
  e2e/src/tests/prompts.test.ts
  public/images/icons/unpublish.svg
  src/components/Chat/PublishModal.tsx
  src/components/Chat/ShareModal.tsx
  src/components/Chat/UnpublishModal.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Common/ItemContextMenu.tsx
  src/components/Folder/Folder.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/constants/chat.ts
  src/store/conversations/conversations.epics.ts
  src/store/conversations/conversations.reducers.ts
  src/store/prompts/prompts.epics.ts
  src/store/prompts/prompts.reducers.ts
  src/types/share.ts
  src/utils/app/clean.ts
  src/utils/app/search.ts
  src/utils/app/share.ts
Labels: enhancement, _priority_1

#327 fix: fix share icon tooltip and focus for filters
  src/components/Common/ShareIcon.tsx
  src/components/Search/SearchFilterRenderer.tsx
Labels: bug

#325 fix: chat header information tooltip performs poorly if system prompt is big
  src/components/Chat/ChatInfoTooltip.tsx
Labels: bug, _priority_2

#332 fix: need to add a space between names in chat/prompt panels
  src/components/Chatbar/components/ConversationsRenderer.tsx
Labels: bug

#333 fix: fixed tooltips for share icon
  package-lock.json
  src/components/Common/ShareIcon.tsx
Labels: bug

#338 fix: add search filter tooltip and fix checkbox focus
  src/components/Search/SearchFiltersView.tsx
  src/styles/globals.css
Labels: bug

#337 fix: folder background should be green if to hover over in chat panel purple in prompt panel
  src/components/Folder/Folder.tsx
Labels: enhancement, design, _priority_2

#340 fix: fix conversation name when only attachments
  src/store/conversations/conversations.epics.ts
  src/utils/app/conversation.ts
Labels: bug, enhancement, _priority_1

#344 fix: folder background should be green if to hover over in chat panel purple in prompt panel
  src/components/Common/ShareIcon.tsx
  src/components/Folder/Folder.tsx
Labels: enhancement, design, _priority_2

#350 fix: part 2 file attachment corrections ui
  src/components/Chat/ChatInput/ChatInputAttachment.tsx
  src/components/Files/FileItem.tsx
  src/components/Files/FileItemContextMenu.tsx
  src/components/Files/FileManagerModal.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Files/SelectFolderModal.tsx
Labels: bug, _priority_2

#351 fix: there is different space between folders and chats
  src/components/Chatbar/components/ConversationsRenderer.tsx
  src/components/Folder/Folder.tsx
  src/components/Promptbar/components/Prompts.tsx
Labels: bug

#354 feat: add option to upload file directly to folder via context menu (Issue #230)
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Files/FileManagerModal.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Files/SelectFolderModal.tsx
  src/components/Folder/Folder.tsx
  src/components/Folder/index.ts
  src/components/Promptbar/components/PromptFolders.tsx
Labels: enhancement, _priority_2

#358 fix: empty "Select Folder" search after close (Issue #357)
  src/components/Files/SelectFolderModal.tsx
Labels: bug

#359 fix: it's impossible to upload file thru attachment functionality opened from chat panel if new chat or chat based on not dial rag is opened
  src/components/Chatbar/components/ChatbarSettings.tsx
Labels: bug, _priority_1

#346 feat: added an full screen chat width option(#83, #143)
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ChatInput/ChatInputMessage.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Chat/NotAllowedModel.tsx
  src/components/Chat/PlaybackControls.tsx
  src/components/Chat/__tests__/PlaybackControls.test.tsx
  src/components/Common/ToggleSwitch/ToggleSwitch.tsx
  src/components/Common/ToggleSwitch/ToggleSwitchLabeled.tsx
  src/components/Markdown/ChatMDComponent.tsx
  src/components/Markdown/MemoizedReactMarkdown.tsx
  src/components/Settings/SettingDialog.tsx
  src/components/Settings/ThemeSelect.tsx
  src/store/ui/ui.epics.ts
  src/store/ui/ui.reducers.ts
  src/types/storage.ts
  src/utils/app/data/data-service.ts
Labels: bug, enhancement

#363 fix: reset renaming on search change
  src/components/Files/FileManagerModal.tsx
  src/components/Files/SelectFolderModal.tsx
  src/components/Folder/Folder.tsx
  src/store/files/files.reducers.ts
Labels: bug

#365 fix: user messages not widen in "Full width chat" mode
  src/components/Chat/ChatMessage.tsx
  src/components/Sidebar/Sidebar.tsx
Labels: bug

#373 fix: not allow incorrect symbols in file names (Issue #253)
  src/components/Common/ErrorMessage.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Files/SelectFolderModal.tsx
  src/components/Folder/Folder.tsx
  src/utils/app/file.ts
Labels: bug, _priority_1

#372 fix: shared and published icons have unnecessary background if to navigate thru context menu in select conversation drop down list
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/Combobox.tsx
Labels: bug

#377 fix: add folder name validation (Issue #375)
  src/components/Files/FileManagerModal.tsx
  src/components/Files/SelectFolderModal.tsx
  src/components/Folder/Folder.tsx
  src/utils/app/file.ts
Labels: enhancement

#362 chore: remove credential provider (Issue #348)
  .env.development
  README.md
  src/pages/api/auth/[...nextauth].ts
  src/utils/auth/nextauth.ts
Labels: enhancement, _priority_1

#378 chore: remove credential provider (Issue #348)
  .env.development
  README.md
  src/pages/api/auth/[...nextauth].ts
  src/utils/auth/nextauth.ts
Labels: enhancement, _priority_1

#383 fix: add file name validation during renaming before upload and fix sharing/publishing displaying (Issue #253, #385)
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Common/ItemContextMenu.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/utils/app/file.ts
Labels: bug, _priority_1

#386 fix: add file name validation during renaming before upload and fix sharing/publishing displaying (Issue #253, #385)
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Common/ItemContextMenu.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/utils/app/file.ts
Labels: bug

#390 fix: fix reupload file
  src/components/Chat/ChatInput/ChatInputAttachment.tsx
  src/components/Files/FileItem.tsx
  src/store/files/files.reducers.ts
Labels: bug

#388 fix: add 'stop streaming' to the 'save & submit' message button (issue #161)
  src/components/Chat/Chat.tsx
Labels: bug

#396 fix: there is no space between nested folders in attachment windows (Issue #384)
  src/components/Folder/Folder.tsx
Labels: bug

#399 fix: it's inconvenient to read file name while editing as there is no space before file extension (Issue #370)
  src/components/Files/PreUploadModal.tsx
Labels: bug

#400 fix: send button is available though attachment is being loaded (Issue #398)
  src/components/Chat/ChatInput/ChatInputMessage.tsx
  src/components/Chat/ChatMessage.tsx
  src/store/files/files.reducers.ts
Labels: bug

#408 fix: fix console errors (Issue #407)
  src/components/Chat/MessageAttachments.tsx
  src/components/Chat/ModelsDialog.tsx
  src/components/Files/PreUploadModal.tsx
  src/store/conversations/conversations.selectors.ts
Labels: enhancement, technical debt

#410 fix: fix cursor for model view (Issue #407)
  src/components/Chat/ModelsDialog.tsx
Labels: bug, technical debt

#409 fix: hot keys are applied not on opened modal window but on playback chat on background (Issue #404)
  src/components/Chat/PlaybackControls.tsx
  src/components/Chat/PublishModal.tsx
  src/components/Chat/ShareModal.tsx
  src/components/Chat/UnpublishModal.tsx
  src/components/Common/ConfirmDialog.tsx
  src/components/Files/FileManagerModal.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Files/SelectFolderModal.tsx
  src/components/Folder/Folder.tsx
  src/components/Promptbar/components/PromptModal.tsx
  src/utils/app/modals.ts
Labels: bug

#422 feat: need to add download button for received pictures (Issue #124)
  src/components/Chat/ChatMessage.tsx
  src/components/Chat/MessageAttachment.tsx
Labels: enhancement

#411 feat: add attachments in message input in playback mode (issue #387)
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatInput/ChatInputAttachment.tsx
  src/components/Chat/ChatInput/ChatInputAttachments.tsx
  src/components/Chat/ChatInput/ChatInputMessage.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Chat/Playback/PlaybackAttachments.tsx
  src/components/Chat/Playback/PlaybackControls.tsx
  src/components/Chat/Playback/PlaybackEmptyInfo.tsx
  src/components/Chat/Playback/PlaybackIcon.tsx
  src/components/Chat/__tests__/PlaybackAttachments.test.tsx
  src/components/Chat/__tests__/PlaybackControls.test.tsx
  src/components/Chatbar/components/Conversation.tsx
Labels: enhancement

#423 fix: chat and prompt panels are opened at the same time if to log into dial for the first time on mobile (Issue #241)
  src/utils/app/data/data-service.ts
Labels: bug

#428 feat: add mobile styles to the attachments in message in edit mode (issue #424)
  src/components/Chat/ChatMessage.tsx
Labels: enhancement

#432 feat: implement limited context menu and readonly view (no message input) (Issue #389, #431)
  package-lock.json
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatExternalControls.tsx
  src/components/Chat/ChatInput/ChatInput.tsx
  src/components/Chat/ChatInput/ChatInputMessage.tsx
  src/components/Chat/ChatReplayControls.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Common/ItemContextMenu.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/store/conversations/conversations.epics.ts
  src/store/conversations/conversations.reducers.ts
  src/store/conversations/conversations.selectors.ts
  src/store/prompts/prompts.epics.ts
  src/store/prompts/prompts.reducers.ts
  src/styles/globals.css
  src/utils/app/folders.ts
  src/utils/app/share.ts
Labels: enhancement, design

#436 fix: move to folders menu has incorrect background (Issue #426)
  src/components/Common/ContextMenu.tsx
  src/components/Header/User/UserDesktop.tsx
Labels: bug

#439 fix: fix displaying "Shared with me" and "Organization" section items (Issue #437)
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/store/conversations/conversations.epics.ts
  src/store/conversations/conversations.selectors.ts
  src/store/prompts/prompts.epics.ts
  src/store/prompts/prompts.selectors.ts
  src/utils/app/search.ts
Labels: bug, _priority_1

#440 chore: need to add custom popups for confirmation actions (Issue #89)
  e2e/src/tests/chatHeader.test.ts
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ChatInput/ChatInputMessage.tsx
  src/components/Chat/SystemPrompt.tsx
  src/components/Common/ConfirmDialog.tsx
  src/hooks/usePromptSelection.ts
  src/types/features.ts
  src/utils/app/modals.ts
Labels: enhancement, design

#442 fix: chatbar conversation icon is set to default after page refresh (Issue #438)
  e2e/src/tests/entityIcon.test.ts
  src/components/Chatbar/components/ModelIcon.tsx
Labels: bug, _priority_1

#443 chore: errors modals redesign (Issue #90)
  package-lock.json
  package.json
  src/pages/_app.tsx
Labels: enhancement, design

#448 fix: fix spacing between chats and prompts in "Share with Me" and "Organization" sections (Issue #447 )
  public/images/icons/clipboard-xmark.svg
  public/images/icons/xmark.svg
  src/components/Chat/Addons.tsx
  src/components/Chat/AddonsDialog.tsx
  src/components/Chat/ConversationSettings.tsx
  src/components/Chat/ModelsDialog.tsx
  src/components/Chat/VariableModal.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Common/MoveToFolderMobileModal.tsx
  src/components/Common/NoData.tsx
  src/components/Folder/Folder.tsx
  src/components/Header/Header.tsx
  src/components/Header/User/ProfileButton.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/components/Settings/SettingDialog.tsx
Labels: bug
