Repository epam/ai-dial-chat, pull requests merged in 2024-10, with the labels that each got.

#2242 fix(chat): fix use application button text (Issue #2232)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
Labels: bug, _priority_1

#2245 fix(chat): fix application edit, fix application delete & icon fallback logic (Issue #2230 #2021)
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/models/models.epics.ts
Labels: bug, _priority_2

#2257 fix(chat): fix id check for installed application (Issue #2234)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
Labels: bug, _priority_2

#2248 fix(chat): fix prompt versions applying (Issue #2209)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/hooks/usePromptSelection.ts
Labels: bug, _priority_2

#2249 fix(chat): fix card view data update (Issue #2224)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug

#2241 fix(chat): fix prompts duplication (Issue #2201)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
  apps/chat/src/utils/app/data/storages/api/prompt-api-storage.ts
  apps/chat/src/utils/server/api.ts
Labels: bug, _priority_1

#2253 feat(chat): redesign of message template editor (Issue #2235)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat/src/components/Buttons/TabButton.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/ReplayVariables.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/ChatMessageTemplatesModal.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateInput.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateRenderer.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateRow.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Chat/Publish/RuleListItem.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/utils/app/prompts.ts
  libs/shared/src/types/chat.ts
Labels: enhancement

#2264 fix(chat): fix attachments type font size (Issue #2250)
  apps/chat/src/components/Common/MultipleComboBox.tsx
Labels: bug

#2260 fix(chat): add posibilty to remove specific app version from my apps list, hide remove button from custom apps owner (Issues #2226, #2220)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug, _priority_2

#2215 feat(chat): add topics and capabilities fields to custom apps (Issue #2086)
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/DropdownSelector.tsx
  apps/chat/src/types/common.ts
  apps/chat/src/utils/app/style-helpers.ts
  package-lock.json
  package.json
Labels: enhancement

#2263 fix(chat): fix the message template editor (Issue #2275, #2268, #2270)
  apps/chat/src/components/Chat/ChatInput/PromptVariablesDialog.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/ChatMessageTemplatesModal.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateRenderer.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateRow.tsx
  apps/chat/src/constants/folders.ts
  apps/chat/src/utils/app/prompts.ts
Labels: bug

#2298 fix(chat): fix message template editor (Issue #2291)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/ChatMessageTemplatesModal.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateRow.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
Labels: enhancement

#2292 fix(chat): fix application dialog issues (Issue #2247, #2251, #2262)
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
Labels: bug

#2301 fix(chat): fix validation of message template (Issue #2296)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
Labels: bug

#2299 fix(chat): fix validation of message template (Issue #2270, #2295)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateInput.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateRow.tsx
  apps/chat/src/components/Common/DropdownSelector.tsx
Labels: bug

#2315 feat(chat): change home to all application (Issue #2313)
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
Labels: bug

#2312 fix(chat): fix public custom app remove action and add app details modal closing after remove (Issues #2290, #2280)
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug, _priority_1

#2317 fix(chat): fix topics paddings (Issue #2295)
  apps/chat/src/components/Common/DropdownSelector.tsx
  apps/chat/src/components/Common/QuickAppDialog.tsx
Labels: bug

#2318 fix(chat): fix opentelemetry errors (Issue #2199)
  .ort.yml
  apps/chat/src/opentelemetry.ts
  apps/chat/src/pages/_document.tsx
  package-lock.json
  package.json
Labels: bug, technical debt, _priority_1

#2320 fix(chat): fix "Add app" button view for several options (Issue #2319, #141)
  apps/chat/src/components/Chat/ChatExternalControls.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/components/Search/SearchFiltersView.tsx
  apps/chat/src/styles/globals.css
Labels: bug

#2327 fix(chat): fix application letters cut (Issue #2282)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
Labels: bug

#2325 fix(chat): change marketplace side panel home icon and color (Issue #2278)
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
Labels: bug

#2322 fix(chat): fix marketplace checkbox row (Issue #2310)
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
Labels: bug

#2307 feat(chat): change application word to item, fix features validation (Issue #2229)
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: bug

#2333 feat(chat): support "\n \n" delimiter for model description (Issue #2332)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Common/MarkdownDescription.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/constants/chat.ts
Labels: enhancement

#2311 fix(chat): fix app icons publishing (Issue #1941)
  apps/chat/src/components/Common/QuickAppDialog.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug

#2339 feat(chat): rename Marketplace terms and tabs (Issue #2338)
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat-e2e/src/tests/entityIcon.test.ts
  apps/chat-e2e/src/ui/webElements/entitySelector.ts
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Marketplace/MarketplaceBanner.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: enhancement, _priority_1

#2340 fix(chat): change marketplace alphabetically order (Issue #2285)
  apps/chat/src/store/models/models.reducers.ts
Labels: bug

#2336 fix(chat): fix marketplace tab moving (Issue #2335)
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
Labels: bug

#2337 fix(chat): fix marketplace counter (Issue #2326)
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: bug

#2328 feat(chat): add modulify-ui library (Issue #2331)
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/customizations/index.tsx
  apps/chat/src/pages/api/auth/[...nextauth].ts
  apps/chat/src/pages/index.tsx
  apps/chat/src/utils/auth/auth-pages.ts
  apps/chat/tsconfig.json
  libs/modulify-ui/.eslintrc.json
  libs/modulify-ui/README.md
  libs/modulify-ui/package.json
  libs/modulify-ui/project.json
  libs/modulify-ui/src/index.ts
  libs/modulify-ui/src/lib/ComponentBuilder.test.tsx
  libs/modulify-ui/src/lib/ComponentBuilder.tsx
  libs/modulify-ui/src/lib/Inversify.test.tsx
  libs/modulify-ui/src/lib/Inversify.tsx
  libs/modulify-ui/tsconfig.json
  libs/modulify-ui/tsconfig.lib.json
  libs/modulify-ui/tsconfig.spec.json
  libs/modulify-ui/vite.config.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#2324 fix(chat): fix system propmt applying (Issue #2209)
  apps/chat/src/components/Chat/SystemPrompt.tsx
Labels: bug, _priority_2

#2346 fix(chat): fix "Talk to" list displaying (Issue #2286)
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/utils/app/data/data-service.ts
Labels: bug, _priority_1

#2354 fix(chat): fix attachments type validation and remove topics validation (Issue #2251)
  apps/chat/src/components/Common/ApplicationDialog.tsx
Labels: bug

#2359 fix(chat): fix the infinite loader for "New conversation" (Issue #2358)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, PATCH

#2367 fix(chat): fix manage attachments icon color (Issue #2233)
  apps/chat/src/components/Files/FileItem.tsx
Labels: bug

#2321 fix(chat): fix my models deletion (Issue #2287)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
Labels: bug, _priority_2

#2370 fix(chat): fix published custom app target icon urls (Issue #1941)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/QuickAppDialog.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug

#2375 fix(chat): fix conversations duplication (Issue #2352)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug, _priority_1

#2380 fix(chat): change my workspace text (Issue #2343)
  apps/chat/src/components/Marketplace/MarketplaceBanner.tsx
Labels: bug

#2384 fix(chat): remove dotes from unnecessary parts (Issue #2356)
  apps/chat/src/components/Chat/Addons.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
Labels: bug

#2385 fix(chat): fix deleting of application (Issue #2383)
  apps/chat/src/store/models/models.epics.ts
Labels: bug, _priority_2

#2376 fix(chat): change tree paddings in side panels (Issue #2213)
  apps/chat-e2e/src/tests/chatBarFolderConversation.test.ts
  apps/chat-e2e/src/tests/folderPrompts.test.ts
  apps/chat-e2e/src/tests/promptFolderNumeration.test.ts
  apps/chat-e2e/src/ui/webElements/entityTree/folders.ts
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug

#2366 fix(chat): fix the infinite loader for "New conversation" (Issue #2358)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/models/models.reducers.ts
Labels: bug

#2386 fix(chat): fix custom app icons publishing (Issue #1941)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug

#2381 fix(chat): fix e2e-tests (Issue #2272)
  apps/chat-e2e/src/assertions/addonsDialogAssertion.ts
  apps/chat-e2e/src/assertions/baseAssertion.ts
  apps/chat-e2e/src/assertions/chatHeaderAssertion.ts
  apps/chat-e2e/src/assertions/chatMessagesAssertion.ts
  apps/chat-e2e/src/assertions/conversationInfoTooltipAssertion.ts
  apps/chat-e2e/src/assertions/conversationToCompareAssertion.ts
  apps/chat-e2e/src/assertions/entitySettingAssertion.ts
  apps/chat-e2e/src/assertions/entityTreeAssertion.ts
  apps/chat-e2e/src/assertions/index.ts
  apps/chat-e2e/src/assertions/isolatedViewAssertion.ts
  apps/chat-e2e/src/assertions/marketplaceApplicationsAssertion.ts
  apps/chat-e2e/src/assertions/recentEntitiesAssertion.ts
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/testData/api/iconApiHelper.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/abortedReplay.test.ts
  apps/chat-e2e/src/tests/chatExportImport.test.ts
  apps/chat-e2e/src/tests/chatHeader.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat-e2e/src/tests/entityIcon.test.ts
  apps/chat-e2e/src/tests/isolatedView.test.ts
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat-e2e/src/tests/publishConversation.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat-e2e/src/ui/domData/tags.ts
  apps/chat-e2e/src/ui/pages/dialHomePage.ts
  apps/chat-e2e/src/ui/webElements/addonsDialog.ts
  apps/chat-e2e/src/ui/webElements/baseElement.ts
  apps/chat-e2e/src/ui/webElements/chatHeader.ts
  apps/chat-e2e/src/ui/webElements/chatInfoTooltip.ts
  apps/chat-e2e/src/ui/webElements/chatMessages.ts
  apps/chat-e2e/src/ui/webElements/conversationToCompare.ts
  apps/chat-e2e/src/ui/webElements/entityTree/entitiesTree.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/sideBarEntitiesTree.ts
  apps/chat-e2e/src/ui/webElements/marketplace/applications.ts
  apps/chat-e2e/src/ui/webElements/modelSelector.ts
  apps/chat-e2e/src/ui/webElements/moreInfo.ts
  apps/chat-e2e/src/ui/webElements/talkToEntities.ts
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug, e2e

#2393 fix(chat): Update the phrase "Not allowed model selected. Please, change the model to proceed" (Issue #2363)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat/public/locales/en/chat.json
Labels: bug

#2395 fix(chat): update marketplace icons tooltips (#2377)
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
Labels: bug

#2391 fix(chat): home page add delete button to custom app, remove short description from card view (Issue #2279, #2334)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/utils/app/application.ts
Labels: bug

#2396 fix(chat): fix duplicate in compare mode (Issue #2394)
  apps/chat/src/components/Chat/ChatExternalControls.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/app/share.ts
Labels: bug, _priority_2

#2399 fix(chat): fix resourceListing route (Issue #2400)
  apps/chat/src/pages/api/publication/userListing.ts
  apps/chat/src/utils/app/data/publication-service.ts
Labels: technical debt

#2392 fix(chat): fix custom apps unpublishing, fix resources order and app icon size inside publication review modal (Issue #1941, #2390)
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
Labels: bug, _priority_1

#2398 fix(chat): update icons and panel width (#2389)
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
Labels: bug

#2378 fix(chat): fix image blinking (Issue #2272, #2347)
  apps/chat-e2e/src/assertions/addonsDialogAssertion.ts
  apps/chat-e2e/src/assertions/baseAssertion.ts
  apps/chat-e2e/src/assertions/chatHeaderAssertion.ts
  apps/chat-e2e/src/assertions/chatMessagesAssertion.ts
  apps/chat-e2e/src/assertions/conversationInfoTooltipAssertion.ts
  apps/chat-e2e/src/assertions/conversationToCompareAssertion.ts
  apps/chat-e2e/src/assertions/entitySettingAssertion.ts
  apps/chat-e2e/src/assertions/entityTreeAssertion.ts
  apps/chat-e2e/src/assertions/index.ts
  apps/chat-e2e/src/assertions/isolatedViewAssertion.ts
  apps/chat-e2e/src/assertions/marketplaceApplicationsAssertion.ts
  apps/chat-e2e/src/assertions/recentEntitiesAssertion.ts
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/testData/api/iconApiHelper.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/abortedReplay.test.ts
  apps/chat-e2e/src/tests/chatExportImport.test.ts
  apps/chat-e2e/src/tests/chatHeader.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat-e2e/src/tests/entityIcon.test.ts
  apps/chat-e2e/src/tests/isolatedView.test.ts
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat-e2e/src/tests/publishConversation.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat-e2e/src/ui/domData/tags.ts
  apps/chat-e2e/src/ui/pages/dialHomePage.ts
  apps/chat-e2e/src/ui/webElements/addonsDialog.ts
  apps/chat-e2e/src/ui/webElements/baseElement.ts
  apps/chat-e2e/src/ui/webElements/chatHeader.ts
  apps/chat-e2e/src/ui/webElements/chatInfoTooltip.ts
  apps/chat-e2e/src/ui/webElements/chatMessages.ts
  apps/chat-e2e/src/ui/webElements/conversationToCompare.ts
  apps/chat-e2e/src/ui/webElements/entityTree/entitiesTree.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/sideBarEntitiesTree.ts
  apps/chat-e2e/src/ui/webElements/marketplace/applications.ts
  apps/chat-e2e/src/ui/webElements/modelSelector.ts
  apps/chat-e2e/src/ui/webElements/moreInfo.ts
  apps/chat-e2e/src/ui/webElements/talkToEntities.ts
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/QuickAppDialog.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/pages/api/themes/image/[name].ts
  apps/chat/src/utils/app/file.ts
  package-lock.json
  package.json
Labels: bug

#2388 feat(chat): add possibility to define role paths for each identity provider (Issue #1996)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: enhancement, technical debt, _priority_1

#2316 fix(chat): remove extra api requests for marketplace page (Issue #2177)
  apps/chat/src/components/Layout.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/types/common.ts
Labels: bug, _priority_1

#2404 feat(chat): create new conversation after initialization (Issue #2351)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/models/models.reducers.ts
Labels: enhancement, _priority_1, PATCH

#2406 feat(chat): show loader during redirecting (Issue #2350)
  apps/chat/src/components/Layout.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/store/marketplace/marketplace.selectors.ts
Labels: enhancement

#2409 fix(chat): disable `publish/` requests if feature is disabled (Issue #2007)
  apps/chat/src/pages/api/publication/resourceListing.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/settings/settings.reducers.ts
Labels: bug, technical debt, _priority_2

#2416 fix(chat): fix dropdown horizontal scroll, UI corrections (Issue #2243, #2274)
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: bug

#2415 fix(chat): fix same name external conversations duplicate (Issue #2414)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
Labels: bug

#2417 feat(chat): redesign marketplace card view (Issue #2373)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/CardsList.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/Marketplace/MarketplaceBanner.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: enhancement

#2420 fix(chat): add organization section uploading on publications initialisation (Issue #2418)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/settings/settings.epic.ts
Labels: bug, _priority_1

#2435 fix(chat): removes technical text when renaming a [replay] conversation (Issue #2425)
  apps/chat/src/components/Chatbar/Conversation.tsx
Labels: bug

#2433 fix(chat): fix marketplace cards UI (issue #2426)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/CardsList.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/types/common.ts
  apps/chat/src/utils/app/mobile.ts
  apps/chat/tailwind.config.js
Labels: bug

#2431 fix(chat): remove alt-text of icons (Issue #2436, #2412)
  apps/chat-e2e/src/ui/domData/attributes.ts
  apps/chat-e2e/src/ui/webElements/baseElement.ts
  apps/chat/src/components/Chatbar/ModelIcon.tsx
Labels: bug

#2432 fix(chat): change version dropdown maximum width (Issue #2428)
  apps/chat/src/components/Chat/Publish/VersionSelector.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
Labels: bug

#2437 fix(chat): add back to chat button on marketplace mobile (Issue #2243)
  apps/chat/src/components/Header/BackToChatMobile.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
Labels: bug

#2405 feat(chat): create new conversation after initialization (adapted for Marketplace) (Issue #2351)
  apps/chat-e2e/src/assertions/baseAssertion.ts
  apps/chat-e2e/src/core/baseFixtures.ts
  apps/chat-e2e/src/tests/abortedReplay.test.ts
  apps/chat-e2e/src/tests/accountSettings.test.ts
  apps/chat-e2e/src/tests/announcementBanner.test.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/chatBarFolderConversation.test.ts
  apps/chat-e2e/src/tests/chatExportImport.test.ts
  apps/chat-e2e/src/tests/chatExportImportWithAttachment.test.ts
  apps/chat-e2e/src/tests/chatHeader.test.ts
  apps/chat-e2e/src/tests/chatHeaderSettings.test.ts
  apps/chat-e2e/src/tests/chatSelectionFunctionality.test.ts
  apps/chat-e2e/src/tests/chatSwitch.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/conversationNameNumeration.test.ts
  apps/chat-e2e/src/tests/conversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/conversationWithAttachmentInResponse.test.ts
  apps/chat-e2e/src/tests/conversationWithStage.test.ts
  apps/chat-e2e/src/tests/duplicateConversation.test.ts
  apps/chat-e2e/src/tests/duplicateSharedConversations.test.ts
  apps/chat-e2e/src/tests/editConversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/editMessageWithAttachment.test.ts
  apps/chat-e2e/src/tests/entityIcon.test.ts
  apps/chat-e2e/src/tests/folderNameNumeration.test.ts
  apps/chat-e2e/src/tests/importSpecific.test.ts
  apps/chat-e2e/src/tests/manageAttachment.test.ts
  apps/chat-e2e/src/tests/mdTableModelResponse.test.ts
  apps/chat-e2e/src/tests/parametrizedReplay.test.ts
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat-e2e/src/tests/promptUsage.test.ts
  apps/chat-e2e/src/tests/publishConversation.test.ts
  apps/chat-e2e/src/tests/publishConversationToOrganisation.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/scrolling.test.ts
  apps/chat-e2e/src/tests/selectChatPanelEntity.test.ts
  apps/chat-e2e/src/tests/shareConversationWithContent.test.ts
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat-e2e/src/tests/sharedWithMeConversations.test.ts
  apps/chat-e2e/src/tests/sideBarFilters.test.ts
  apps/chat-e2e/src/tests/sidePanelEntityDragAndDrop.test.ts
  apps/chat-e2e/src/tests/tokenLimits.test.ts
  apps/chat-e2e/src/tests/uploadFromDevice.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat-e2e/src/ui/webElements/entityTree/entitiesTree.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/baseSideBarConversationTree.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/sideBarEntitiesTree.ts
  apps/chat/src/components/Layout.tsx
  apps/chat/src/hooks/useRouteHistory.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/utils/app/id.ts
Labels: enhancement, _priority_1

#2438 feat(chat): add bookmarks (Issue #2349)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/CardsList.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
Labels: enhancement

#2447 fix(chat): fix markdown table displaying (Issue #2446)
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/styles/globals.css
Labels: bug

#2444 fix(chat): fix version grouping (Issue #2308)
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug

#2462 fix(chat): fix search and Add-button height (Issue #2439)
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: bug

#2453 fix(chat): add no models or application in marketplace (Issue #2448)
  apps/chat/src/components/Common/NoResultsFound.tsx
  apps/chat/src/components/Marketplace/MarketplaceBanner.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug

#2458 fix(chat): don't show not public files when unpublish a conversation (Issue #2126)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug

#2464 feat(chat): fix suggested results display (Issue #2461)
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: enhancement

#2355 feat(chat): refactor application dialogs, add deployable app dialog draft (Issue #2353)
  apps/chat/.env.development
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizard.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizardFooter.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizardHeader.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/components/Common/ApplicationWizard/view-props.ts
  apps/chat/src/components/Common/DropdownSelector.tsx
  apps/chat/src/components/Common/Forms/ControlledFormField.tsx
  apps/chat/src/components/Common/Forms/DynamicFormFields.tsx
  apps/chat/src/components/Common/Forms/Field.tsx
  apps/chat/src/components/Common/Forms/FieldError.tsx
  apps/chat/src/components/Common/Forms/FieldErrorMessage.tsx
  apps/chat/src/components/Common/Forms/FieldTextArea.tsx
  apps/chat/src/components/Common/Forms/Label.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
  apps/chat/src/components/Common/QuickAppDialog.tsx
  apps/chat/src/components/Common/__tests__/MultipleComboBox.test.tsx
  apps/chat/src/components/Files/AttachLinkDialog.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/FunctionStatusIndicator.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/constants/applications.ts
  apps/chat/src/constants/file.ts
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/styles/globals.css
  apps/chat/src/types/applications.ts
  apps/chat/src/types/common.ts
  apps/chat/src/types/models.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/data/application-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/application-api-storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
  apps/chat/src/utils/app/data/text-file-service.ts
  apps/chat/src/utils/server/api.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
  libs/shared/src/types/features.ts
Labels: enhancement

#2468 fix(chat): add code apps source files folder encoding (Issue #2469)
  apps/chat/src/components/Common/ApplicationWizard/form.ts
Labels: bug, _priority_1

#2470 fix(chat): fix icon formats (Issue #2411, #2466)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/Forms/FieldErrorMessage.tsx
  apps/chat/src/components/Files/AttachLinkDialog.tsx
Labels: bug

#2465 fix(chat): remove content top margin (Issue #2461)
  apps/chat/src/components/Marketplace/CardsList.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug

#2485 feat(chat): refactor code app source files folder selector (Issue #2476)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
Labels: enhancement, _priority_1

#2489 feat(chat): add validations for source files (Issue #2475)
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizardFooter.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/components/Common/SelectFolder/SelectFolderFooter.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/constants/applications.ts
  apps/chat/src/utils/app/application.ts
Labels: enhancement

#2492 feat(chat): support new Code Apps format (Issue #2491)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/components/Common/Forms/DynamicFormFields.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/FunctionStatusIndicator.tsx
  apps/chat/src/constants/applications.ts
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/types/applications.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/data/application-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/application-api-storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
Labels: bug, enhancement, _priority_1

#2495 feat(chat): allow admin deploying/undeploying of Code Apps (Issue #2494)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/FunctionStatusIndicator.tsx
Labels: bug, enhancement

#2473 fix(chat): remove mobile and tablet view tooltips from Marketplace (Issue #2441)
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
Labels: bug

#2490 fix(chat): add default values in application dialog (Issue #2477)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/components/Common/Forms/DynamicFormFields.tsx
  apps/chat/src/constants/applications.ts
  apps/chat/src/constants/default-ui-settings.ts
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/types/common.ts
Labels: bug

#2488 feat(chat): add code editor for code apps (Issue #2478)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/utils/app/data/text-file-service.ts
  apps/chat/src/utils/server/api.ts
Labels: enhancement, design, _priority_1

#2498 fix(chat): show toast only about own applications (Issue #2497)
  apps/chat/src/store/application/application.epics.ts
Labels: bug
