Repository epam/ai-dial-chat, pull requests merged in 2024-03, with the labels that each got.

#887 feat(chat): change stop generation displaying (Issue #885)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat/src/components/Chat/ChatInput/ChatInput.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/SendMessageButton.tsx
Labels: enhancement, design

#886 fix(chat): removes sidebar delete and import buttons if only shared items exist (Issue #750)
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Promptbar/components/PromptbarSettings.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
Labels: bug, _priority_3

#892 fix(chat): show always selected model (Issue #873)
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/utils/app/search.ts
Labels: bug

#893 fix(chat): revoke access to folder if folder renamed (Issue #833)
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/store/share/share.epics.ts
Labels: bug, _priority_1

#890 feat(chat): option to set personal custom logo (Issue#783)
  apps/chat/.env.development
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/components/Settings/SettingDialog.tsx
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/data/data-service.ts
  libs/shared/src/types/features.ts
Labels: enhancement, _priority_1

#894 fix(chat): fix file uploading for new folder (Issue #655)
  apps/chat/src/hooks/useHandleFileFolders.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
Labels: bug

#898 fix(chat): fix unavailable model displaying (Issue #873)
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
Labels: bug

#906 fix(chat): fix hiding chatbar (Issue #905)
  apps/chat/src/store/conversations/conversations.epics.ts
  package-lock.json
Labels: bug

#913 fix(chat): fix compare name generation (Issue #911)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug

#914 fix(chat): use only first line for conversation name (Issue #912)
  apps/chat/src/utils/app/common.ts
Labels: enhancement

#897 feat(chat): regenerate redesign (Issue #878)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInput.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
Labels: enhancement

#925 feat(chat): change the regenerate button to an icon in compare mode (Issue #924)
  apps/chat/src/components/Chat/Chat.tsx
Labels: enhancement

#929 fix(chat): add `{` and `}` in not allowed symbols (Issue #928)
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat/src/utils/app/file.ts
Labels: bug

#930 fix(chat): add `{` and `}` in not allowed symbols (Issue #928)
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat/src/utils/app/file.ts
Labels: bug

#931 fix(chat): fix compare name generation (Issue #921)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug

#943 fix(chat): don't use system message for playback and compare (Issue #942)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1

#944 fix(chat): don't use system message for playback and compare (Issue #942)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1

#937 fix(chat): fix autofocus to send message input (Issue #916)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
Labels: bug

#946 fix(chat): fix conversation name regeneration (Issue #921)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/utils/app/conversation.ts
Labels: bug, _priority_1

#945 fix(chat): hide full width setting for mobile (Issue #613)
  apps/chat/src/components/Settings/SettingDialog.tsx
Labels: bug

#941 fix(chat): updated Playback first screen. Removed model name from the Playback button(#939)
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/Playback/PlaybackModelButton.tsx
Labels: bug, _priority_1

#955 fix: correct model highlighting for the model in the models list for the Playback and Replay (Issue #936)
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/ReplayAsIsButton.tsx
  apps/chat/src/components/Common/NonModelButton.tsx
Labels: bug, _priority_1

#957 fix(chat): fix custom logo (Issue #920 )
  apps/chat/src/components/Header/Header.tsx
Labels: bug

#958 fix(chat): fix custom logo (Issue #920 )
  apps/chat/src/components/Header/Header.tsx
Labels: bug

#961 fix(chat): fix app name for migration backup (Issue #959)
  apps/chat/src/store/import-export/importExport.epics.ts
Labels: bug

#963 fix(chat): fix chat name generation when have attachments (Issue #960)
  apps/chat/src/utils/app/common.ts
Labels: bug

#965 fix(chat): patch 0.6.6 (Issue #959, #960)
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/utils/app/common.ts
Labels: bug

#969 fix(chat): revert edit mode textarea reset logic (Issue #916)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
Labels: bug

#976 fix: remove redundant condition (Issue #974)
  apps/chat/src/utils/app/share.ts
Labels: bug, _priority_1

#975 fix(chat): remove unshare option from newly created item (Issue #825)
  apps/chat/src/components/Common/ItemContextMenu.tsx
Labels: bug

#964 fix(chat): fix shared folder removing (Issue #847)
  apps/chat/src/store/share/share.epics.ts
Labels: bug

#940 feat(chat): make prompt content field required (Issue #78)
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/prompts.ts
Labels: bug

#982 fix(chat): fix encode url for API (Issue #981)
  apps/chat/src/utils/server/api.ts
  apps/chat/src/utils/server/get-headers.ts
  apps/chat/src/utils/server/server.ts
Labels: bug

#991 fix(chat): handle encode url exceptions (Issue #981)
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
Labels: bug

#978 fix(chat): fix encode url for API (Issue #981, #974)
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/share.ts
  apps/chat/src/utils/server/api.ts
  apps/chat/src/utils/server/get-headers.ts
  apps/chat/src/utils/server/server.ts
Labels: bug

#987 fix(chat): hide scroll down button if there no messages in selected conversations (Issue #927)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#993 fix(chat): show import button instead export if there no my conversations and fix renaming text (Issues #989, #985)
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
Labels: bug

#995 fix(chat): fix attachments/replay/playback height (Issues #932, #994)
  apps/chat/src/components/Chat/ChatInput/ChatInputAttachment.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputAttachments.tsx
  apps/chat/src/components/Common/NonModelButton.tsx
Labels: bug

#997 fix(chat): fix prompt name truncation (Issue #977)
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/store/prompts/prompts.reducers.ts
Labels: bug

#988 fix: fixed file name color in the File Manager
  apps/chat/src/components/Files/FileItem.tsx
Labels: bug

#998 fix(chat): fix encoding space (Issue #999)
  apps/chat/src/utils/server/api.ts
Labels: bug

#1000 fix(chat): fix encoding space (Issue #999)
  apps/chat/src/utils/server/api.ts
Labels: bug

#1005 fix(chat): not allow dots in the end of name (Issue #1003)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/folders.ts
Labels: bug, enhancement

#1006 fix(chat): not allow dots in the end of name (Issue #1003)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/folders.ts
Labels: bug, enhancement

#983 feat(chat): add conversations context menu loader (Issue #843)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/types/menu.ts
Labels: bug

#1020 fix(chat): fix unicode splitting and not delete if create fails (Issue #1018)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/utils/app/common.ts
  package-lock.json
  package.json
Labels: bug, _priority_1

#1009 fix(chat): add not allowed model messages to assistant model (Issue #621)
  apps/chat/src/components/Chat/AssistantSubModelSelector.tsx
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Common/Combobox.tsx
Labels: bug

#1011 fix(chat): fix context menu for mobile (Issue #1010)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug

#1031 feat(chat): add render support for other image types (webp, svg, bmp, ico, avif, apng) (Issue #883)
  apps/chat/src/components/Chat/MessageAttachment.tsx
Labels: enhancement

#996 fix(chat): fix displaying spaces in names (Issue #973)
  apps/chat/src/components/Chat/AddonsDialog.tsx
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ChatInfoTooltip.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputFileAttachment.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Chat/MessageStage.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/PublishAttachment.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/ReportIssueDialog.tsx
  apps/chat/src/components/Chat/RequestApiKeyDialog.tsx
  apps/chat/src/components/Chat/VariableModal.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/CollapsableSection.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Common/Tooltip.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Search/SearchFilterRenderer.tsx
  apps/chat/src/pages/_app.tsx
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/ui/ui.epics.ts
Labels: bug

#1017 fix(chat): fix chats and chat folders removing if such exist somewhere in 'shared with me' section (Issue #838)
  apps/chat/src/store/conversations/conversations.reducers.ts
Labels: bug

#1028 fix(chat): show error message for renaming if dots in the end of name (Issue #1022)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/utils/app/common.ts
Labels: bug

#1041 fix(chat): hide message buttons if message is generating (Issue #910)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
Labels: bug, _priority_3

#1046 fix(chat): add `\` in not allowed symbols (Issue #821)
  apps/chat/src/utils/app/file.ts
Labels: bug

#1052 fix(chat): fix prompt variables logic (Issue #950)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/PromptVariablesDialog.tsx
  apps/chat/src/components/Chat/SystemPrompt.tsx
  apps/chat/src/components/Chat/VariableModal.tsx
  apps/chat/src/hooks/usePromptSelection.ts
  apps/chat/src/utils/app/prompts.ts
Labels: bug

#1045 fix(chat): add long chat name truncation when choosing a chat to compare (Issue #1037)
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
  apps/chat/src/components/Common/Combobox.tsx
Labels: bug

#1062 fix(chat): don't request listing for new folder (Issue #1061)
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
Labels: bug

#1067 fix(chat): fix tooltip wraps (Issue #1059)
  apps/chat/src/components/Common/Tooltip.tsx
Labels: bug

#1069 fix: fix cutting long header string in common modal (Issue #1064)
  apps/chat/src/components/Common/Modal.tsx
Labels: bug

#1068 feat: add ability to use supported types label insead of long extensions list (Issue #919)
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
Labels: enhancement

#1071 fix(chat): handle items with invalid names (Issue #1007, #1038)
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Common/ContextMenu.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Common/ShareIcon.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/conversation.ts
Labels: enhancement

#1057 fix(chat): remove gradient and change message content size (Issues #1044, #949)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/testData/expectedMessages.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInput.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/ChatReplayControls.tsx
  apps/chat/src/components/Chat/ChatReplayControls.tsx
  apps/chat/src/components/Chat/NotAllowedModel.tsx
  apps/chat/src/components/Chat/Playback/PlaybackControls.tsx
  apps/chat/src/styles/globals.css
Labels: bug

#1078 fix(chat): fix draggable zone for recent conversations and prompts (Issue #1077)
  apps/chat/src/components/Sidebar/Sidebar.tsx
Labels: bug

#1032 feat(chat): add attachment charts support (Issue #1021)
  .ort.yml
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Chat/MessageAttachments.tsx
  apps/chat/src/components/Plotly/Plotly.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/utils/app/data/file-service.ts
  package-lock.json
  package.json
Labels: enhancement, _priority_1

#1073 fix(chat): fix last message check (Issue #910)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
Labels: bug

#1084 fix(chat): save input text if connection lost (Issue #790)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  package-lock.json
Labels: bug

#1097 fix(chat): remove horizontal scroll (Issues #1095, #1092)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/AdjustedTextarea.tsx
Labels: bug

#1086 feat(chat): add buttons to copy tables (Issue #489)
  apps/chat/src/components/Markdown/ChatMDComponent.tsx
  apps/chat/src/components/Markdown/Table.tsx
  apps/chat/src/types/chat.ts
Labels: enhancement, _priority_2

#1101 fix(chat): forbid % and & symbols and folder names preparing (Issue #1099)
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/folders.ts
Labels: bug

#1093 fix(chat): clear text if can save question (Issue #1089)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
Labels: bug

#1087 fix(chat): fix folder dots remains even if folder not in focus (Issue #599)
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#1114 fix(chat): decrease refresh token timeout (Issue #1075)
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug

#1124 fix(chat): revise our labels/messages to reflect accurate name definitions (Issue #1008)
  apps/chat-e2e/src/hooks/global-setup.ts
  apps/chat-e2e/src/hooks/global-teardown.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/selectors/sideBarSelectors.ts
  apps/chat-e2e/src/ui/webElements/addons.ts
  apps/chat-e2e/src/ui/webElements/chatHeader.ts
  apps/chat-e2e/src/ui/webElements/sendMessage.ts
  apps/chat-e2e/src/utils/fileUtil.ts
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/ChatExternalControls.tsx
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Common/__tests__/MultipleComboBox.test.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/components/Settings/SettingDialog.tsx
  apps/chat/src/components/Sidebar/BetweenFoldersLine.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/constants/folders.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/file-service.ts
  libs/overlay/src/lib/ChatOverlay.ts
Labels: bug, enhancement

#1125 feat(chat): add ability to select entities to migrate (Issue #1119)
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
Labels: enhancement

#1117 fix(chat): fix conversations migration, prompt variables logic and decrease refresh token timeout (Issues #950, #1075, #1106, #1119)
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/PromptVariablesDialog.tsx
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/components/Chat/SystemPrompt.tsx
  apps/chat/src/components/Chat/VariableModal.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/hooks/usePromptSelection.ts
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/types/chat.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/data/prompt-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/prompts.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug

#1133 fix(chart): fix charts import (Issue #1132)
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug

#1131 fix(chat): fix conversations migration and decrease refresh token timeout (Issues #1075, #1106, #1119, #1132)
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/types/chat.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/data/prompt-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug, enhancement

#1121 fix(chat): hide scroll down button if message is empty (Issue #927)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#1135 fix(chat): update tooltip for shared entities with incorrect names (Issue #1123
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/utils/app/errors.ts
Labels: bug, enhancement

#1108 fix(chat): fix conversation selecting if delete selected share with me conversation entity (Issues #1074, #1129)
  apps/chat-e2e/src/tests/sharedWithMe.test.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/share/share.epics.ts
Labels: bug

#1120 fix(chat): fix shared entity opening (Issue #1072)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/share/share.epics.ts
Labels: bug

#1141 fix(chat): fix regenerate button after last message error (Issue #1118)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#1144 fix(chat): hide copy and download buttons for code block and table if last message is being generating (Issue #1085)
  apps/chat/src/components/Markdown/ChatMDComponent.tsx
  apps/chat/src/components/Markdown/CodeBlock.tsx
  apps/chat/src/components/Markdown/Table.tsx
Labels: bug, enhancement

#1145 fix(chat): add error message and border if dot at the end of prompt name appears while renaming (Issue #1103)
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/components/Common/EmptyRequiredInputMessage.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
Labels: bug

#1148 fix(chat): show spaces in folder name (Issue #1090)
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#1157 fix(chat): disable context menu for attachment/table/code block buttons (Issue #1156)
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Markdown/CodeBlock.tsx
  apps/chat/src/components/Markdown/Table.tsx
Labels: bug

#1152 feat(chat): implement isolated model view page (Issue #1154)
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/pages/_app.tsx
  apps/chat/src/pages/_document.tsx
  apps/chat/src/pages/index.tsx
  apps/chat/src/pages/models/[modelId].tsx
  apps/chat/src/store/addons/addons.epics.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/utils/app/data/bucket-service.ts
  apps/chat/src/utils/app/data/data-service.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/server/__tests__/api.test.ts
  apps/chat/src/utils/server/api.ts
Labels: enhancement

#1164 fix(chat): fix chat input height (Issue #1150)
  apps/chat/src/components/Chat/ChatMessage/AdjustedTextarea.tsx
Labels: bug

#1160 feat(chat): add possibility to duplicate own chats and prompts (Issue #1137)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat/src/components/Common/ItemContextMenu.tsx
Labels: enhancement

#1149 fix(chat): replace addons and talk to modals over side panels (Issue #1100)
  apps/chat/src/components/Chat/AddonsDialog.tsx
  apps/chat/src/components/Chat/ModelsDialog.tsx
Labels: bug

#1161 feat(chat): add overlay when menu on mobile is open (Issue #1159)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/store/ui/ui.reducers.ts
Labels: bug
