Repository epam/ai-dial-chat, pull requests merged in 2024-02, with the labels that each got.

#647 fix: forbid # and \ symbols
  apps/chat/src/utils/app/file.ts
Labels: bug

#630 feat(chat): add export and import with content(issue 568)
  .ort.yml
  apps/chat-e2e/src/testData/conversationHistory/importConversation.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/testData/import/ai_dial_chat_history_1-4_version.json
  apps/chat-e2e/src/testData/import/ai_dial_chat_history_1-9_version.json
  apps/chat-e2e/src/tests/chatExportImport.test.ts
  apps/chat/public/images/icons/loader.svg
  apps/chat/src/components/Chat/Addons.tsx
  apps/chat/src/components/Chat/AddonsDialog.tsx
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ChatInfoTooltip.tsx
  apps/chat/src/components/Chat/ChatLoader.tsx
  apps/chat/src/components/Chat/ChatMessage.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/MessageStage.tsx
  apps/chat/src/components/Chat/ModelDescription.tsx
  apps/chat/src/components/Chat/ModelsDialog.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Chatbar/Conversations.tsx
  apps/chat/src/components/Chatbar/ConversationsRenderer.tsx
  apps/chat/src/components/Chatbar/ExportModal.tsx
  apps/chat/src/components/Chatbar/ImportExportLoader.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Common/FullPageLoader.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Common/SidebarMenu.tsx
  apps/chat/src/components/Common/Spinner.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptbarSettings.tsx
  apps/chat/src/components/Settings/Import.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/store/index.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/types/files.ts
  apps/chat/src/types/importExport.ts
  apps/chat/src/utils/app/__tests__/importExports.test.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/app/zip-import-export.ts
  apps/chat/tailwind.config.js
  package-lock.json
  package.json
Labels: enhancement

#649 feat(chat): remove BetweenFoldersLine and don't save open folder ids (Issue #165)
  apps/chat-e2e/src/core/localStorageManager.ts
  apps/chat-e2e/src/testData/conversationHistory/conversationData.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/chatBarFolderConversation.test.ts
  apps/chat-e2e/src/tests/chatExportImport.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/folderPrompts.test.ts
  apps/chat-e2e/src/tests/promptExportImport.test.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/sideBarFilters.test.ts
  apps/chat-e2e/src/tests/sidePanelEntityDragAndDrop.test.ts
  apps/chat/src/components/Chat/Addons.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Sidebar/BetweenFoldersLine.tsx
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/utils/app/data/data-service.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/move.ts
  package-lock.json
Labels: enhancement

#654 fix(chat): fix import for attachments in stages(issues #651,#652)
  apps/chat/src/components/Common/FullPageLoader.tsx
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/app/zip-import-export.ts
Labels: bug, enhancement

#637 feat(chat): automigration (Issue #265)
  apps/chat/src/components/Chat/Migration/Migration.tsx
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/components/Common/Loader.tsx
  apps/chat/src/constants/default-settings.ts
  apps/chat/src/pages/api/[entitytype]/[...slug].ts
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/data/data-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
  apps/chat/src/utils/server/get-headers.ts
Labels: enhancement, _priority_1

#675 fix(chat): fix remove folder logic (Issue #671)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug

#678 fix(chat): fix rerender conversation settings issues (Issue #676, #688, #671)
  apps/chat/src/pages/api/[entitytype]/[...slug].ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/types/common.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/prompts.ts
  apps/chat/src/utils/server/get-headers.ts
Labels: bug

#694 feat(chat): implement unique entitiy names validation (Issue #633)
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/constants/default-settings.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/conversation.ts
Labels: enhancement, _priority_1

#693 feat(chat): encode each URL component separately (Issue #663)
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/data/data-service.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/server/api.ts
Labels: enhancement, technical debt

#710 fix(chat): fix prompt counter when creating new prompt (Issue #705)
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug

#713 fix(chat): fix new created prompt appears in three sections (Issue #696)
  apps/chat/src/store/prompts/prompts.selectors.ts
Labels: bug

#701 fix(chat): handle API errors (Issue #663)
  apps/chat/src/pages/api/[entitytype]/[...slug].ts
  apps/chat/src/pages/api/listing/[...listing].ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
  apps/chat/src/utils/server/api.ts
Labels: enhancement, technical debt

#722 fix(chat): fix saving addons on settings panel (Issue #681)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#721 fix(chat): fix duplicate entity structure if move to new folder (Issue #720)
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug

#736 fix(chat): handle bucket request error (Issue #733, #728)
  apps/chat/src/constants/errors.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/settings/settings.epic.ts
Labels: bug

#746 fix(chat): fix prompt folders drag&drop (Issue #745)
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#748 fix(chat): fixed maximum file uploading count (Issue #656)
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
Labels: bug

#729 fix(chat): fix error message for failed removing (Issue #724, #691)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug

#749 fix(chat): use NEXT_PUBLIC_DEFAULT_TEMPERATURE if it equals 0 (Issue #588)
  apps/chat/src/constants/default-settings.ts
Labels: bug

#762 fix(chat): fix applying temperature (Issue #588)
  apps/chat/src/pages/api/chat.ts
Labels: bug

#759 feat(chat): hide context menu options for empty chat (Issue #755, #758)
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: enhancement

#763 fix(chat): fix entity updates even if error occure while recreation (Issue #740)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
Labels: bug

#717 fix(chat): fix migration issues (Issue #668)
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
Labels: bug

#766 fix: fix applying temperature (Issue #588)
  src/constants/default-settings.ts
  src/pages/api/chat.ts
Labels: bug

#770 fix(chat): fix removing files(Issue #771)
  apps/chat/src/utils/app/data/file-service.ts
Labels: bug

#773 fix(chat): hide context menu options for empty folders (Issue #756)
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: enhancement

#776 fix(chat): debounce system prompt updating (Issue #757)
  apps/chat-e2e/src/ui/webElements/entitySettings.ts
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chat/SystemPrompt.tsx
  apps/chat/src/hooks/usePromptSelection.ts
  apps/chat/src/utils/app/common.ts
  package-lock.json
  package.json
Labels: bug

#765 fix(chat): add spinner while create new entity or delete all entities (Issue #725)
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Header/CreateNewChatMobile.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/store/share/share.epics.ts
Labels: bug

#787 fix(chat): fix attachment limit (Issue #656, #278)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug

#799 fix(chat): fix system prompt applying (Issue #610)
  apps/chat/src/components/Chat/SystemPrompt.tsx
  apps/chat/src/hooks/usePromptSelection.ts
Labels: bug, _priority_1

#786 fix(chat): add possibility to create entities if such exists on another tab (Issue #769)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/data/conversation-service.ts
  apps/chat/src/utils/app/data/prompt-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
Labels: bug

#802 fix(chat): fix import export (issues: #640, #768, #767)
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/types/import-export.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/app/zip-import-export.ts
Labels: bug, _priority_1

#811 fix(chat): fix files deleting while edit message (Issue #772)
  apps/chat/src/utils/app/file.ts
Labels: bug

#813 fix(chat): don't display "replay" model (Issue #679, #810)
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/server/api.ts
Labels: bug

#806 feat(chat): add possibility to preview shared prompt (Issue #743)
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
Labels: enhancement, _priority_1

#801 fix(chat): fix autoscrolling for next chat and chat regeneration (Issues #501, #500)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/utils/data/throttle.ts
Labels: bug

#824 feat(chat): add a model version selector (Issue #468)
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/selectors/dialogSelectors.ts
  apps/chat-e2e/src/ui/webElements/modelsDialog.ts
  apps/chat-e2e/src/ui/webElements/recentEntities.ts
  apps/chat/src/components/Chat/AddonsDialog.tsx
  apps/chat/src/components/Chat/AssistantSubModelSelector.tsx
  apps/chat/src/components/Chat/ChatInfoTooltip.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/ModelDescription.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Chat/ModelsDialog.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/types/openai.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/search.ts
Labels: enhancement, design

#827 fix(chat): fix compare mode list view (Issue #661)
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
Labels: bug

#830 fix(chat): fix loading flag set for child folder items (Issue #817)
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
Labels: bug

#831 fix(overlay): fix export and import from overlay (Issue #567)
  libs/overlay/src/lib/ChatOverlay.ts
Labels: bug

#835 feat(chat): add icons for model versions (Issue #468)
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/utils/app/conversation.ts
Labels: bug

#837 fix(chat): not allow to expand on initial screen (Issue #468)
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
Labels: bug

#839 fix(chat): fix "report a issue" and "request api key" modals (Issue #836)
  apps/chat/src/components/Common/FooterMessage.tsx
  apps/chat/src/hooks/useUrlHash.ts
Labels: bug

#561 chore(chat): create PR and Issue templates
  .github/ISSUE_TEMPLATE/01_report_a_issue.yml
  .github/ISSUE_TEMPLATE/02_feature_request.yml
  .github/ISSUE_TEMPLATE/03_bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
Labels: documentation, enhancement, technical debt

#845 fix(chat): fix templates (Issue #556)
  .github/ISSUE_TEMPLATE/config.yml
  .github/pull_request_template.md
Labels: enhancement

#826 feat(chat): change playback start screen(issue #600, #834)
  apps/chat-e2e/src/testData/expectedMessages.ts
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat/src/components/Chat/Addons.tsx
  apps/chat/src/components/Chat/AssistantSubModelSelector.tsx
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatSettings.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Playback/PlaybackControls.tsx
  apps/chat/src/components/Chat/Playback/PlaybackEmptyInfo.tsx
  apps/chat/src/components/Chat/Playback/PlaybackModelButton.tsx
  apps/chat/src/components/Chat/SystemPrompt.tsx
  apps/chat/src/components/Chat/Temperature.tsx
  apps/chat/src/components/Chat/__tests__/PlaybackControls.test.tsx
  apps/chat/src/components/Common/DisableOverlay.tsx
  apps/chat/src/components/Common/NonModelButton.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: enhancement, design, _priority_1

#848 fix(chat): fix model version displaying in sorted order (Issue #468)
  .github/ISSUE_TEMPLATE/03_bug_report.yml
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Chat/ModelsDialog.tsx
  apps/chat/src/store/models/models.reducers.ts
Labels: bug

#853 fix(chat): fix file manager root folder renaming (Issue #812)
  apps/chat/src/hooks/useHandleFileFolders.ts
Labels: bug

#849 fix(chat): import with attachments itegration with the Api (Issue #819)
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/app/zip-import-export.ts
Labels: bug

#855 feat(chat): set desc-order for model versions (Issue #468)
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
Labels: enhancement

#841 chore: add publish for development version (Issue #761)
  .github/workflows/deploy_dev.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/pr-title-check.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  README.md
  libs/overlay/project.json
  libs/shared/project.json
  tools/publish-lib.mjs
Labels: enhancement, _priority_2

#859 chore(chat): refactor of util-methods (part1) (Issue #793)
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
  apps/chat/src/components/Chat/ChatMessage.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chat/__tests__/PlaybackControls.test.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Chatbar/Conversations.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Files/Download.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Promptbar/components/PromptbarSettings.tsx
  apps/chat/src/pages/api/[entitytype]/[...slug].ts
  apps/chat/src/pages/api/listing/[...listing].ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/types/common.ts
  apps/chat/src/types/error.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/__tests__/importExports.test.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/data/prompt-service.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
  apps/chat/src/utils/app/data/storages/api/prompt-api-storage.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/app/mappers.ts
  apps/chat/src/utils/app/search.ts
  apps/chat/src/utils/app/share.ts
  apps/chat/src/utils/auth/timeout-async.ts
  apps/chat/src/utils/server/api.ts
  apps/chat/src/utils/server/error.ts
  apps/chat/src/utils/server/index.ts
  apps/chat/src/utils/server/server.ts
Labels: enhancement, technical debt

#852 feat(chat): redesign mobile and overlay (Issue #618, #98)
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Chat/MemoizedChatMessage.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/components/Header/User/ProfileButton.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug

#861 feat(chat): add confirmation dialog for file deleting (Issue #593)
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: enhancement

#864 chore(chat): fix clear all and refactor of util-methods (part 2) (Issue #793, #780, #842)
  apps/chat/src/components/Chat/__tests__/FooterMessage.test.tsx
  apps/chat/src/components/Common/FooterMessage.tsx
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/folders.ts
  package-lock.json
  package.json
Labels: enhancement, technical debt

#866 fix(chat): fix highlight after file download (Issue #685)
  apps/chat/src/components/Files/FileItemContextMenu.tsx
Labels: bug

#867 fix(chat): fix confirm file deleting (Issue #593)
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug

#870 fix(chat): fix shared prompt duplicates (Issue #816)
  apps/chat/src/store/prompts/prompts.reducers.ts
Labels: bug

#872 feat(chat): support rendering gif-file as image (Issue #871)
  apps/chat-e2e/src/testData/api/fileApiHelper.ts
  apps/chat/src/components/Chat/MessageAttachment.tsx
Labels: enhancement

#876 fix(chat): fix duplication chat/prompt (Issue #777)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Chatbar/Conversations.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/Prompts.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/app/search.ts
Labels: bug

#860 feat(chat): add auto opening for accepted share item (Issues #796, #727, #874)
  apps/chat/src/pages/api/share/details.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/types/share.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/id.ts
Labels: enhancement, _priority_1

#881 fix(chat): disable send when last message error (Issue #532)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug, _priority_1

#869 fix(chat): fix select folder and upload from device screens width (Issue #595)
  apps/chat/src/components/Common/SelectFolder/SelectFolder.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
Labels: bug

#884 fix(chat): fix import export for shared with me resources (Issue #798)
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
Labels: bug, _priority_1
