Repository epam/ai-dial-chat, pull requests merged in 2024-07, with the labels that each got.

#1673 feat(chat): redesign publication filters (Issue #1640)
  apps/chat/src/components/Chat/Publish/CompareRulesModal.tsx
  apps/chat/src/components/Chat/Publish/FilterFunctionSelect.tsx
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/RegexParamInput.tsx
  apps/chat/src/components/Chat/Publish/RuleListItem.tsx
  apps/chat/src/components/Chat/Publish/RulesSelect.tsx
  apps/chat/src/components/Chat/Publish/TargetAudienceFilter.tsx
  apps/chat/src/components/Chat/Publish/TargetAudienceFilterComponent.tsx
  apps/chat/src/components/Chat/Publish/UserGroupFilter.tsx
  apps/chat/src/components/Chat/__tests__/TargetAudienceFilter.test.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/types/publication.ts
  apps/chat/src/utils/app/data/publication-service.ts
Labels: enhancement

#1654 fix(chat): scroll down icon position (Issue #1611, #1632, #1660)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatExternalControls.tsx
  apps/chat/src/components/Chat/NotAllowedModel.tsx
  apps/chat/src/components/Chat/Playback/PlaybackControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
Labels: bug

#1678 feat(chat): redesign approve required modal (Issue #1676)
  apps/chat-e2e/src/ui/webElements/sideBar.ts
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Common/CollapsibleSection.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/types/common.ts
Labels: enhancement

#1702 feat(chat): show header "add conversation" icon on tablets (Issue #1682)
  apps/chat/public/images/icons/circle-plus.svg
  apps/chat/src/components/Header/CreateNewChatMobile.tsx
Labels: enhancement

#1708 fix(chat): fix addon name wrapping (Issue #1467)
  apps/chat/src/components/Chat/AddonsDialog.tsx
Labels: bug

#1719 feat(cha-e2e): revert baseUrl change
  apps/chat-e2e/config/overlay.playwright.config.ts
Labels: e2e

#1720 fix(chat): fix external entities export (Issue #1434)
  .gitignore
  apps/chat-e2e/src/testData/conversationHistory/importPrompt.ts
  apps/chat-e2e/src/tests/chatExportImport.test.ts
  apps/chat-e2e/src/tests/promptExportImport.test.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug

#1711 fix(chat): use latest used model (Issue #1672)
  .eslintignore
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug

#1705 fix(chat): fix button alignment for prompt review mode, filters UI (Issues #1696, #1700, #1701)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/RegexParamInput.tsx
  apps/chat/src/components/Chat/Publish/TargetAudienceFilterComponent.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
Labels: bug

#1697 fix(chat): fix search for select folder and change path dialogs, folders order for change path dialog (Issue #1687)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Common/CollapsibleSection.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/utils/app/search.ts
Labels: bug

#1570 feat(chat): add support for the http in opentelemetry instrumentation (Issue #1138)
  apps/chat-e2e/.env.development
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/src/opentelemetry.ts
  apps/chat/src/utils/server/logger.ts
  package-lock.json
  package.json
Labels: enhancement

#1723 fix(chat): fix filters words wrap and approve required compare mode (Issue #1700)
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/RuleListItem.tsx
Labels: bug

#1725 fix(chat): fix temporary folders displaying (Issue #1724)
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug, _priority_1

#1687 fix(chat): fix publication request mobile scroll (Issue #1618)
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug

#1733 fix(chat): fix font size for collapsible sections in 'Approve Required' section modals (Issue #1591)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
Labels: bug

#1740 fix(chat): fix temporary prompt folders displaying (Issue #1724)
  apps/chat/src/store/prompts/prompts.selectors.ts
Labels: bug, _priority_1

#1741 fix(chat): fix send publication request modal sections font size (Issue #1591)
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
Labels: bug

#1750 fix(chat): fix standard logo size
  apps/chat/src/components/Header/Header.tsx
Labels: bug

#1751 fix(chat): fix standard logo size
  apps/chat/src/components/Header/Header.tsx
Labels: bug, PATCH

#1755 fix(chat): fix combined request review and change 'go to review...' button text if review started (Issues #1748, #1754)
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
Labels: bug, enhancement

#1674 feat(chat): add focus on new created folder (Issue #1589, #1512)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/store/conversations/conversations.reducers.ts
Labels: enhancement

#1726 feat(chat): add default value in prompt variables (Issue #1592)
  apps/chat/src/components/Chat/ChatInput/PromptVariablesDialog.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/constants/folders.ts
  apps/chat/src/types/prompt.ts
  apps/chat/src/utils/app/prompts.ts
  package-lock.json
Labels: enhancement

#1749 fix(chat): disable approve button and add error message if unpublished entity exists in approve required modal (Issue #1422)
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/types/common.ts
Labels: bug, _priority_2

#1760 fix(chat): fix replacement attachment type after import (Issue #1759)
  apps/chat/src/utils/app/import-export.ts
Labels: bug

#1763 fix(chat): fix replacement attachment type after import (Issue #1759)
  apps/chat/src/utils/app/import-export.ts
Labels: bug, PATCH

#1731 feat(chat): add TRUE and FALSE publication filter, redesign filters for mobile (Issues #1442, #1732)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/RegexParamInput.tsx
  apps/chat/src/components/Chat/Publish/RulesSelect.tsx
  apps/chat/src/components/Chat/Publish/TargetAudienceFilterComponent.tsx
  apps/chat/src/components/Chat/__tests__/TargetAudienceFilter.test.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
  apps/chat/src/types/publication.ts
Labels: enhancement

#1768 fix(chat): fix replacement prompt with variables by content (Issue #1766)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/SystemPrompt.tsx
  apps/chat/src/hooks/usePromptSelection.ts
Labels: bug, _priority_1

#1769 fix(chat): fix mobile logo size (Issue #1767)
  apps/chat/src/components/Header/Header.tsx
Labels: bug, _priority_1

#1773 fix(chat): fix root items unpublishing and empty rules section (Issues #1762, #1771)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/folders.ts
Labels: bug, _priority_1

#1774 fix(chat): fix replacement prompt with variables by content and mobile logo size (Issue #1766, #1767)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/SystemPrompt.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/hooks/usePromptSelection.ts
Labels: bug, PATCH

#1791 feat(chat): support template markup for Replay functionality (Issue #1592, #1783, #1784, #1788)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatControls.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/PromptVariablesDialog.tsx
  apps/chat/src/components/Chat/ChatInput/ReplayVariables.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/types/chat.ts
  apps/chat/src/utils/app/__tests__/prompts.test.ts
  apps/chat/src/utils/app/prompts.ts
Labels: enhancement, _priority_1

#1794 fix(chat): truncate long prompt names (Issue #1790)
  apps/chat/src/components/Chat/ChatInput/PromptList.tsx
Labels: bug

#1796 fix(chat): fix prompt displaying with long or multiline text (Issue #1792)
  apps/chat/src/components/Chat/ChatInput/PromptVariablesDialog.tsx
  apps/chat/src/components/Chat/ChatInput/ReplayVariables.tsx
  apps/chat/src/components/Common/Tooltip.tsx
  apps/chat/src/utils/app/prompts.ts
Labels: bug, _priority_1

#1797 fix(chat): fix sidebar menu items count calculation (Issue #1710)
  apps/chat/src/components/Common/SidebarMenu.tsx
Labels: bug, _priority_1

#1803 fix(chat): fix changing of model for replay mode (Issue #1662)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatControls.tsx
  apps/chat/src/components/Chat/ChatInput/PromptVariablesDialog.tsx
  apps/chat/src/components/Chat/ChatInput/ReplayVariables.tsx
  apps/chat/src/components/Chat/ChatSettings.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/ReplayAsIsButton.tsx
  apps/chat/src/components/Chat/StartReplayButton.tsx
  apps/chat/src/constants/chat.ts
Labels: bug

#1806 feat(chat): remove TRUE/FALSE filters (Issue #1805)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/TargetAudienceFilterComponent.tsx
  apps/chat/src/components/Chat/__tests__/TargetAudienceFilter.test.tsx
  apps/chat/src/types/publication.ts
Labels: enhancement

#1809 fix(chat): fix continue of generation for paused replay message (Issue #1784, #1414)
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatControls.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug, _priority_1

#1821 feat(chat): replace "show more" by "show previous" for stages and show last 3 stages by default (Issue 1820)
  apps/chat-e2e/src/assertions/chatMessagesAssertion.ts
  apps/chat-e2e/src/tests/conversationWithStage.test.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/webElements/chatMessages.ts
  apps/chat/src/components/Chat/MessageStages.tsx
Labels: enhancement

#1813 fix(chat): fix importing playback & replay conversation with attachments (Issue #1617)
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug

#1825 fix(chat): fix replay flag check on extracting attachments from conversation (Issue #1824)
  apps/chat/src/utils/app/folders.ts
Labels: bug

#1808 chore(chat): add token decoding to be able to check if user is admin (part 1) (Issue #1434)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/index.d.ts
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/auth/auth.reducers.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: enhancement

#1822 feat(chat): support model `reference` instead of `id` into `conversationId` (Issue #1811)
  apps/chat/src/components/Chat/AssistantSubModelSelector.tsx
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/types/models.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
Labels: enhancement, _priority_1

#1810 fix: fix import conversation with attachments to show one dialog for all items (Issue #1237)
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/constants/successMessages.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug

#1830 feat(chat): add dots to unread publications (Issue #1457)
  apps/chat/src/components/Chat/ChatExternalControls.tsx
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Chat/Publish/ReviewDot.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/CollapsibleSection.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/publication/publication.selectors.ts
Labels: enhancement

#1832 chore(chat): remove BackendDataNodeType from publications epic (Issue #1831)
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/data/publication-service.ts
Labels: technical debt

#1826 fix: [Mobile] Re-design of 'Chat settings' and 'Addons dialog' modals (Issue #1468)
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/core/dialSharedWithMeFixtures.ts
  apps/chat-e2e/src/ui/webElements/chat.ts
  apps/chat-e2e/src/ui/webElements/entitySelector.ts
  apps/chat-e2e/src/ui/webElements/groupEntity.ts
  apps/chat/src/components/Chat/AddonsDialog.tsx
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatSettings.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
Labels: bug

#1829 feat(chat): [REVERT] replace "show more" by "show previous" for stages and show last 3 stages by default (Issue #1820)
  apps/chat-e2e/src/assertions/chatMessagesAssertion.ts
  apps/chat-e2e/src/tests/conversationWithStage.test.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/webElements/chatMessages.ts
  apps/chat/src/components/Chat/MessageStages.tsx
Labels: enhancement

#1836 fix(chat): fix folders selection if search term isn't empty (Issue #1837)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
Labels: bug

#1843 fix(chat): fix folders selection if search term isn't empty (Issue #1837)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
Labels: bug, PATCH

#1841 fix(chat): fix publication files download icon, hide 'go to a review' button if request contains only files, add file section to publication request if there no files to publish (Issues #1839, #1745)
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
Labels: bug

#1848 fix(chat): add filename truncation in publication approve modal (Issue #1839)
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
Labels: bug

#1845 fix(chat): fix infinity loader when try to use search on not allowed folder, fix items to review counter (Issues #1667, #1842)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/pages/api/publication/[entitytype]/[...slug].ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/ui/ui.reducers.ts
Labels: bug

#1850 fix(chat): fix infinite scroll in publish resources panel (Issue #1729)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug

#1862 fix(chat): fix import/export for Replay-conversations (Issue #1451)
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug

#1859 fix(chat): disable chatbar menu and conversation settings (Issue #1835, #1368)
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/SidebarMenu.tsx
Labels: bug
