Repository epam/ai-dial-chat, pull requests merged in 2024-08, with the labels that each got.

#1863 fix(chat): fix folders order and no attachments label in publish modal (Issue #1844, #1856)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
Labels: bug

#1840 fix(chat): add error messages for failed publish requests (Issue #1481)
  apps/chat/src/pages/api/publication/approve.ts
  apps/chat/src/pages/api/publication/create.ts
  apps/chat/src/pages/api/publication/rulesList.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/server/api.ts
  apps/chat/src/utils/server/server.ts
Labels: bug, _priority_2

#1855 fix(chat): fix publish target path constructing (Issue #1853)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug

#1873 feat(chat): redesign toast-notifications (Issue #1865)
  apps/chat/public/images/icons/loader.svg
  apps/chat/src/components/Toasts/Toasts.tsx
  apps/chat/src/pages/_app.tsx
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/types/toasts.ts
  apps/chat/tailwind.config.js
Labels: enhancement

#1838 fix(chat): show error when response generation was stopped after part of response was provided for Application, Assistant or Model with addon (Issue #1834)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/types/models.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
Labels: bug

#1866 fix: fixed resizing and toggling of sidebars for tablet and mobile views (Issue #1727, #1778, #1267)
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/utils/app/data/data-service.ts
  apps/chat/src/utils/app/mobile.ts
  apps/chat/src/utils/app/sidebar.ts
  package-lock.json
Labels: bug, enhancement

#1857 fix(chat): fix prompt folders uploading and right side panel approve dots color (Issue #1667)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chat/Publish/ReviewDot.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug

#1881 fix(chat): fix horizontal scroll during renaming (Issue #1846)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug, _priority_1

#1888 fix(chat): fix selecting convs & prompts in search mode (Issue #1874)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatApi/arithmeticRequest.test.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  package-lock.json
  package.json
Labels: bug, _priority_1, PATCH

#1890 feat(chat): redesign error messages (Issue #1889)
  apps/chat-e2e/src/tests/errorUploadFromDevice.test.ts
  apps/chat-e2e/src/ui/webElements/attachFilesModal.ts
  apps/chat-e2e/src/ui/webElements/uploadFromDeviceModal.ts
  apps/chat/src/components/Common/ErrorMessage.tsx
  apps/chat/src/components/Toasts/Toasts.tsx
Labels: bug

#1891 fix(chat): fix sending of empty attachments (Issue #1717)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/utils/server/chat.ts
Labels: bug, _priority_1

#1896 fix(chat): fix settings field widths (Issue #1893)
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/components/Settings/ThemeSelect.tsx
Labels: bug

#1899 fix: update in THEME-CUSTOMIZATION.md
  docs/THEME-CUSTOMIZATION.md
Labels: documentation

#1897 fix(chat): don't send empty custom content (Issue #1717)
  apps/chat/src/utils/server/chat.ts
Labels: bug

#1900 fix(chat): fix importing prompts with duplicates & new ones (Issue #1892)
  apps/chat/src/store/import-export/importExport.epics.ts
Labels: bug, _priority_1

#1901 fix(chat): fix `back to publication` for unpublished requests (Issue #1770, #1902)
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Header/CreateNewChatMobile.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/types/common.ts
Labels: bug

#1908 chore(chat): use `HTTPMethod` enum instead of strings
  apps/chat/src/pages/api/[entitytype]/[...slug].ts
  apps/chat/src/pages/api/publication/approve.ts
  apps/chat/src/pages/api/publication/create.ts
  apps/chat/src/pages/api/publication/delete.ts
  apps/chat/src/pages/api/publication/details.ts
  apps/chat/src/pages/api/publication/listing.ts
  apps/chat/src/pages/api/publication/reject.ts
  apps/chat/src/pages/api/publication/resourceListing.ts
  apps/chat/src/pages/api/publication/rulesList.ts
  apps/chat/src/pages/api/rate.ts
  apps/chat/src/pages/api/report-issue.ts
  apps/chat/src/pages/api/request-api-key.ts
  apps/chat/src/pages/api/share/accept.ts
  apps/chat/src/pages/api/share/create.ts
  apps/chat/src/pages/api/share/details.ts
  apps/chat/src/pages/api/share/discard.ts
  apps/chat/src/pages/api/share/listing.ts
  apps/chat/src/pages/api/share/revoke.ts
  apps/chat/src/pages/api/themes/image/[name].ts
  apps/chat/src/pages/api/themes/listing.ts
  apps/chat/src/pages/api/themes/styles.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/service/service.epics.ts
  apps/chat/src/types/http.ts
  apps/chat/src/utils/app/data/bucket-service.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/data/publication-service.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/server/api.ts
  apps/chat/src/utils/server/index.ts
Labels: technical debt

#1909 fix(chat): fix folder selection in unpublish request modal (Issue #1867)
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug, _priority_1

#1912 fix: highlight resize trigger while resizing in tablet mode (Issue #1911)
  apps/chat/src/components/Sidebar/Sidebar.tsx
Labels: bug

#1907 fix: fixed select empty folders in select mode (Issue #1864)
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/utils/app/folders.ts
Labels: bug

#1919 fix(chat): fix first falsy request on creating conversation with postfix (Issue #1905)
  apps/chat/src/store/import-export/importExport.epics.ts
Labels: bug

#1922 feat: changed default sidebar width for the mobile view (Issue #1914)
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/constants/default-ui-settings.ts
  apps/chat/src/utils/app/mobile.ts
Labels: enhancement

#1930 fix: "Chat Settings" button is not disabled during model response in "Compare" mode (Issue #1923)
  apps/chat/src/components/Chat/ChatHeader.tsx
Labels: bug

#1934 fix(chat): fix importing duplicate chats & prompts (Issue #1905)
  apps/chat/src/store/import-export/importExport.epics.ts
Labels: bug

#1935 fix(chat): fix overflowing long message in error toast (Issue #1915)
  apps/chat/src/utils/server/server.ts
Labels: bug, _priority_1

#1851 feat(chat): custom applications (Issue #1686)
  .gitignore
  apps/chat/.env.development
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/ModelsDialog.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/EmptyRequiredInputMessage.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/components/Settings/SettingDialog.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/pages/api/ops/[...slug].ts
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/application/application.selectors.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/index.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/styles/globals.css
  apps/chat/src/types/applications.ts
  apps/chat/src/types/common.ts
  apps/chat/src/types/models.ts
  apps/chat/src/types/share.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/application-service.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/app/mappers.ts
  apps/chat/src/utils/server/api.ts
  apps/chat/src/utils/server/index.ts
  libs/shared/src/types/features.ts
Labels: enhancement

#1933 fix(chat): "Chatbar" panel closed after deleting conversation(s) on Mobile and Tablet view (Issue #1699)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
Labels: bug

#1928 fix(chat): Fixed an error that appeared when expanding the prompt folder in the "Approve Required" (Issue #1913)
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug, _priority_1

#1951 fix(chat): fix passing feature "allowResume" (Issue #1834)
  apps/chat/src/types/models.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
Labels: bug

#1949 chore(chat): fix localization area for header components
  apps/chat/src/components/Header/CreateNewChatMobile.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Header/User/ProfileButton.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
Labels: technical debt

#1953 fix: Duplicated attachment import fails if the replace option is chosen. (Issue #1952)
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/utils/app/data/file-service.ts
Labels: bug, _priority_1

#1937 fix(chat): fix loaders for prompt publishing change path dialog (Issue #1667)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Files/SelectFolderModal.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug

#1968 fix(chat): fix prompt applying for admin (Issue #1967)
  apps/chat/src/components/Chat/ChatInput/PromptList.tsx
  apps/chat/src/store/publication/publication.selectors.ts
Labels: bug

#1939 fix(chat): fix deleting empty folders (Issue #1698)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug, _priority_1

#1910 fix(chat): hide publication review dot if publication has non-existent resource (Issue #1847)
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/publication/publication.selectors.ts
Labels: bug

#1972 feat(chat): add opportunity to configure the role field name (Issue #1971)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/index.d.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: enhancement, _priority_1

#1973 feat(chat): add opportunity to configure the roles field name instead of `dial_roles` and fix prompt applying for admin (Issue #1971, #1967)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/index.d.ts
  apps/chat/src/components/Chat/ChatInput/PromptList.tsx
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: enhancement, PATCH

#1961 feat(chat): allow modal windows to be closed only on 'x' or cancel (Issue #1918)
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat/src/components/Chat/AddonsDialog.tsx
  apps/chat/src/components/Chat/ModelsDialog.tsx
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chatbar/ExportModal.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolder.tsx
  apps/chat/src/components/Files/AttachLinkDialog.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Settings/SettingDialog.tsx
Labels: enhancement

#1980 fix(chat): not reset selection for publication when view prompt (Issue #1978)
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug, _priority_1

#1975 fix(chat): fix collapsing folders on import (Issue #1958)
  apps/chat/src/store/import-export/importExport.epics.ts
Labels: bug

#1981 fix(chat): fix expanding folders logic for "go to review" (Issue #1979)
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
Labels: bug, _priority_1

#1983 fix(chat): add roles into session and add possibility to access roles for any path (#1971)
  apps/chat/README.md
  apps/chat/index.d.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug

#1989 fix(chat): add possibility to access roles for any path, prompt publishing fixes (Issue #1971, #1978, #1979)
  apps/chat/README.md
  apps/chat/index.d.ts
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug, PATCH

#1995 fix(chat): fix token reading (Issue #1971)
  apps/chat/index.d.ts
  apps/chat/src/pages/api/publication/listing.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: PATCH

#1994 fix(chat): fix token reading (Issue #1971)
  apps/chat/index.d.ts
  apps/chat/src/pages/api/publication/listing.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug

#1997 fix(chat): fix collapsing nested folders on import (Issue #1958)
  apps/chat/src/store/import-export/importExport.epics.ts
Labels: bug

#1965 feat(chat): change custom application dialog, fix features (Issue #1938, #1945)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/types/applications.ts
  apps/chat/src/utils/app/application.ts
Labels: enhancement

#2002 fix(chat): fix no data view in files manager (Issue #1977)
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug

#1999 chore(chat): implement application storage and refactore application service (Issue #1955)
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/types/applications.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/application-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/data/storages/api/application-api-storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
Labels: technical debt

#1990 feat(chat): add a 'Shared with me' section to the file manager modal (Issues #1283, #1982, #1987)
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Files/Download.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/file.ts
Labels: enhancement

#1970 fix(chat): Error messages appear for Admin are impossible to read (Issue #1944, #1959)
  apps/chat/src/components/Toasts/Toasts.tsx
Labels: bug
