Repository epam/ai-dial-chat, pull requests merged in 2024-09, with the labels that each got.

#2009 fix(chat): fix "invalid JWT" error (Issue #2003)
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug, _priority_1

#2017 fix(chat): fix "invalid JWT" error (Issue #2003)
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug, PATCH

#2020 fix(chat): add messages for external files sharing errors
  apps/chat/src/constants/errors.ts
  apps/chat/src/pages/api/share/create.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
Labels: bug, _priority_2

#2029 fix(chat): reduce session token size (Issue #2028)
  apps/chat/index.d.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug, PATCH

#1957 feat(chat): add versioning for chat and prompt publications, fix freezes on admin UI and publish to path when unpublish entity from folders (Issues #321, #1966, #1991)
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/core/dialSharedWithMeFixtures.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/duplicateSharedConversations.test.ts
  apps/chat-e2e/src/tests/scrolling.test.ts
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/webElements/conversationToCompare.ts
  apps/chat-e2e/src/ui/webElements/modelSelector.ts
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ChatInput/PromptList.tsx
  apps/chat/src/components/Chat/IconNonModelWithTooltip.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/VersionSelector.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderHeader.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Common/ShareIcon.tsx
  apps/chat/src/components/Files/FileItemContextMenu.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/constants/public.ts
  apps/chat/src/constants/versions.ts
  apps/chat/src/hooks/usePromptSelection.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/types/common.ts
  apps/chat/src/types/publication.ts
  apps/chat/src/types/search.ts
  apps/chat/src/types/share.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/data/publication-service.ts
  apps/chat/src/utils/app/mappers.ts
  apps/chat/src/utils/app/publications.ts
  apps/chat/src/utils/app/search.ts
  apps/chat/src/utils/server/api.ts
Labels: bug, enhancement, design

#2033 feat(chat): add option to unpublish app, add apps filter for publish request modal, hide caret icon if publication resource types don't contain prompt or conversation (Issues #1940, #2006, #2031)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.selectors.ts
Labels: bug, enhancement

#2023 fix(chat): Features and maxInputAttachments validations
  apps/chat/src/components/Common/ApplicationDialog.tsx
Labels: bug

#2051 fix(chat): Application attachments (Issues #2015, #2018, #2019, #2024)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
Labels: bug

#2069 fix(chat): fix application long name size, description line break (Issues #2049, #2052, #2053)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
Labels: bug

#2081 fix(chat): use `model.reference` instead of `model.id` everywhere in `conversation.model.id` (Issue #2080)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/overlay/overlay.epics.ts
Labels: bug, _priority_1

#2010 fix(chat): Fixed delete 'shared with me' attachments (Issue #2005)
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
Labels: bug

#2068 fix(chat): fix error message on application delete (Issue #2021)
  apps/chat/src/components/Chat/ModelList.tsx
Labels: bug

#2091 fix(chat): use `model.reference` instead of `model.id` everywhere in `conversation.model.id` (Error 412) (Issue #2080)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/overlay/overlay.epics.ts
Labels: bug, _priority_1, PATCH

#2090 fix(chat): fix error message for publish/share external files (Issue #1984)
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/utils/app/file.ts
Labels: bug, _priority_2

#2094 chore(chat): update sidebar icons
  apps/chat/public/images/icons/move-left.svg
  apps/chat/public/images/icons/move-right.svg
  apps/chat/src/components/Header/Header.tsx
Labels: enhancement

#2078 fix(chat): fix application name postfix
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug

#2099 fix(chat): fix error message typo (Issue #1984)
  apps/chat/src/constants/errors.ts
Labels: bug

#2103 chore(chat): enable PR checks for marketplace target branch
  .github/workflows/pr.yml
Labels: technical debt

#2109 fix(chat): fix fields and add trim before save (Issue #2107)
  apps/chat/src/components/Common/ApplicationDialog.tsx
Labels: bug

#2093 fix(chat): fix clip icon appearance (Issue #2063)
  apps/chat/src/components/Common/ApplicationDialog.tsx
Labels: bug

#2077 feat(chat): marketplace application view (Issue #2037)
  .ort.yml
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Common/FullScreenImages.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationContent.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/ApplicationTag.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/Marketplace/Rating/RatingHandler.tsx
  apps/chat/src/components/Marketplace/Rating/RatingProgressBar.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/hooks/useMobileSwipe.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/conversation.ts
Labels: enhancement

#2120 feat(chat): implement Client Data Service: save/read/update installed deployments into ClientData (Issue #2034)
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/constants/client-data.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/data/client-data-service.ts
  apps/chat/src/utils/app/data/data-service.ts
Labels: enhancement

#2122 feat(chat): add typing for installed deployments (Issue #2034)
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/types/models.ts
  apps/chat/src/utils/app/data/client-data-service.ts
Labels: enhancement

#2121 fix(chat): fix application edit (Issue #2101)
  apps/chat/src/store/models/models.reducers.ts
Labels: bug

#2127 feat(chat): replace models dialog with my applications page (Issue #2112)
  apps/chat-e2e/src/tests/abortedReplay.test.ts
  apps/chat-e2e/src/tests/chatExportImportWithAttachment.test.ts
  apps/chat-e2e/src/tests/chatHeaderSettings.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/conversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/conversationWithAttachmentInResponse.test.ts
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat-e2e/src/tests/editConversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/entityIcon.test.ts
  apps/chat-e2e/src/tests/modelSettings.test.ts
  apps/chat-e2e/src/tests/parametrizedReplay.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chat/ModelsDialog.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Common/ShareIcon.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/store/index.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/search.ts
Labels: enhancement

#2131 chore(chat): Refactor IconUrl without api prefix (Issue #2060)
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
Labels: technical debt

#2128 fix(chat): fix issue with folders creation inside change path dialog (Issue #2114)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderFooter.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/types/common.ts
Labels: bug, _priority_1

#2151 feat(chat): implement configurable background for model icons (Issue #2144)
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/tailwind.config.js
Labels: enhancement

#2156 fix(chat): revert addon icon rendering (Issue #2144)
  apps/chat/src/components/Chatbar/ModelIcon.tsx
Labels: enhancement

#2152 feat(chat): update icon sizes (Issue #2098)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Playback/PlaybackIcon.tsx
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Chat/ReplayAsIsIcon.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Chatbar/ConversationsRenderer.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Files/SelectFolderModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Promptbar/components/Prompts.tsx
  apps/chat/src/components/Search/Search.tsx
  apps/chat/src/types/common.ts
Labels: enhancement

#2062 fix(chat): add application icon publishing (Issues #1941)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/types/models.ts
Labels: bug

#2168 feat(chat): add DEFAULT_ASSISTANT_SUB_MODEL env variable (Issue #2166)
  apps/chat/src/constants/default-ui-settings.ts
Labels: enhancement

#2189 fix(chat): fix custom application version validation, add hint to description (Issue #2130, #2073)
  apps/chat/src/components/Common/ApplicationDialog.tsx
Labels: bug

#2202 fix(chat): remove discard requests for own files (Issue #2193)
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug, _priority_1

#2205 feat(chat): add opportunity to set message template parameters for parametrized Replay (Issue #2162)
  apps/chat/.env.development
  apps/chat/src/components/Buttons/TabButton.tsx
  apps/chat/src/components/Chat/ChatInput/PromptVariablesDialog.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/ChatMessageTemplatesModal.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateInput.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateRenderer.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateRow.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Chat/ModelsDialog.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/utils/app/prompts.ts
  libs/shared/src/types/features.ts
  package-lock.json
Labels: enhancement, _priority_1

#2217 fix(chat): fix template input jumping (Issue #2162)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/TemplateInput.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: bug, _priority_1

#2231 feat(chat): support Marketplace feature flag (Issue #2223)
  apps/chat/.env.development
  apps/chat/src/components/Chat/ConversationSettingsModels.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/pages/marketplace/index.tsx
  libs/shared/src/types/features.ts
Labels: enhancement, _priority_1

#2236 fix(chat): exclude publication info while creating chat duplicate (Issue #2200)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1

#2238 fix(chat): update recent list on model use, reset filters on page load (Issue #2216, #2219)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/pages/marketplace/index.tsx
  apps/chat/src/store/marketplace/marketplace.reducers.ts
Labels: bug, _priority_1, _priority_2

#2211 fix(chat): custom app completion URL validation, resolve console errors , add hint for Attachment types (Issue #2206)
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
Labels: bug

#2239 fix(chat): add attachment validation on blur event (Issue #2227)
  apps/chat/src/components/Common/MultipleComboBox.tsx
Labels: bug

#2237 fix(chat): add tooltip to edit button (Issue #2225)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
Labels: bug
