Repository epam/ai-dial-chat, pull requests merged in 2024-05, with the labels that each got.

#1358 fix(chat): fix playback attachments displaying (Issue #1357)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/Playback/PlaybackControls.tsx
Labels: bug

#1361 feat(chat): add Okta auth (Issue #1360)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/src/utils/auth/auth-providers.ts
Labels: enhancement

#1363 feat(chat): support attachment of folders (Issue #967)
  apps/chat/src/components/Chat/ChatInput/ChatInputAttachments.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputFolderAttachment.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/constants/folders.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/types/models.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
  package-lock.json
Labels: enhancement

#1371 feat(chat): fix uploading files (Issue #967)
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug

#1375 feat(chat): fix folder attachments (Issue #967)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug

#1377 feat(chat): fix folder attachments (Issue #967, #1376)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/utils/app/file.ts
Labels: bug

#1379 fix(chat): fix links sharing and playback with folders (Issue #1372, #967)
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Chat/Playback/PlaybackAttachments.tsx
  apps/chat/src/components/Chat/__tests__/PlaybackAttachments.test.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug

#1387 fix(chat): adjust buttons hover color on prompt preview modal (Issue #1327)
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
Labels: bug

#1395 fix(chat): fix import of conversations with plotly-data (Issue #1394)
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug

#1390 fix(chat): fix links and plotly sharing (Issue #1372)
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Chat/__tests__/PlaybackAttachments.test.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/import-export.ts
  package-lock.json
  package.json
Labels: bug, PATCH

#1393 fix(chat): change prompt button colors (Issue #1249)
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
Labels: bug

#1396 fix(chat): change folder hover color (Issue #1338)
  apps/chat/src/components/Common/SelectFolder/SelectFolderFooter.tsx
Labels: bug

#1385 fix(chat): align version selector for models with long description (Issue #1346)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
Labels: bug

#1389 feat(chat): auto-select just uploaded files in attach files window (Issue #1325)
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: enhancement

#1397 fix(chat): reset new folder after renaming (Issue #1340)
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#1384 fix(chat): Change 'Continue' button white font on light theme in import duplicates dialog (Issue #1235)
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
Labels: bug

#1399 fix(chat): fix modal scrolling (Issue #1194)
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
Labels: bug

#1383 fix(chat): unify the modal windows paddings (Issue #1191)
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug

#1402 fix(chat): update nested folder ids when parent folder is renamed (Issue #1339)
  apps/chat/src/store/files/files.reducers.ts
Labels: bug

#1392 fix(chat): clean error message when select folder closed (Issue #1337)
  apps/chat/src/components/Files/SelectFolderModal.tsx
Labels: bug

#1409 fix(chat): unify the modal windows paddings (Issue #1191)
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Settings/SettingDialog.tsx
Labels: bug

#1401 fix(chat): fix height for the duplicated import modal and buttons text alignment (Issues #1230, #1231)
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
Labels: bug

#1408 fix(chat): open chat or prompt bars on accepted sharing (Issue #1296)
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
Labels: bug

#1415 fix(chat): name duplicated attached file from empty prefix (Issue #1234)
  apps/chat/src/utils/app/zip-import-export.ts
Labels: bug

#1411 fix(chat): open chat/prompt from root shared folder (Issue #1202, #1250)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug

#1412 fix(chat): change button color depending on mode (Issue #1284)
  apps/chat/src/styles/globals.css
Labels: bug

#1416 fix(chat): change tooltip showing place (Issue #109)
  apps/chat/src/components/Chatbar/ModelIcon.tsx
Labels: bug

#1418 fix(chat): change tooltip showing place (Issue #109)
  apps/chat/src/components/Chat/Addons.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
Labels: bug

#1400 feat(visualizer, chat): add redux logic for the custom visualizer connector( Issue #1270)
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/VisualalizerRenderer/VisualizerRenderer.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  libs/chat-visualizer-connector/README.md
  libs/chat-visualizer-connector/src/index.ts
  libs/chat-visualizer-connector/src/lib/ChatVisualizerConnector.ts
  libs/shared/src/types/visualizer-connector.ts
Labels: enhancement

#1436 fix(chat): fix context menu displaying for Replay and Playback conversations (Issue #1435)
  .ort.yml
  apps/chat/src/components/Chatbar/Conversation.tsx
Labels: bug, _priority_1

#1437 chore(chat): update codeowners
  .github/CODEOWNERS
Labels: technical debt

#1432 feat(chat): add possibility to set selected conversation which will be used in Overlay (Issue#1403)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatExternalControls.tsx
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/types/publication.ts
  apps/chat/src/utils/app/folders.ts
  libs/overlay/README.md
  libs/shared/src/types/overlay.ts
Labels: enhancement

#1426 feat(chat): use original folder path during importing attaches (Issue #1420, #1239)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatExportImportWithAttachment.test.ts
  apps/chat/src/store/import-export/importExport.epics.ts
Labels: enhancement

#1462 fix(chat): change prompt button colors (Issue #1249)
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
Labels: bug

#1461 feat(chat): add tooltips for files and folders (Issue #1227)
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#1472 fix(chat): center the 'no data' and 'no result found' and add same logic to 'select folders' (Issue #1333)
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug
