Repository epam/ai-dial-chat, pull requests merged in 2024-04, with the labels that each got.

#1165 feat(chat): implement isolated model view page (Issue #1154)
  apps/chat/next.config.js
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/pages/_document.tsx
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/utils/app/data/bucket-service.ts
  apps/chat/src/utils/app/data/share-service.ts
  libs/shared/src/types/features.ts
Labels: enhancement

#1173 fix(chat): fix message and model view in isolated view (Issue #1154)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ModelDescription.tsx
Labels: bug

#1177 fix(chat): suppress console error (Issue #1154)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug

#1180 fix(chat): check assistant model id only for "assistant" type (Issue #1179)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#1184 fix(chat): check assistant model id only for "assistant" type (Issue #1179)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#1185 fix(chat): fix model description for isolated view (Issue #1154, #1181)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ModelDescription.tsx
Labels: bug

#1171 fix(chat): hide share icon when mouse hover on the file (Issue #1169)
  apps/chat/src/components/Common/ShareIcon.tsx
  apps/chat/src/components/Files/FileItem.tsx
Labels: bug

#1174 fix(chat): fix 'duplicate the conversation to be able to edit' button (Issue #1166)
  apps/chat/src/components/Chat/ChatExternalControls.tsx
Labels: bug

#1189 fix(chat): replace 'conversation not found' screen while deleting all conversations with loader (Issue #1187)
  apps/chat/src/store/conversations/conversations.reducers.ts
Labels: bug

#1155 fix(chat): fix nested folders deletion (Issue #1151)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug

#1197 fix(chat): update error text about tokens (Issue #1196)
  apps/chat/src/utils/app/modals.ts
Labels: bug

#1201 fix(chat): fix token limit text wrapping (Issue #1196)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
Labels: bug

#1199 fix(chat): update error text about tokens (Issue #1196)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/utils/app/modals.ts
Labels: bug, PATCH

#1198 fix(chat): fix the duplication of own items (Issue #1137)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug

#1204 fix(chat): replace TAB by space (Issue #1203)
  apps/chat/src/utils/app/file.ts
Labels: bug

#1178 fix(chat): fix selected shared chat folder structure (Issue #1172)
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
Labels: bug

#1205 fix(chat): replace TAB by space (Issue #1203)
  apps/chat/src/utils/app/file.ts
Labels: bug, PATCH

#1208 fix(chat): fix blackout for overlay (Issue #1207)
  apps/chat/src/store/ui/ui.reducers.ts
Labels: bug

#1213 fix(chat): disallow TAB and ASCII control symbols (Issue #1212)
  apps/chat/src/utils/app/file.ts
Labels: bug

#1214 fix(chat): disallow TAB and ASCII control symbols (Issue #1212)
  apps/chat/src/utils/app/file.ts
Labels: bug, PATCH

#1217 feat(chat): combined patch into 0.8 (Issue #1154, #1203, #1212)
  apps/chat/next.config.js
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ModelDescription.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/pages/_document.tsx
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/utils/app/data/bucket-service.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/file.ts
  libs/shared/src/types/features.ts
Labels: bug, enhancement, PATCH

#1225 fix(chat): fix prompt sharing (Issue #1172)
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
Labels: bug

#1218 fix(chat): fix file to folder upload (Issue #1211)
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/app/share.ts
Labels: bug

#1219 fix(chat): fix scroll down when expand image (Issue #1168)
  apps/chat-e2e/src/ui/webElements/dropdownMenu.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
Labels: bug

#1240 fix(chat): fix auto-scroll for message editing for desktop (Issue 1168)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
Labels: bug

#1242 fix(chat): fix duplicated disabled folder with a dot at the end after import of chat/prompt(Issue #1236)
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug

#1246 fix(chat): fix menu aligment (Issue #1245)
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Settings/ThemeSelect.tsx
Labels: bug

#1247 fix(chat): fix menu aligment (Issue #1245)
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Settings/ThemeSelect.tsx
Labels: bug, PATCH

#1210 feat(chat-e2e): added tests for isolated view feature
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/testData/expectedMessages.ts
  apps/chat-e2e/src/tests/chatExportImport.test.ts
  apps/chat-e2e/src/tests/isolatedView.test.ts
  apps/chat-e2e/src/tests/promptExportImport.test.ts
  apps/chat-e2e/src/tests/sharedWithMe.test.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/webElements/chat.ts
  apps/chat-e2e/src/ui/webElements/chatBar.ts
  apps/chat-e2e/src/ui/webElements/chatMessages.ts
  apps/chat-e2e/src/ui/webElements/moreInfo.ts
  apps/chat-e2e/src/ui/webElements/promptBar.ts
  apps/chat-e2e/src/ui/webElements/replayAsIs.ts
  apps/chat-e2e/src/ui/webElements/sideBar.ts
  apps/chat-e2e/src/utils/modelsUtil.ts
  apps/chat/src/components/Chat/ModelDescription.tsx
  apps/chat/src/components/Chat/ReplayAsIsDescription.tsx
Labels: e2e

#1258 fix(chat): fix edit mode and messages view for mobile (Issues #1255, #1256)
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/Publish/FilterTypeSelect.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
  apps/chat/src/components/Common/Select.tsx
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Settings/ThemeSelect.tsx
Labels: bug

#1259 fix(chat): hide Edit and Delete for shared entity (Issue #1257)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
Labels: bug

#1251 fix(chat): remove scroll down button from empty chats (Issue #927)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#1253 fix(chat): collapse long list of the allowed extensions (Issue#1220)
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/utils/app/file.ts
Labels: bug

#1271 fix(chat): create new conversation if no selected (Issue #1265)
  apps/chat/src/store/conversations/conversations.epics.ts
  package-lock.json
Labels: bug, PATCH

#1278 fix(chat): change label for model change confirmation of shared chat (Issue #1053)
  apps/chat/src/components/Chat/ChatSettings.tsx
Labels: bug

#1279 chore(chat): upgrade default api version to `2024-02-01` (Issue #1277)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/src/constants/default-server-settings.ts
Labels: enhancement

#1291 fix(chat): fix share accepting (Issue #1281)
  apps/chat/src/store/share/share.epics.ts
Labels: bug

#1268 fix(chat): fix items aligment and edit attachment functionality (Issues #1263, #1264)
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputAttachments.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputLinkAttachment.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ContextMenu.tsx
  apps/chat/src/components/Common/SidebarMenu.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Settings/ThemeSelect.tsx
Labels: bug

#1293 fix(chat): update import failed error messages (Issue #1223)
  apps/chat/src/components/Settings/Import.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  package-lock.json
Labels: bug

#1222 chore(chat): sync prompts and conversations methods (Issue #792)
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptbarSettings.tsx
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/store/index.ts
  apps/chat/src/store/migration/migration.epics.ts
  apps/chat/src/store/migration/migration.reducers.ts
  apps/chat/src/store/migration/migration.selectors.ts
  apps/chat/src/store/migration/migration.types.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/data/storages/api/prompt-api-storage.ts
  apps/chat/src/utils/app/prompts.ts
Labels: technical debt, _priority_3

#1298 fix(chat): disable attach link button if required input isn't valid (Issue #1275)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Common/ContextMenu.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/components/Files/AttachLinkDialog.tsx
  apps/chat/src/types/menu.ts
Labels: bug

#1300 fix(chat): change text from 'revoke' to 'unshare' for shared by me items (Issue #1288)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug

#1304 fix(chat): fix chat name generating for link attachments (Issues #1273, #1274)
  apps/chat/src/components/Chat/ChatInput/ChatInputFileAttachment.tsx
  apps/chat/src/utils/app/conversation.ts
Labels: bug

#1290 fix(chat): fix attachments upload (Issue #1229)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatApi/arithmeticRequest.test.ts
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/utils/app/file.ts
Labels: bug

#1316 fix(chat): fix link attachment text alignment (Issue #1315)
  apps/chat/src/components/Chat/ChatInput/ChatInputLinkAttachment.tsx
Labels: bug

#1248 fix(chat): fix mobile view issues (Issue #1255, #1256, #1257, #927)
  apps/chat/.env.development
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Chat/Publish/FilterTypeSelect.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
  apps/chat/src/components/Common/Select.tsx
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Settings/ThemeSelect.tsx
Labels: bug, enhancement, PATCH

#1320 chore(chat-e2e): add new databricks models in e2e-test
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatApi/arithmeticRequest.test.ts
Labels: e2e

#1332 feat: add ability to configure font for chat application
  apps/chat/src/components/Markdown/CodeBlock.tsx
  apps/chat/src/components/Settings/ThemeSelect.tsx
  apps/chat/src/pages/_app.tsx
  apps/chat/src/pages/api/themes/styles.ts
  apps/chat/src/types/themes.ts
  apps/chat/tailwind.config.js
  docs/THEME-CUSTOMIZATION.md
Labels: enhancement, _priority_1

#1336 feat(chat): add ability to configure font for chat application (Issue #1332)
  apps/chat/src/components/Markdown/CodeBlock.tsx
  apps/chat/src/components/Settings/ThemeSelect.tsx
  apps/chat/src/pages/_app.tsx
  apps/chat/src/pages/api/themes/styles.ts
  apps/chat/src/types/themes.ts
  apps/chat/tailwind.config.js
  docs/THEME-CUSTOMIZATION.md
Labels: enhancement
