Repository epam/ai-dial-chat, pull requests merged in 2024-11, with the labels that each got.

#2502 feat(chat): add examples for Code Apps (Issue #2499)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppExampleLink.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppExamples.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/constants/code-apps.ts
Labels: enhancement

#2504 fix(chat): fix colors (Issue #2113)
  apps/chat/src/components/Chat/MessageAttachments.tsx
Labels: bug

#2506 fix(chat): allow to remove icon during editing (Issue #2505)
  apps/chat/src/store/application/application.epics.ts
Labels: bug

#2511 fix(chat): fix code app endpoints (Issue #2508)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/constants/applications.ts
Labels: bug

#2507 feat(chat): add full tab mode for code editor (Issue #2500)
  apps/chat/.env.development
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: enhancement

#2445 fix(chat): show version while review items (Issue #2403)
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ChatInput/PromptList.tsx
  apps/chat/src/components/Chat/Publish/PublicVersionSelector.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Chat/Publish/VersionSelector.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/hooks/usePublicVersionGroupIdFromPublicEntity.ts
  apps/chat/src/store/publication/publication.reducers.ts
Labels: bug

#2514 fix(chat): fix displaying of disabled context menu items (Issue #2509)
  apps/chat-e2e/src/tests/sharedWithMeConversations.test.ts
  apps/chat-e2e/src/tests/sharedWithMePromptFolders.test.ts
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppExampleLink.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppExamples.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/components/Common/ContextMenu.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/types/menu.ts
Labels: bug

#2535 fix(chat): fix application logs displaying (Issue #2534)
  apps/chat/src/components/Marketplace/ApplicationLogs.tsx
Labels: bug

#2539 fix(chat): ignore spaces into endpoints (Issue #2537)
  apps/chat/src/components/Common/ApplicationWizard/form.ts
Labels: bug

#2538 fix(chat): fix files selection after upload action (Issue #2523)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppExampleLink.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/store/files/files.reducers.ts
Labels: bug

#2540 fix(chat): fix app log visibility for Admin, disable 'Use application' button (Issue #2526, #2531)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
Labels: bug

#2548 fix(chat): fix long names issues (Issue #2513, #2543)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
Labels: bug

#2549 fix(chat): fix displaying of completion url in review request (Issue #2510)
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
Labels: bug, _priority_1

#2552 fix(chat): add the limit for folder depth (Issue #2522)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/components/Toasts/Toasts.tsx
Labels: bug

#2554 fix(chat): fix code editor full screen tooltip and show tooltip if use app button is disabled (Issues #2550, #2544)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
Labels: bug, enhancement

#2557 fix(chat): fix multipleComboBox field design (Issue #2545)
  apps/chat/src/components/Chat/Publish/TargetAudienceFilterComponent.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
Labels: bug

#2560 fix(chat): fix app log context menu (Issue #2532)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug

#2561 fix(chat): fix stroke appearance (Issue #2113)
  apps/chat/src/components/Chat/MessageAttachments.tsx
  apps/chat/src/components/Chat/MessageStage.tsx
Labels: bug

#2547 fix(chat): disallow external icons publishing with applications (Issue #2427)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/ErrorMessage.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/hooks/usePublicVersionGroupIdFromPublicEntity.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/publications.ts
Labels: bug, _priority_2

#2559 fix(chat): fix displaying endpoints and environmental variable in review request (Issue #2521)
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationPropsSection.tsx
Labels: bug

#2571 chore(chat): bump NextJS from 14.2.12 to 14.2.17
  package-lock.json
  package.json
Labels: technical debt

#2575 fix(chat): fix code editor UI for safari browser (Issue #2569)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/styles/globals.css
Labels: bug

#2583 fix(chat): fix scrolls on Marketplace (Issue #2582)
  apps/chat/src/pages/marketplace/index.tsx
Labels: bug, _priority_1

#2590 fix(chat): fix font in "no found" (Issue #2589)
  apps/chat/src/components/Common/NoResultsFound.tsx
Labels: bug

#2591 fix(chat): update confiramtion message (Issue #2558)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
Labels: bug

#2593 fix(chat): fix font in "no found" (Issue #2589)
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug

#2572 feat(chat): refactor of code editor actions and add code editor files saving on ctrl(cmd) + s (Issues #2573, #2576)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/store/codeEditor/codeEditor.epics.ts
  apps/chat/src/store/codeEditor/codeEditor.reducer.ts
  apps/chat/src/store/codeEditor/codeEditor.selectors.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/index.ts
Labels: enhancement, technical debt

#2609 chore(chat): add `bypass_ort: true`
  .github/workflows/pr.yml
Labels: technical debt

#2600 fix(chat): fix filter text box hint (Issue #2371)
  apps/chat/src/components/Chat/Publish/TargetAudienceFilterComponent.tsx
  apps/chat/src/components/Common/MultipleComboBox.tsx
Labels: bug

#2602 fix(chat): fix code app file delete icon displaying (Issue #2574)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
Labels: bug

#2603 feat(chat): fix app icon publishing warning message, add 'save all' option to code editor and 'save' to code editor file context menu, fix code editor empty files content (Issues #2576, #2515, #2427)
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/components/Common/ContextMenu.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Files/FileItemContextMenu.tsx
  apps/chat/src/store/codeEditor/codeEditor.epics.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/types/menu.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
Labels: bug, enhancement, _priority_2

#2588 feat(chat): Add download to Application logs (Issue #2581)
  apps/chat/src/components/Marketplace/ApplicationLogs.tsx
  apps/chat/src/store/application/application.selectors.ts
  apps/chat/src/styles/globals.css
  apps/chat/src/utils/app/import-export.ts
Labels: enhancement

#2621 chore(chat): revert `bypass_ort: true`
  .github/workflows/pr.yml
  .github/workflows/release.yml
  package-lock.json
Labels: technical debt

#2622 feat(chat): update code app delete icon (Issue #2617)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
Labels: enhancement

#2615 chore(chat): get rid of takeUntil and race conditions when accepting share invitation (Issue #2599)
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/share/share.epics.ts
Labels: technical debt

#2607 fix(chat): add flag for updating new conversation (Issue #2267)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
Labels: bug, _priority_2

#2625 chore(chat): ORT clean up
  .ort.yml
  Dockerfile
  package-lock.json
  package.json
Labels: technical debt

#2631 chore(chat): regenerate `package-lock.json`
  .github/workflows/deploy_dev.yml
  .github/workflows/e2e_tests.yml
  .github/workflows/pr-title-check.yml
  .github/workflows/pr.yml
  .github/workflows/release.yml
  .nvmrc
  apps/chat-e2e/src/tests/chatExportImportWithAttachment.test.ts
  apps/chat-e2e/src/tests/conversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat-e2e/src/tests/sharedWithMeConversations.test.ts
  apps/chat-e2e/tsconfig.json
  apps/chat/src/components/Chat/AddonsDialog.tsx
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/ReplayVariables.tsx
  apps/chat/src/components/Chat/ChatSettings.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Chat/Migration/Migration.tsx
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/components/Chat/Playback/PlaybackControls.tsx
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Chat/Publish/ReviewDot.tsx
  apps/chat/src/components/Chat/Publish/TargetAudienceFilterComponent.tsx
  apps/chat/src/components/Chat/Temperature.tsx
  apps/chat/src/components/Common/FullScreenImages.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
  apps/chat/src/components/Common/ShareIcon.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/Rating/RatingHandler.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/components/Settings/SettingDialog.tsx
  apps/chat/src/components/VisualalizerRenderer/VisualizerRenderer.tsx
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/tsconfig.json
  apps/overlay-sandbox/tsconfig.json
  libs/chat-visualizer-connector/tsconfig.json
  libs/modulify-ui/src/lib/ComponentBuilder.tsx
  libs/modulify-ui/src/lib/Inversify.tsx
  libs/modulify-ui/src/lib/__tests__/ComponentBuilder.test.tsx
  libs/modulify-ui/src/lib/__tests__/Inversify.test.tsx
  libs/modulify-ui/tsconfig.json
  libs/overlay/tsconfig.json
  libs/shared/tsconfig.json
  libs/visualizer-connector/tsconfig.json
  package-lock.json
Labels: technical debt

#2626 fix(chat): fix conversation selection after deleting all conversations (Issue #2056)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/publications.ts
Labels: bug

#2628 fix(chat): update code app delete button (Issue #2617)
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat-e2e/src/ui/selectors/iconSelectors.ts
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Common/Forms/DynamicFormFields.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
Labels: bug

#2627 fix(chat): refactor init requests (Issue #2598)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/ui/webElements/entitySelector.ts
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/store/addons/addons.epics.ts
  apps/chat/src/store/addons/addons.reducers.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/migration/migration.epics.ts
  apps/chat/src/store/migration/migration.reducers.ts
  apps/chat/src/store/migration/migration.selectors.ts
  apps/chat/src/store/migration/migration.types.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
Labels: bug, _priority_1

#2637 fix(chat): update deployed code app edit, show toast (Issue #2479, #2512)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
Labels: bug, enhancement

#2638 fix(chat): fix disappearing of the organization section from "Select application icon" (Issue #2481)
  apps/chat/src/store/settings/settings.epic.ts
Labels: bug, _priority_1

#2644 fix(chat): remove publicationInfo from import-export flow (Issue #2276)
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug, _priority_2

#2643 fix(chat): fix lastActivityDate sorting for public items (Issue #2056)
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug

#2608 fix(chat): add files upload when create an unpublish request for conversation (Issue #2605)
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#2647 feat(chat-e2e): introduce more users in tests
  apps/chat-e2e/README.md
  apps/chat-e2e/config/local.chat.playwright.config.ts
  apps/chat-e2e/src/core/dialAdminFixtures.ts
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/core/dialSharedWithMeFixtures.ts
  apps/chat-e2e/src/tests/desktopAuth.ts
  apps/chat-e2e/src/tests/promptUsage.test.ts
  apps/chat-e2e/src/tests/shareConversationWithContent.test.ts
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat-e2e/src/tests/sharedWithMeConversations.test.ts
  apps/chat-e2e/src/tests/sharedWithMePromptFolders.test.ts
  apps/chat-e2e/src/tests/sharedWithMePrompts.test.ts
  apps/chat-e2e/src/utils/bucketUtil.ts
Labels: e2e

#2650 fix(chat): fix my application version search (Issue #2648)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug, _priority_1

#2649 fix(chat): temporarily hide file unpublish (Issue #2632, #2180)
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
Labels: bug, _priority_2

#2601 fix(chat): don't save empty conversations into storage (Issue #2584, #2566, #2618)
  apps/chat-e2e/config/chat.playwright.config.ts
  apps/chat-e2e/src/core/dialSharedWithMeFixtures.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/chatBarFolderConversation.test.ts
  apps/chat-e2e/src/tests/chatExportImport.test.ts
  apps/chat-e2e/src/tests/chatExportImportWithAttachment.test.ts
  apps/chat-e2e/src/tests/chatSelectionFunctionality.test.ts
  apps/chat-e2e/src/tests/cleanup.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/conversationNameNumeration.test.ts
  apps/chat-e2e/src/tests/conversationWithAttachmentInResponse.test.ts
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat-e2e/src/tests/duplicateSharedConversations.test.ts
  apps/chat-e2e/src/tests/errorUploadFromDevice.test.ts
  apps/chat-e2e/src/tests/manageAttachment.test.ts
  apps/chat-e2e/src/tests/promptUsage.test.ts
  apps/chat-e2e/src/tests/publishConversation.test.ts
  apps/chat-e2e/src/tests/publishFolderWithConversation.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/scrolling.test.ts
  apps/chat-e2e/src/tests/selectUploadFolder.test.ts
  apps/chat-e2e/src/tests/shareConversationWithContent.test.ts
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat-e2e/src/tests/sideBarFilters.test.ts
  apps/chat-e2e/src/tests/sidePanels.test.ts
  apps/chat-e2e/src/tests/uploadFileToFolder.test.ts
  apps/chat-e2e/src/tests/uploadFromDevice.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat-e2e/src/ui/webElements/chatBar.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/baseSideBarConversationTree.ts
  apps/chat-e2e/src/ui/webElements/publicationReviewControl.ts
  apps/chat-e2e/src/ui/webElements/publishingApprovalModal.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chatbar/Conversations.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Header/CreateNewChatMobile.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/constants/storage.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/types/settings.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/data-service.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/app/publications.ts
  apps/chat/src/utils/app/search.ts
Labels: enhancement, _priority_1

#2663 feat(chat): add context menu to chat header (Issue #2046)
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
Labels: enhancement

#2668 fix(chat): wrap with layout per page (Issue #2666)
  apps/chat/src/pages/_app.tsx
  apps/chat/src/pages/index.tsx
  apps/chat/src/pages/marketplace/index.tsx
Labels: bug, _priority_1

#2674 fix(chat): fix custom auth pages initialization (Issue #2666)
  apps/chat/src/pages/_document.tsx
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: bug, _priority_1

#2673 fix(chat): fix custom app edit (Issue #2665)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
Labels: bug, _priority_1

#2679 fix(chat): fix "No data" (Issue #2651)
  apps/chat/src/utils/app/search.ts
Labels: bug

#2680 fix(chat): fix header context menu color (Issue #2046)
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Common/ContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/types/menu.ts
Labels: bug

#2682 fix(chat): create new conversation after unsharing selected (Issue #2681)
  apps/chat/src/store/share/share.epics.ts
Labels: bug

#2687 fix(chat): close app card after "Use model" (Issue #2686)
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug

#2688 feat(chat): disable Name and Version fields for edit when app is in deployed state (Issue #2683)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/utils/app/application.ts
Labels: enhancement

#2694 fix(chat): update API paths to include leading slash
  apps/chat-e2e/src/testData/api/itemApiHelper.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat/src/components/Files/Download.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Layout.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
  apps/chat/src/pages/_app.tsx
  apps/chat/src/pages/api/auth/[...nextauth].ts
  apps/chat/src/store/addons/addons.epics.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/service/service.epics.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/utils/app/attachments.ts
  apps/chat/src/utils/app/data/bucket-service.ts
  apps/chat/src/utils/app/data/data-service.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/data/publication-service.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/data/storages/api/application-api-storage.ts
  apps/chat/src/utils/app/themes.ts
  apps/chat/src/utils/app/zip-import-export.ts
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: technical debt

#2696 fix(chat): fix chat history blinking on conversations change (Issue #2401)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug, _priority_2

#2657 fix(chat): redesign of empty conversation settings (Issue #2045, #2697, #1691)
  README.md
  apps/chat-e2e/src/assertions/agentInfoAssertion.ts
  apps/chat-e2e/src/assertions/index.ts
  apps/chat-e2e/src/assertions/isolatedViewAssertion.ts
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/core/dialOverlayFixtures.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/testData/expectedMessages.ts
  apps/chat-e2e/src/tests/abortedReplay.test.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/chatExportImport.test.ts
  apps/chat-e2e/src/tests/chatExportImportWithAttachment.test.ts
  apps/chat-e2e/src/tests/chatHeader.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/conversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/conversationWithAttachmentInResponse.test.ts
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat-e2e/src/tests/editConversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/entityIcon.test.ts
  apps/chat-e2e/src/tests/isolatedView.test.ts
  apps/chat-e2e/src/tests/modelSettings.test.ts
  apps/chat-e2e/src/tests/overlay/overlay.test.ts
  apps/chat-e2e/src/tests/parametrizedReplay.test.ts
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat-e2e/src/tests/promptExportImport.test.ts
  apps/chat-e2e/src/tests/promptUsage.test.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/shareConversationWithContent.test.ts
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat-e2e/src/ui/pages/dialHomePage.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/webElements/agentInfo.ts
  apps/chat-e2e/src/ui/webElements/chat.ts
  apps/chat-e2e/src/ui/webElements/compare.ts
  apps/chat-e2e/src/ui/webElements/conversationSettings.ts
  apps/chat-e2e/src/ui/webElements/entitySelector.ts
  apps/chat-e2e/src/ui/webElements/entitySettings.ts
  apps/chat-e2e/src/ui/webElements/index.ts
  apps/chat-e2e/src/ui/webElements/marketplace/applications.ts
  apps/chat-e2e/src/ui/webElements/moreInfo.ts
  apps/chat/public/locales/en/chat.json
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  apps/chat/src/components/Chat/ModelDescription.tsx
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Chat/ReplayAsIsDescription.tsx
  apps/chat/src/components/Chat/SystemPrompt.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Promptbar/components/PromptbarSettings.tsx
Labels: enhancement

#2702 fix(chat): fix new conversation loading spinner size for mobile (Issue #2701)
  apps/chat/src/components/Header/CreateNewConversation.tsx
Labels: bug

#2707 fix(chat): fix custom applications versions sorting (Issue #2670)
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/store/models/models.reducers.ts
Labels: bug, _priority_2

#2709 chore(chat): add `NEXT_PUBLIC_QUICK_APPS_HOST` environment variable (Issue #2675)
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/components/Common/MarkdownDescription.tsx
  apps/chat/src/components/Markdown/ChatMDComponent.tsx
Labels: enhancement, technical debt

#2700 fix(chat): fix disable Delete when Code app deployed (Issue #2692)
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizardFooter.tsx
Labels: bug
