Repository epam/ai-dial-chat, pull requests merged in 2024-12, with the labels that each got.

#2714 fix(chat): fix chat blinking when model is unavailable (Issue #2401)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug, _priority_2

#2715 fix(chat): fix deployed code app delete icon tooltip (Issue #2692)
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizardFooter.tsx
Labels: bug

#2718 feat(chat): redirect back to chat on logo click, add topics to application review dialog (Issue #2369, #2329)
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Header/Logo.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
Labels: bug, enhancement, _priority_2

#2713 feat(chat): inform user about Name and Version field restrictions in Deployed state (Issue #2693)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Common/Forms/Field.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
Labels: enhancement

#2640 feat(chat-e2e): unpublish conversation tests
  apps/chat-e2e/src/assertions/baseAssertion.ts
  apps/chat-e2e/src/assertions/conversationToPublishAssertion.ts
  apps/chat-e2e/src/assertions/entityTreeAssertion.ts
  apps/chat-e2e/src/assertions/index.ts
  apps/chat-e2e/src/assertions/publishEntityAssertion.ts
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/testData/api/publicationApiHelper.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/cleanup.ts
  apps/chat-e2e/src/tests/publishConversation.test.ts
  apps/chat-e2e/src/tests/scrolling.test.ts
  apps/chat-e2e/src/tests/unpublishConversation.test.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/selectors/dialogSelectors.ts
  apps/chat-e2e/src/ui/webElements/chatHeader.ts
  apps/chat-e2e/src/ui/webElements/chatMessages.ts
  apps/chat-e2e/src/ui/webElements/entityTree/publishEntitiesTree.ts
  apps/chat-e2e/src/ui/webElements/publishingApprovalModal.ts
  apps/chat-e2e/src/ui/webElements/publishingRequestModal.ts
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: e2e

#2719 chore(chat): fix QUICK_APPS_HOST variable (Issue #2675)
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/constants/default-ui-settings.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/utils/app/data/defaults-service.ts
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: bug

#2731 chore(chat): fix `QUICK_APPS_HOST` variable (Issue #2675)
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/constants/default-ui-settings.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/utils/app/data/defaults-service.ts
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: bug

#2730 fix(chat): save overlay conversations (Issue #2724)
  apps/chat/src/store/overlay/overlay.epics.ts
Labels: bug

#2732 fix(chat): save not local new conversations (Issue #2724, #2584)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
Labels: bug

#2725 fix(chat): create new conversation on logo click (Issue #2369)
  apps/chat/src/components/Header/Logo.tsx
Labels: enhancement, _priority_2

#2733 fix(chat): update "Hello world" example (Issue #2564)
  apps/chat/src/constants/code-apps.ts
Labels: enhancement

#2735 fix(chat): add success action on creating not local conversation (Issue #2724)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/overlay/overlay.epics.ts
Labels: bug, _priority_1

#2729 fix(chat): Fix error if no recent models set (Issue #2653)
  apps/chat/src/store/models/models.epics.ts
Labels: bug, _priority_1

#2738 fix(chat): fix chat completion request for application with special symbols (Issue #2737)
  apps/chat/src/utils/server/index.ts
Labels: bug

#2739 feat(chat): add QUICK_APPS_MODEL env variable (Issue #2736)
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/src/components/Chat/ChatSettings.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/constants/default-ui-settings.ts
  apps/chat/src/constants/quick-apps.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/data/defaults-service.ts
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: enhancement, _priority_1

#2747 feat(chat): add QUICK_APPS_MODEL env variable (Issue #2736)
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/src/components/Chat/ChatSettings.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/constants/default-ui-settings.ts
  apps/chat/src/constants/quick-apps.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/data/defaults-service.ts
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: enhancement, PATCH

#2712 fix(chat): fix disable icons during conversation response generation (Issue #2672)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
Labels: bug

#2751 fix(chat): hide chat settings in isolated view (Issue #2721)
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
Labels: bug, _priority_2

#2749 fix(chat): fix logo click during response generation (Issue #2748)
  apps/chat/src/components/Header/Logo.tsx
Labels: bug

#2752 fix(chat): show versions on submodel list item (Issue #2218)
  apps/chat/src/components/Chat/ConversationSettings.tsx
Labels: bug, _priority_3

#2761 fix(chat): fix code app admin review feautres displaying (Issue #2723)
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialogView.tsx
Labels: bug

#2762 fix(chat): hide regenerate button for disallowed models (Issue #2360)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#2764 fix(chat): open folder on adding subfolder (Issue #2556)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
Labels: bug

#2777 chore(chat): use `ort_version: 42.1.0`
  .github/workflows/pr.yml
  .github/workflows/release.yml
Labels: technical debt

#2767 fix(chat): skip bucket request if performed once (Issue #2642)
  apps/chat/src/store/settings/settings.epic.ts
Labels: bug

#2765 fix(chat): add 'today', 'pinned conversations', 'pinned prompts' and 'recent' sections expansion if create new chat/folder/prompt (Issue #1552)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Publish/PublishAttachment.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Chatbar/Conversations.tsx
  apps/chat/src/components/Chatbar/ConversationsRenderer.tsx
  apps/chat/src/components/Common/CollapsibleSection.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Promptbar/components/PromptbarSettings.tsx
  apps/chat/src/components/Promptbar/components/Prompts.tsx
  apps/chat/src/constants/folders.ts
  apps/chat/src/constants/sections.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug

#2716 fix(chat): Fix setting Overlay conversation, refactoring init selected conversations epic (Issue #2599, #2741)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: technical debt, _priority_2

#2760 feat(chat): adapt the chat settings modal for compare mode (Issue #2740)
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/ui/webElements/agentSettings.ts
  apps/chat-e2e/src/ui/webElements/compare.ts
  apps/chat-e2e/src/ui/webElements/conversationSettingsModal.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatSettings.tsx
  apps/chat/src/components/Chat/ChatSettings/Addons.tsx
  apps/chat/src/components/Chat/ChatSettings/AddonsDialog.tsx
  apps/chat/src/components/Chat/ChatSettings/AssistantSubModelSelector.tsx
  apps/chat/src/components/Chat/ChatSettings/ChatSettingsModal.tsx
  apps/chat/src/components/Chat/ChatSettings/ConversationSettings.tsx
  apps/chat/src/components/Chat/ChatSettings/SystemPrompt.tsx
  apps/chat/src/components/Chat/ChatSettings/Temperature.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/store/ui/ui.reducers.ts
Labels: enhancement

#2770 fix(chat): fix new conversations model selection (Issue #2684)
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Header/CreateNewConversation.tsx
  apps/chat/src/components/Header/Logo.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/types/settings.ts
Labels: bug

#2769 fix(overlay): hide 'configure settings' when features are disabled (Issue #2728)
  apps/chat-e2e/src/tests/shareConversationWithContent.test.ts
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
Labels: bug

#2788 feat(chat): regenerate on empty assistant message (#2783)
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat-e2e/src/ui/webElements/chatMessages.ts
  apps/chat-e2e/src/ui/webElements/sendMessage.ts
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/SendMessageButton.tsx
Labels: enhancement

#2790 feat(chat): redesign header tooltips (Issue #79)
  apps/chat-e2e/src/assertions/conversationInfoTooltipAssertion.ts
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/core/dialSharedWithMeFixtures.ts
  apps/chat-e2e/src/tests/chatHeader.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/isolatedView.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/sharedWithMeConversations.test.ts
  apps/chat-e2e/src/ui/selectors/dialogSelectors.ts
  apps/chat-e2e/src/ui/webElements/chatHeader.ts
  apps/chat-e2e/src/ui/webElements/chatSettingsTooltip.ts
  apps/chat-e2e/src/ui/webElements/index.ts
  apps/chat-e2e/src/ui/webElements/marketplace/marketplaceAgents.ts
  apps/chat-e2e/src/ui/webElements/modelInfoTooltip.ts
  apps/chat-e2e/src/ui/webElements/tooltip.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/ChatHeader/HeaderModelTooltip.tsx
  apps/chat/src/components/Chat/ChatHeader/HeaderSettingsTooltip.tsx
  apps/chat/src/components/Chat/ChatInfoTooltip.tsx
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/utils/app/conversation.ts
Labels: enhancement

#2795 fix(chat): Fix incorrectly working flag when selected conversation loading (Issue #2793)
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/overlay-sandbox/app/cases/overlay/page.tsx
Labels: bug, _priority_1

#2789 feat(chat): introduce feature flags (Issue #2771)
  apps/chat/.env.development
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  libs/shared/src/types/features.ts
Labels: enhancement

#2800 fix(chat): replace "model" by "agent" term (Issue #2797)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#2804 fix(chat): fix toggle folder in code app editor (Issue #2556)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
Labels: bug

#2782 feat(chat): apply endpoints and environment variables with Code App examples (Issue #2536)
  apps/chat-e2e/src/testData/conversationHistory/conversationBuilder.ts
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatSettings/SystemPrompt.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppExampleLink.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/components/Common/Forms/DynamicFormFields.tsx
  apps/chat/src/constants/code-apps.ts
  apps/chat/src/constants/default-server-settings.ts
  apps/chat/src/constants/default-ui-settings.ts
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/utils/app/__tests__/importExports.test.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/data/defaults-service.ts
  apps/chat/src/utils/server/get-common-page-props.ts
  package-lock.json
Labels: enhancement

#2806 fix(chat): disallow "Stop generation" by Enter click (Issue #2808)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
Labels: enhancement

#2809 feat(chat): allow settings in Isolated view (Issue #2807)
  apps/chat-e2e/src/tests/isolatedView.test.ts
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: enhancement

#2796 fix(chat): disable new conversation on click when HideNewConversation is enabled (Issue #2792)
  apps/chat/src/components/Header/Logo.tsx
Labels: bug

#2813 fix(chat): Fix the default recent model IDs that are not saved in local storage in overlay mode (Issue #2794)
  apps/chat/src/store/models/models.reducers.ts
Labels: bug, _priority_1

#2816 feat(chat): hide message templates for Isolated view and change order of header buttons (Issue #2814, #2815)
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: enhancement

#2817 fix(chat): add space after version prefix (Issue #2759)
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
Labels: bug

#2812 feat(chat): use `.dial` extension for export files (Issue #2646)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/testData/import/ai_dial_chat_with_attachments.dial
  apps/chat-e2e/src/ui/pages/basePage.ts
  apps/chat/src/components/Settings/Import.tsx
  apps/chat/src/utils/app/zip-import-export.ts
Labels: enhancement

#2823 fix(chat): hide 'Go to my workspace' link if Marketplace feature is disabled (Issue #2780, #2759)
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
Labels: bug

#2824 fix(chat): hide `clientdata` folder (Issue #2704)
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/core/dialSharedWithMeFixtures.ts
  apps/chat-e2e/src/testData/api/fileApiHelper.ts
  apps/chat-e2e/src/testData/api/itemApiHelper.ts
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat/src/utils/app/data/file-service.ts
Labels: bug

#2848 feat(chat): optimize switch to other route (Issue #2773)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Header/BackToChat.tsx
  apps/chat/src/components/Header/Logo.tsx
Labels: enhancement, technical debt

#2844 fix(chat): add sections expansion if move prompt/conversation to other sections (Issue #1552)
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/ConversationsRenderer.tsx
  apps/chat/src/components/Chatbar/ExportModal.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Common/MoveToFolderMobileModal.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/store/ui/ui.epics.ts
Labels: bug

#2853 fix(chat): fix issues for bash and sh code blocks in markdown (Issue #2854)
  apps/chat/src/components/Markdown/CodeBlock.tsx
  apps/chat/src/utils/app/codeblock.ts
Labels: bug

#2839 feat(chat): Add rename conversation modal (Issue #2743)
  apps/chat-e2e/src/assertions/renameConversationModalAssertion.ts
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/chatSelectionFunctionality.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/conversationNameNumeration.test.ts
  apps/chat-e2e/src/tests/monitoring/renameConversation.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/baseSideBarConversationTree.ts
  apps/chat-e2e/src/ui/webElements/renameConversationModal.ts
  apps/chat/src/components/Chat/ChatSettings/AddonsDialog.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/MainModalManager.jsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog.tsx
  apps/chat/src/components/Chat/RenameConversationModal.tsx
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Chatbar/ExportModal.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizard.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolder.tsx
  apps/chat/src/components/Files/AttachLinkDialog.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Settings/SettingDialog.tsx
  apps/chat/src/constants/modal.ts
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
Labels: enhancement

#2821 fix(chat): add Logs for deployed apps and Unpublish for published apps in context menu (Issue #2791)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Marketplace/ApplicationLogs.tsx
Labels: bug

#2859 fix(chat): add padding to text in cards (Issue #2833)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
Labels: bug

#2858 fix(chat): add more language to file extension mappings for code blocks (Issue #2854)
  apps/chat/src/components/Markdown/CodeBlock.tsx
  apps/chat/src/utils/app/codeblock.ts
Labels: enhancement

#2862 fix(chat): fix slider overload and keyboard arrows navigation (Issue #2825)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
Labels: bug, _priority_1

#2864 fix(chat): fix settings modal opening delay (Issue #2863)
  apps/chat/src/hooks/useTokenizer.ts
Labels: bug

#2830 fix(chat): add confirmation dialog for code editor exit without saving (Issue #2734)
  apps/chat/src/components/Common/ApplicationDialog.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/OptionsDialog.tsx
  apps/chat/src/components/Common/QuickAppDialog.tsx
  apps/chat/src/store/codeEditor/codeEditor.epics.ts
  apps/chat/src/store/codeEditor/codeEditor.reducer.ts
  apps/chat/src/store/codeEditor/codeEditor.selectors.ts
Labels: bug

#2865 fix(chat): show like/dislike/copy buttons only if content message hasn't error message or content isn't empty (Issue #125)
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
Labels: bug

#2869 fix(chat): fix downloading without extension and name of code block (Issue #2867, #2868)
  apps/chat/src/components/Markdown/CodeBlock.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/utils/app/folders.ts
Labels: bug

#2872 fix(chat): speed up settings modal opening (Issue #2863)
  apps/chat/src/hooks/useTokenizer.ts
Labels: bug

#2873 fix(chat): hide copy button if message hasn't content (Issue #125)
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
Labels: bug

#2877 fix(chat): add tooltip for conversation settings icon (Issue #2842)
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
Labels: bug

#2886 fix(chat): fix wrapping of version label (Issue #2883)
  apps/chat/src/components/Chat/Publish/PublicVersionSelector.tsx
Labels: bug

#2885 fix(chat): add padding to text in cards (Issue #2833)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
Labels: bug

#2889 fix(chat): disable autocomplete for rename input (Issue #2888)
  apps/chat/src/components/Chat/RenameConversationModal.tsx
Labels: bug

#2890 fix(chat): disable autocomplete for folder rename input (Issue #2888)
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#2857 fix(chat): fix Simple Rag example (Issue #2750)
  apps/chat/src/constants/code-apps.ts
Labels: bug

#2895 fix(chat): fix displaying like/dislike buttons (Issue #2894)
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/utils/server/chat.ts
Labels: bug

#2896 fix(chat): fix displaying like/dislike buttons into mobile menu (Issue #2894)
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
Labels: bug
