Repository epam/ai-dial-chat, pull requests merged in 2024-06, with the labels that each got.

#1474 fix: fix infinite spinner in overlay after login (Issue #1454)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/store/overlay/overlay.reducers.ts
Labels: bug, _priority_1

#1480 fix(chat): Fix long list outdise (Issue #1446)
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
Labels: bug

#1488 fix: fix Manage attachments impossible to download or delete files, no text about supported types and max size (Issue #1443)
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
Labels: bug, _priority_1

#1489 fix(chat): Publication collapse (Issue #1430)
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/types/publication.ts
Labels: bug

#1490 fix(chat): fix issue with report issue and report api key dialogs (Issue #117)
  .ort.yml
  apps/chat/src/pages/api/report-issue.ts
  apps/chat/src/pages/api/request-api-key.ts
  apps/chat/src/store/index.ts
  apps/chat/src/store/service/service.epics.ts
Labels: bug, PATCH

#1487 feat(chat): support inline-markdown images and links (Issue #1486)
  apps/chat/src/components/Markdown/ChatMDComponent.tsx
Labels: enhancement

#1479 fix(chat): fix attachments mapping for playback when publishing and add prompt panel opening when go to a review (Issues #1469, #1482)
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug

#1491 fix(chat): remove horizontal scroll in prompt preview modal (Issue #1424)
  apps/chat/.env.development
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
Labels: bug

#1492 fix(chat): fix export button color for prompt preview mode and add truncating to publish modal (Issues #1327, #1464)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
Labels: bug

#1485 fix(chat): add uploading the root folder of the selected chat if the selected chat is in the 'Organization' section (Issue #1424)
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug

#1449 feat(chat): implement unpublish dialog (Issue #318)
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/UnpublishModal.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/publication/publication.reducers.ts
Labels: enhancement

#1498 fix(chat): fix publish and preview prompt modal items truncating (Issues #1464, #1466)
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/pages/index.tsx
Labels: bug

#1500 fix(chat): fix folders unpublishing and publication folders uploading (Issues #318, #1482)
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/UnpublishModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/folders.ts
Labels: bug

#1506 fix(chat): add prompt panel opening if click on 'go to a review...' (Issue #1482)
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
Labels: bug

#1476 fix(chat): Publish tooltips (Issue #1447, Issue #1463)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
Labels: bug

#1496 fix(chat): Fix approve section incorrect name after dote (Issue #1425)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug

#1516 fix(chat): Fix long list outdise (Issue #1446)
  apps/chat/src/pages/index.tsx
Labels: bug

#1507 fix(chat): hide unpublish option from change path dialog (Issue #1501)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Publish/PublishAttachment.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Files/SelectFolderModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/constants/folders.ts
Labels: bug

#1519 fix(chat): fix Markdown-inline images encoded as Data URLs (Issue #1518)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/utils/app/attachments.ts
Labels: bug

#1525 fix(chat): fix request api key fields reset (Issue #1524)
  apps/chat/src/components/Chat/RequestApiKeyDialog.tsx
Labels: bug

#1520 fix: fix newly generated attachment not shown in file manager (Issue# 1453)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/files/files.reducers.ts
Labels: bug

#1521 feat(chat): add memorization of collapsed sections (Issue #1495)
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/ConversationsRenderer.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Promptbar/components/Prompts.tsx
  apps/chat/src/constants/folders.ts
  apps/chat/src/hooks/useSectionToggle.ts
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/data/data-service.ts
Labels: enhancement

#1533 fix(chat): add resources removing from organization section in they were unpublished (Issue #1444)
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug

#1536 fix(chat): fix opening two prompt dialogs for unpublish request (Issue #1515)
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
Labels: bug

#1528 fix(chat): reuse isAbsoluteUrl logic (Issue #1518)
  apps/chat/src/pages/api/themes/image.ts
  apps/chat/src/pages/api/themes/styles.ts
  apps/chat/src/utils/app/__tests__/file.test.ts
  apps/chat/src/utils/app/attachments.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/app/file.ts
Labels: technical debt

#1541 fix(chat): fix issue with duplicate and link attachments during unpublishing (Issues #1534, #1529)
  apps/chat/src/components/Chat/Publish/UnpublishModal.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug

#1542 feat(chat-e2e): add Gemini 1.5 Flash model
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatApi/arithmeticRequest.test.ts
Labels: e2e

#1543 fix(chat): remove replay entities from publish request (Issue #1504)
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/utils/server/api.ts
Labels: bug

#1554 fix(chat): remove empty folders from the publish request dialog and hide the publish button for folders containing only 'replay' chats (Issue #1504)
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/hooks/usePublicationResources.ts
Labels: bug

#1546 fix(chat): fix review for duplicate unpublish requests (Issue #1423)
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/store/publication/publication.reducers.ts
Labels: bug

#1545 fix(chat): fix model icons displaying for publication resources (Issue #1470)
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug

#1560 chore: update overlay docs
  libs/overlay/README.md
Labels: documentation

#1572 chore: update docs
  README.md
  apps/chat/README.md
Labels: documentation

#1559 feat(chat): Add proxy support for the next-auth (Issue# 1539)
  Dockerfile
  package-lock.json
  package.json
  patches/next-auth+4.24.5.patch
Labels: enhancement

#1540 fix(chat): add tooltips in publish and unpublish (Issue #1421, #1447, #1450, #1478)
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#1561 fix(chat): add removing of empty folders from organization section when admin approves unpublish request (Issue #1444)
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug

#1575 fix(chat): hide unpublish option if resource is on review (Issue #1569)
  apps/chat/src/components/Chat/Publish/ApproveRequiredSection.tsx
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
Labels: bug

#1577 fix(chat): hide unpublish option for prompts in approve required section (Issue #1569)
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug

#1576 fix(chat): remove empty chats from publish modal (Issue #1558)
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#1581 chore(overlay-sandbox): set beautiful image for overlay-manager
  apps/overlay-sandbox/app/cases/overlay-manager/page.tsx
Labels: enhancement

#1590 fix(chat): fix "Can't resolve 'net' and 'tls'"
  apps/chat/src/constants/errors.ts
  package-lock.json
  package.json
Labels: bug

#1563 fix(chat): unify modal paddings (Issue #1473, #1508)
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/UnpublishModal.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolder.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderFooter.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderHeader.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug

#1571 fix(chat): add scroll down buttons for external entities (Issues #1544, #1510)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatExternalControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/store/publication/publication.selectors.ts
Labels: bug

#1582 fix(chat): fix big space and 3 dots in title (Issue #1494)
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug

#1553 fix(chat): add empty filters cleaning from publication request (Issue #1448)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug

#1598 fix(chat): fix filtering of publication resources (Issue #1597)
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#1607 fix(chat): fix large right padding (Issue #1601)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug

#1604 fix(chat): fix unpublish modal (Issue #1594)
  apps/chat/src/components/Chat/Publish/UnpublishModal.tsx
Labels: bug

#1619 fix(chat): fix publication change path scroll (Issue #1609)
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
Labels: bug

#1624 fix(chat): disallow double quotes in entity names (Issue #1622)
  apps/chat/src/utils/app/file.ts
Labels: bug, PATCH

#1623 fix(chat): disallow double quotes in entity names (Issue #1622)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/chatBarFolderConversation.test.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat-e2e/src/tests/selectUploadFolder.test.ts
  apps/chat-e2e/src/ui/webElements/chat.ts
  apps/chat-e2e/src/ui/webElements/uploadFromDeviceModal.ts
  apps/chat/src/utils/app/file.ts
Labels: bug

#1626 fix(chat): fix icon for publish request modal (Issues #1580, #1599, #1612)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
Labels: bug

#1625 feat(chat): Add a loader when uploading items to a publication and handle an error if there are no valid items to publish in the publication request (Issue #1579)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#1630 fix(chat): add nested folders loading for change path dialog (Issue #1429)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
Labels: bug

#1633 fix(chat): fix publish modal mobile paddings (Issue #1631)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/UnpublishModal.tsx
Labels: bug

#1637 fix(chat): fix delete confirm message (Issue #1636)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug

#1638 fix(chat): fix publication request text (Issue #1483)
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
Labels: bug

#1606 fix(chat): fixed UI empty chat settings broken if resize sidebars to max (Issue #1080)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/sidePanels.test.ts
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/constants/chat.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/types/chat.ts
Labels: bug

#1645 fix(chat): handle no resources
  apps/chat/src/components/Chat/Publish/HandlePublication.tsx
Labels: bug

#1642 fix(chat): fix markdown displaying for dark themes (Issue #1641)
  apps/chat/src/store/ui/ui.epics.ts
Labels: bug

#1644 fix(ovelay): fix error in terminal (Issue#1651)
  apps/chat/src/utils/app/overlay.ts
Labels: bug

#1627 fix(chat): publication mobile change overlap (Issue #1620)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
Labels: bug

#1666 fix(chat): fix unpublish modal autoclose (Issue #1610)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
Labels: bug

#1669 fix(chat): fix cutting conversation name if named from attachment link (Issue #1313)
  apps/chat/src/utils/app/common.ts
Labels: bug

#1659 fix(chat): fix broken chat settings UI for mobile view (Issue #1653)
  apps/chat/src/components/Chat/ChatSettingsEmpty.tsx
  apps/chat/src/components/Chat/ConversationSettings.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
Labels: bug

#1677 fix(chat): fix folder attachments in edit mode (Issue #1665)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/types/files.ts
  apps/chat/src/utils/app/file.ts
Labels: bug

#1680 fix(chat): disallow auto-select uploaded files if can't attach files (Issue #1665)
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug

#1684 fix(chat): hide folder checkboxes in Manage attachments (Issue #1665)
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
Labels: bug, _priority_1

#1679 fix(chat): fix editing folder attachments and cutting entity names to 160 symbols (Issue #1313, #1665)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/types/files.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/file.ts
Labels: bug, PATCH

#1614 feat(chat): add ability to have multiple select for files / prompts / conversations (Issue #1531)
  apps/chat-e2e/src/core/localStorageManager.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/testData/expectedMessages.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/chatBarFolderConversation.test.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat-e2e/src/ui/webElements/chatBar.ts
  apps/chat-e2e/src/ui/webElements/chatMessages.ts
  apps/chat/src/components/Chat/ChatHeader.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Promptbar/components/PromptbarSettings.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/styles/globals.css
Labels: enhancement, _priority_1
