Repository epam/ai-dial-chat, pull requests merged in 2024-01, with the labels that each got.

#451 fix: icon is not changed to default if changed conversation entity to entity with default icon (Issue #450)
  src/components/Chatbar/components/ModelIcon.tsx
Labels: bug

#446 feat: need to group stages if there are a lot of them (Issue #429)
  src/components/Chat/ChatMessage.tsx
  src/components/Chat/MessageStage.tsx
  src/components/Chat/MessageStages.tsx
Labels: enhancement

#453 fix: need to remove max selected files is 0 label (Issue #366)
  src/components/Files/FileManagerModal.tsx
Labels: bug

#455 fix: toggle activation area too large for full width chat setting (Issue #454)
  src/components/Common/ToggleSwitch/ToggleSwitch.tsx
  src/components/Common/ToggleSwitch/ToggleSwitchLabeled.tsx
Labels: bug

#449 feat: implement publishing wizard (Issue #317, #458)
  package-lock.json
  src/components/Chat/NotAllowedModel.tsx
  src/components/Chat/PublishModal.tsx
  src/components/Chat/ShareModal.tsx
  src/components/Chat/UnpublishModal.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/Modal.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Promptbar/components/PromptModal.tsx
Labels: enhancement, design

#459 chore: remove tracing for chat requests (Issue #415)
  src/opentelemetry.ts
Labels: enhancement, _priority_1

#310 chore!: update env variables to avoid naming misunderstanding (Issue #427)
  .env.development
  .github/pr-title-checker-config.json
  README.md
  environment.d.ts
  src/constants/default-settings.ts
  src/pages/api/files/file/[...slug].ts
  src/pages/api/files/listing.ts
  src/pages/api/rate.ts
  src/utils/server/get-entities.ts
  src/utils/server/get-headers.ts
  src/utils/server/index.ts
Labels: enhancement

#463 chore!: update env variables to avoid naming misunderstanding (Issue #427)
  README.md
  src/pages/api/files/bucket.ts
  src/utils/server/get-headers.ts
Labels: bug

#456 chore: redesign dropdown in theme settings (Issue #144)
  src/components/Chat/ShareModal.tsx
  src/components/Common/ConfirmDialog.tsx
  src/components/Common/Modal.tsx
  src/components/Files/FileManagerModal.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Files/SelectFolderModal.tsx
  src/components/Settings/SettingDialog.tsx
  src/components/Settings/ThemeSelect.tsx
  src/pages/_app.tsx
Labels: bug, design

#466 fix: fix out of bounds error message for long filenames (Issue #465)
  src/components/Common/ErrorMessage.tsx
  src/components/Files/FileManagerModal.tsx
Labels: bug

#472 fix: remove redundant hook useOutsideAlerter (Issue #118)
  src/components/Folder/Folder.tsx
  src/hooks/useOutsideAlerter.ts
Labels: technical debt

#473 feat: implement publish/update request wizard for conversations and for prompts (Issue #317)
  package-lock.json
  src/components/Chat/Playback/PlaybackControls.tsx
  src/components/Chat/PublishModal.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/CollapsableSection.tsx
  src/components/Common/EmptyRequiredInputMessage.tsx
  src/components/Folder/Folder.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/store/conversations/conversations.epics.ts
  src/store/conversations/conversations.reducers.ts
  src/store/conversations/conversations.selectors.ts
  src/store/prompts/prompts.epics.ts
  src/store/prompts/prompts.reducers.ts
  src/store/prompts/prompts.selectors.ts
  src/types/share.ts
  src/utils/app/__tests__/folders.test.ts
  src/utils/app/__tests__/importExports.test.ts
  src/utils/app/folders.ts
  src/utils/app/modals.ts
  src/utils/app/search.ts
  src/utils/app/share.ts
Labels: enhancement, design

#487 fix: added bucket error handling for 401 status (issue #425)
  src/pages/index.tsx
  src/store/conversations/conversations.epics.ts
  src/store/files/files.epics.ts
  src/store/settings/settings.epic.ts
  src/store/settings/settings.reducers.ts
Labels: bug

#491 fix: fix gradient for error message (Issue #458)
  src/components/Chat/NotAllowedModel.tsx
Labels: bug

#504 fix: added check for the aviable models before init resent models (issue #488)
  src/constants/errors.ts
  src/store/models/models.epics.ts
  src/store/models/models.reducers.ts
  src/store/settings/settings.epic.ts
Labels: bug

#502 fix: fix gradient over text (Issue #458)
  src/components/Chat/ChatInput/ChatInput.tsx
  src/components/Chat/NotAllowedModel.tsx
  src/components/Chat/Playback/PlaybackControls.tsx
  src/styles/globals.css
Labels: bug, enhancement

#471 fix: fix lint issues (#393)
  src/components/Chat/Chat.tsx
  src/components/Chat/PublishModal.tsx
  src/components/Chat/ReportIssueDialog.tsx
  src/components/Chat/RequestApiKeyDialog.tsx
  src/components/Chat/SystemPrompt.tsx
  src/components/Chat/Temperature.tsx
  src/components/Chatbar/Chatbar.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Chatbar/components/ChatbarSettings.tsx
  src/components/Common/Combobox.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Common/ItemContextMenu.tsx
  src/components/Common/Tooltip.tsx
  src/components/Files/FileItemContextMenu.tsx
  src/components/Folder/Folder.tsx
  src/components/Header/User/ProfileButton.tsx
  src/components/Header/User/UserDesktop.tsx
  src/components/Promptbar/Promptbar.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/components/Promptbar/components/PromptbarSettings.tsx
  src/components/Search/SearchFilterRenderer.tsx
  src/components/Search/SearchFiltersView.tsx
  src/components/Sidebar/BetweenFoldersLine.tsx
  src/components/Sidebar/Sidebar.tsx
  src/pages/_app.tsx
  src/pages/api/chat.ts
  src/pages/api/files/file/[...slug].ts
  src/pages/api/health.ts
  src/pages/index.tsx
  src/store/addons/addons.reducers.ts
  src/store/conversations/conversations.epics.ts
  src/store/index.ts
  src/store/models/models.reducers.ts
  src/types/auth.ts
  src/types/menu.ts
  src/utils/app/__tests__/forms.test.tsx
  src/utils/app/data/data-service.ts
  src/utils/app/data/storages/api-storage.ts
  src/utils/app/data/storages/browser-storage.ts
  src/utils/app/forms.ts
  src/utils/app/import-export.ts
  src/utils/auth/nextauth-client.ts
  src/utils/auth/nextauth.ts
  src/utils/auth/ping-identity.ts
  src/utils/auth/session.ts
  src/utils/data/throttle.ts
  src/utils/server/index.ts
Labels: technical debt

#517 fix: fix request API key form description (Issue #494)
  src/components/Chat/RequestApiKeyDialog.tsx
Labels: bug

#519 fix: fix form submission canceled because the form is not connected warning (Issue #480)
  src/components/Common/Modal.tsx
Labels: bug, _priority_3

#518 fix: add highlight color to the folder if chat is active(issue #482)
  e2e/src/tests/chatBarConversation.test.ts
  src/components/Folder/Folder.tsx
Labels: bug

#520 fix: fix clicking on external links (Issue #494)
  src/components/Chat/RequestApiKeyDialog.tsx
Labels: bug

#521 fix: change chat message border to the correct (secondary) color (issue #477)
  src/components/Chat/ChatMessage.tsx
Labels: bug

#526 fix: fix gradient over text (Issue #458)
  src/styles/globals.css
Labels: bug, enhancement

#527 fix: fix folder highlight color (issue #482)
  src/components/Folder/Folder.tsx
Labels: bug

#531 fix: fix keyboard events handling for the prompts in message input and system prompt (issue #485)
  src/components/Chat/ChatInput/ChatInputMessage.tsx
  src/components/Chat/SystemPrompt.tsx
  src/hooks/usePromptSelection.ts
Labels: bug

#529 fix: fix height of items in select conversation dropdown (Issue #476)
  src/components/Common/Combobox.tsx
Labels: bug

#540 fix: fix background for attached files (Issue #509)
  src/components/Chat/MessageAttachment.tsx
Labels: bug

#543 fix: fix file name truncation if it has spaces (Issue #483)
  src/utils/app/file.ts
Labels: bug

#486 feat: implement change path dialog (Issues #330, #522)
  src/components/Chat/ChangePathDialog.tsx
  src/components/Chat/PublishModal.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Common/SelectFolder/SelectFolder.tsx
  src/components/Common/SelectFolder/SelectFolderFooter.tsx
  src/components/Common/SelectFolder/SelectFolderHeader.tsx
  src/components/Common/SelectFolder/SelectFolderList.tsx
  src/components/Files/FileManagerModal.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Files/SelectFolderModal.tsx
  src/components/Folder/Folder.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/constants/folders.ts
  src/hooks/useHandleFileFolders.ts
  src/store/conversations/conversations.epics.ts
  src/store/conversations/conversations.reducers.ts
  src/store/conversations/conversations.selectors.ts
  src/store/conversations/conversations.types.ts
  src/store/files/files.reducers.ts
  src/store/prompts/prompts.epics.ts
  src/store/prompts/prompts.reducers.ts
  src/store/prompts/prompts.selectors.ts
  src/store/prompts/prompts.types.ts
  src/types/folder.ts
  src/utils/app/folders.ts
Labels: enhancement, design

#514 feat: implement file view for publishing request wizard (Issue #331)
  src/components/Chat/PublishAttachment.tsx
  src/components/Chat/PublishModal.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Chatbar/components/ChatbarSettings.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Common/ItemContextMenu.tsx
  src/components/Common/SelectFolder/SelectFolderList.tsx
  src/components/Files/FileItemContextMenu.tsx
  src/components/Files/PreUploadModal.tsx
  src/components/Folder/Folder.tsx
  src/components/Header/CreateNewChatMobile.tsx
  src/components/Header/User/UserMobile.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/components/Promptbar/components/PromptbarSettings.tsx
  src/components/Search/SearchFilterRenderer.tsx
  src/constants/folders.ts
  src/store/conversations/conversations.epics.ts
  src/store/conversations/conversations.selectors.ts
  src/types/menu.ts
  src/types/share.ts
  src/utils/app/file.ts
  src/utils/app/folders.ts
  src/utils/app/share.ts
Labels: enhancement, design

#539 fix: add chat header and conversation settings if chosen unavailable model and fix system prompt erasing (Issues #171, #559)
  src/components/Chat/Chat.tsx
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ChatInfoTooltip.tsx
  src/components/Chat/ConversationSettings.tsx
  src/components/Chat/ConversationSettingsModels.tsx
  src/components/Chat/SystemPrompt.tsx
  src/types/chat.ts
  src/utils/app/conversation.ts
Labels: bug

#577 fix: fix the inability to delete a file through edit message (Issue #484)
  src/utils/app/file.ts
Labels: bug

#587 fix: show in MoveTo only own folders (Issue #585)
  src/components/Chatbar/components/Conversation.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/store/conversations/conversations.selectors.ts
  src/store/prompts/prompts.selectors.ts
  src/utils/app/folders.ts
  src/utils/app/search.ts
Labels: bug

#590 chore: redesign settings panel (Issue #492)
  src/components/Chat/AddonsDialog.tsx
  src/components/Chat/ChatSettings.tsx
  src/components/Chat/ConversationSettings.tsx
  src/components/Chat/Temperature.tsx
Labels: enhancement, design

#596 feat: set external entities as not draggable (Issue #584)
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/FolderContextMenu.tsx
  src/components/Common/ItemContextMenu.tsx
  src/components/Folder/Folder.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/components/Sidebar/BetweenFoldersLine.tsx
  src/store/conversations/conversations.reducers.ts
  src/store/conversations/conversations.selectors.ts
  src/utils/app/share.ts
Labels: bug, enhancement

#603 fix: fix drag & drop logic, displaying and not allow to move external entities (Issue #601, #584)
  src/components/Chatbar/Chatbar.tsx
  src/components/Chatbar/components/ChatFolders.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Folder/Folder.tsx
  src/components/Promptbar/Promptbar.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/components/Promptbar/components/PromptFolders.tsx
  src/components/Sidebar/BetweenFoldersLine.tsx
  src/components/Sidebar/Sidebar.tsx
  src/utils/app/move.ts
Labels: bug, enhancement

#570 feat: add user group filter to the publish modal(Issue #433)
  .eslintignore
  src/components/Chat/Addons.tsx
  src/components/Chat/AddonsDialog.tsx
  src/components/Chat/Publish/FilterTypeSelect.tsx
  src/components/Chat/Publish/PublishAttachment.tsx
  src/components/Chat/Publish/PublishWizard.tsx
  src/components/Chat/Publish/RegexParamInput.tsx
  src/components/Chat/Publish/TargetAudienceFilter.tsx
  src/components/Chat/Publish/UserGroupFilter.tsx
  src/components/Chat/__tests__/TargetAudienceFilter.test.tsx
  src/components/Chatbar/components/Conversation.tsx
  src/components/Common/CaretIconComponent.tsx
  src/components/Common/CollapsableSection.tsx
  src/components/Common/MultipleComboBox.tsx
  src/components/Common/__tests__/MultipleComboBox.test.tsx
  src/components/Folder/Folder.tsx
  src/components/Promptbar/components/Prompt.tsx
  src/types/share.ts
Labels: enhancement

#606 fix: not allow to move parent folder in child folder (Issue #604)
  src/components/Folder/Folder.tsx
Labels: bug

#581 fix: fix chat autoscrolling if position of previous chat not at the bottom (Issue #501)
  src/components/Chat/Chat.tsx
Labels: bug

#602 feat: redesign mobile and overlay (Issues #565, #582)
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ChatInput/ChatInputMessage.tsx
  src/components/Chat/ChatInput/SendMessageButton.tsx
  src/components/Chat/ChatMessage.tsx
  src/components/Chat/SystemPrompt.tsx
  src/components/Header/CreateNewChatMobile.tsx
  src/components/Header/Header.tsx
  src/components/Header/User/UserMobile.tsx
  src/components/Markdown/ChatMDComponent.tsx
  src/components/Sidebar/Sidebar.tsx
  src/pages/index.tsx
  src/store/overlay/overlay.epics.ts
  src/store/settings/settings.reducers.ts
  src/utils/app/mobile.ts
Labels: enhancement, design

#626 fix: fix import old prompts without description (Issue #625)
  src/utils/app/search.ts
Labels: bug

#624 fix: fix select folder root name (Issue #597)
  src/components/Chat/ChangePathDialog.tsx
  src/components/Common/SelectFolder/SelectFolderList.tsx
  src/components/Files/SelectFolderModal.tsx
Labels: bug
