Repository epam/ai-dial-chat, pull requests merged in 2025-09, with the labels that each got.

#4578 feat(chat): add toolset authentication methods (Issue #4399, #4577)
  apps/chat/public/images/icons/key.svg
  apps/chat/src/components/Common/Forms/RadioButton.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTable.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/CredentialsStatusIndicator.tsx
  apps/chat/src/components/Marketplace/EntityDetailsHeader.tsx
  apps/chat/src/components/Marketplace/MarketplaceEntityIndicator.tsx
  apps/chat/src/components/ToolsetEditor/EditorForm/AuthField.tsx
  apps/chat/src/components/ToolsetEditor/EditorForm/SettingsForm.tsx
  apps/chat/src/components/ToolsetEditor/ToolsetEditor.tsx
  apps/chat/src/components/ToolsetEditor/ToolsetLoginForm.tsx
  apps/chat/src/components/ToolsetEditor/ToolsetPreview.tsx
  apps/chat/src/components/ToolsetEditor/form.ts
  apps/chat/src/constants/routes.ts
  apps/chat/src/constants/server.ts
  apps/chat/src/constants/toolsets.ts
  apps/chat/src/hooks/useToolsetCredentialsLevel.ts
  apps/chat/src/pages/auth/toolset-signin/index.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/toolset/toolset.epics.ts
  apps/chat/src/store/toolset/toolset.reducer.ts
  apps/chat/src/types/slugs-types.ts
  apps/chat/src/types/toolsets.ts
  apps/chat/src/utils/app/data/toolset-service.ts
  apps/chat/src/utils/app/epics-helpers/publications.epic-helpers.ts
  apps/chat/src/utils/app/epics-helpers/toolset.epic-helpers.ts
  apps/chat/src/utils/app/toolsets.ts
  libs/shared/src/types/toolsets.ts
Labels: enhancement, _priority_1

#4590 fix(chat): fix toolset with default name saving and redirect to my workspace tab when go back to marketplace from apps or toolset editor page (Issues #4570, #4569)
  apps/chat/src/components/ToolsetEditor/ToolsetEditor.tsx
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  package-lock.json
Labels: bug, _priority_2

#4598 fix(chat): restrict creation of toolset with id that already exists and remove unsupported toolset actions (Issues #4561, #4567)
  apps/chat/src/components/Marketplace/AddMarketplaceEntityButton.tsx
  apps/chat/src/components/Marketplace/AddToolsButton.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/ToolsetEditor/EditorForm/EditorForm.tsx
  apps/chat/src/components/ToolsetEditor/EditorForm/GeneralForm.tsx
  apps/chat/src/components/ToolsetEditor/ToolsetEditor.tsx
  apps/chat/src/components/ToolsetEditor/ToolsetEditorView.tsx
  apps/chat/src/hooks/useToolsetMenuActions.ts
  apps/chat/src/hooks/useToolsetMenuItems.ts
  apps/chat/src/pages/api/toolsets-listing/[...slug].ts
  apps/chat/src/pages/api/toolsets-listing/index.ts
  apps/chat/src/pages/api/toolsets/[...slug].ts
  apps/chat/src/pages/toolset-editor/index.tsx
  apps/chat/src/store/toolset/toolset.epics.ts
  apps/chat/src/store/toolset/toolset.reducer.ts
  apps/chat/src/store/toolset/toolset.selectors.ts
  apps/chat/src/store/toolset/toolset.types.ts
  apps/chat/src/utils/app/data/toolset-service.ts
  apps/chat/src/utils/app/toolsets.ts
  libs/shared/src/types/toolsets.ts
Labels: bug, _priority_2

#4607 fix(chat): fix 'next' button when return to the first step of toolset editor (Issue #4606)
  apps/chat/src/components/ToolsetEditor/ToolsetEditor.tsx
Labels: bug

#4605 feat(chat): implement optional support of AUTH_AZURE_B2C_ISSUER (Issue #4611)
  apps/chat/README.md
  apps/chat/src/utils/auth/auth-providers.ts
Labels: enhancement, technical debt

#4604 fix(chat): fix quick app 2 save functionality (Issue #4581)
  apps/chat/src/components/AppsEditor/Settings/form.ts
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  apps/chat/src/components/Chat/TalkTo/ItemCardView.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Common/AgentAndToolsetSelector/AgentAndToolsetModal.tsx
  apps/chat/src/components/Common/AgentAndToolsetSelector/AgentAndToolsetSelector.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/constants/search.ts
  apps/chat/src/hooks/useMarketplaceDisplayedEntities.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/models/models.selectors.ts
  apps/chat/src/store/toolset/toolset.reducer.ts
  apps/chat/src/store/toolset/toolset.selectors.ts
  apps/chat/src/store/toolset/toolset.types.ts
  apps/chat/src/types/marketplace.ts
  apps/chat/src/types/models.ts
  apps/chat/src/types/toolsets.ts
  apps/chat/src/utils/app/marketplace.ts
  apps/chat/src/utils/app/models.ts
Labels: bug

#4614 feat(chat): add failed signin status flow, add login dialog for marketplace (Issue #4600, #4613, #4547)
  apps/chat/public/images/icons/radio-checked.svg
  apps/chat/src/components/Common/DropdownSelector.tsx
  apps/chat/src/components/Common/Forms/RadioButton.tsx
  apps/chat/src/components/Marketplace/AgentsTabRenderer.tsx
  apps/chat/src/components/Marketplace/DeleteMarketplaceEntityDialog.tsx
  apps/chat/src/components/Marketplace/ToolsTabRenderer.tsx
  apps/chat/src/components/Marketplace/ToolsetLoginDialog.tsx
  apps/chat/src/components/ToolsetEditor/EditorForm/AuthField.tsx
  apps/chat/src/components/ToolsetEditor/ToolsetEditor.tsx
  apps/chat/src/components/ToolsetEditor/ToolsetLoginForm.tsx
  apps/chat/src/components/ToolsetEditor/ToolsetPreview.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/constants/toolsets.ts
  apps/chat/src/hooks/useToolsetMenuActions.ts
  apps/chat/src/hooks/useToolsetMenuItems.ts
  apps/chat/src/pages/toolset-editor/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/store/marketplace/marketplace.types.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/toolset/toolset.epics.ts
  apps/chat/src/store/toolset/toolset.reducer.ts
  apps/chat/src/utils/app/epics-helpers/toolset.epic-helpers.ts
  libs/shared/src/types/toolsets.ts
Labels: enhancement

#4619 fix(chat): fix 'next' button for toolset update (Issue #4606)
  apps/chat/src/store/toolset/toolset.epics.ts
Labels: bug

#4622 fix(chat): fix 'next' button for toolset update (Issue #4606)
  apps/chat/src/components/ToolsetEditor/ToolsetEditor.tsx
  apps/chat/src/store/toolset/toolset.epics.ts
  apps/chat/src/store/toolset/toolset.reducer.ts
Labels: bug

#4646 fix(chat): enable themes routes cache (Issue #2774)
  apps/chat/src/pages/api/themes/image/[name].ts
  apps/chat/src/pages/api/themes/listing.ts
  apps/chat/src/pages/api/themes/styles.ts
  package-lock.json
Labels: enhancement, technical debt

#4659 fix(chat): add parsing of string plotly params (Issue #4658)
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Plotly/Plotly.tsx
  apps/chat/src/components/Plotly/PlotlyStringDataRenderer.tsx
Labels: bug

#4666 fix(chat): increase space between name and version (Issue #4592)
  apps/chat/src/components/Common/AgentAndToolsetSelector/AgentAndToolsetChip.tsx
Labels: bug

#4674 fix(chat): add version for toolsets in quick app 2 (Issue #4673)
  apps/chat/src/components/Chat/TalkTo/ItemCardView.tsx
Labels: bug

#4681 fix(chat): add toolset remove bookmark confirmation modal (Issue #4669)
  apps/chat/src/components/Marketplace/DeleteMarketplaceEntityDialog.tsx
  apps/chat/src/components/Marketplace/ToolsTabRenderer.tsx
Labels: bug

#4692 fix(chat): fix toolset id on adding new entity (Issue #4647)
  apps/chat/src/utils/app/toolsets.ts
Labels: bug, _priority_1

#4718 fix(chat): web worker restrictions (Issue #4698)
  apps/chat/src/middleware.ts
Labels: bug

#4720 fix(chat): add security fixes/policies and fix stucking conversations wuth huge stages (Issue #4700, #4683, #4698)
  apps/chat/next.config.js
  apps/chat/src/components/Chat/MessageStage.tsx
  apps/chat/src/components/Chat/NotAllowedModel.tsx
  apps/chat/src/middleware.ts
  apps/chat/src/utils/server/headers-helpers.ts
  package-lock.json
  package.json
  tools/patch-nextjs.js
Labels: bug, _priority_1, PATCH

#4733 fix(chat): disable review toolset edition (Issue #4667)
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewApplicationDialog/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewRowItems/PublicationItemRow.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewToolsetDialog/ReviewToolsetDialogView.tsx
Labels: bug

#4741 fix(chat): add dial_id encoding (Issue #4740)
  apps/chat/src/components/AppsEditor/Settings/form.ts
Labels: bug, _priority_1

#4754 fix(chat): fix toolsets encoding & decoding (Issue #4740)
  apps/chat/src/components/AppsEditor/Settings/form.ts
Labels: bug, _priority_1

#4758 fix(chat): 404 page has dark theme, when use light theme (Issue #4734)
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat/public/scripts/theme-loader.js
  apps/chat/src/pages/_document.tsx
Labels: bug

#4762 fix(chat): always include stylesheet link for themes ( Issue #4734)
  apps/chat/src/pages/_document.tsx
Labels: bug

#4763 fix(chat): call getConfigurationSchema only once when change conversation (Issue #4730)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#4768 fix(chat): fix sidebar infinity scroll spinner sticking (Issue #4752) (#4764)
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Sidebar/ResizableSidebarWrapper.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/components/Sidebar/SidebarSections.tsx
Labels: bug

#4775 fix(chat): do not send configuration requests in compare mode and when agent wasn't changed (Issue #4730)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#4778 fix(chat): fix load starters failed error for quick apps (Issue #4730)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug
