Repository epam/ai-dial-chat, pull requests merged in 2025-01, with the labels that each got.

#2880 feat(chat): add populate & action buttons support into chat (Issue #2837)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/AssistantMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/AssistantSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/UserSchema.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/hooks/usePromptSelection.ts
  apps/chat/src/store/chat/chat.epics.ts
  apps/chat/src/store/chat/chat.reducer.ts
  apps/chat/src/store/chat/chat.selectors.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/index.ts
  apps/chat/src/styles/globals.css
  apps/chat/src/types/chat.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/form-schema.ts
  apps/chat/src/utils/app/merge-streams.ts
  apps/chat/src/utils/server/chat.ts
  libs/shared/src/types/chat.ts
  libs/shared/src/types/index.ts
  libs/shared/src/types/message-form-schema.ts
Labels: enhancement

#2897 fix(chat): fix initialization of recent models (Issue #2881)
  apps/chat-e2e/src/tests/overlay/modelIdFeature.test.ts
  apps/chat/src/components/Chat/ChatSettings/AddonsDialog.tsx
  apps/chat/src/store/models/models.reducers.ts
Labels: bug, _priority_1

#2904 fix(chat): add error boundary for invalid form schema (Issue #2901)
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/AssistantMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/MessageSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/UserSchema.tsx
  apps/chat/src/components/Common/ErrorBoundary.tsx
Labels: bug, _priority_1

#2905 fix(overlay): fix set recent models ids and model id in overlay mode (Issue #2794)
  apps/chat-e2e/src/tests/overlay/modelIdFeature.test.ts
  apps/chat/src/store/overlay/overlay.epics.ts
Labels: bug, _priority_1

#2892 fix(chat): improve Change Agent handling and add mobile tooltips in chats (Issues #2842, #2849)
  apps/chat-e2e/src/tests/publishConversation.test.ts
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Header/CreateNewConversation.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
Labels: bug

#2906 fix(chat): fix removed model version display in card if it was selected (Issue #2882)
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
Labels: bug, _priority_3

#2908 fix(overlay): fix overlay select conversation response (Issue #2745)
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/overlay-sandbox/app/cases/components/chatOverlayWrapper.tsx
Labels: bug

#2912 fix(chat): revert login/logout changes
  apps/chat-e2e/src/tests/announcementBanner.test.ts
  apps/chat-e2e/src/tests/overlay/overlayAuth.ts
  apps/chat-e2e/src/ui/actions/auth0Login.ts
  apps/chat-e2e/src/ui/actions/azureADLogin.ts
  apps/chat-e2e/src/ui/actions/keycloakLogin.ts
  apps/chat-e2e/src/ui/actions/providerLogin.ts
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  apps/chat/src/pages/api/auth/federated-logout.ts
  apps/chat/src/pages/auth/signin/index.tsx
  apps/chat/src/utils/auth/auth-callbacks.ts
  apps/chat/src/utils/auth/auth-pages.ts
  apps/chat/src/utils/auth/auth-providers.ts
  apps/chat/src/utils/auth/signOut.ts
  apps/chat/src/utils/server/get-common-page-props.ts
  package-lock.json
  package.json
Labels: bug, PATCH

#2907 fix(chat): fix error placement in select folder window (Issue #1335)
  apps/chat-e2e/src/tests/selectUploadFolder.test.ts
  apps/chat-e2e/src/ui/selectors/chatSelectors.ts
  apps/chat-e2e/src/ui/webElements/selectFolderModal.ts
  apps/chat/src/components/Common/ErrorMessage.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
Labels: bug

#2913 fix(chat): change code editor confirmation buttons order (Issue #2734)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
Labels: bug

#2917 fix(chat): optimize chat messages processing logic, remove extra requests (Issue #2891)
  apps/chat-e2e/src/assertions/api/apiAssertion.ts
  apps/chat-e2e/src/testData/api/chatApiHelper.ts
  apps/chat-e2e/src/tests/chatHeader.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/types/chat.ts
Labels: bug, _priority_1

#2933 fix(chat): fix system prompt updating (Issue #2920)
  apps/chat/src/components/Chat/ChatSettings/SystemPrompt.tsx
  apps/chat/src/hooks/usePromptSelection.ts
Labels: bug

#2932 feat(modulify-ui): library updates (#2787)
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInput.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/SendMessageButton.tsx
  apps/chat/src/components/Chat/ChatSettings/ConversationSettings.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/pages/_app.tsx
  apps/chat/src/pages/_document.tsx
  libs/modulify-ui/README.md
  libs/modulify-ui/src/index.ts
  libs/modulify-ui/src/lib/ComponentBuilder.tsx
  libs/modulify-ui/src/lib/Inversify.tsx
  libs/modulify-ui/src/lib/utils/appWithJss.tsx
  libs/modulify-ui/src/lib/utils/documentWithJss.tsx
  tools/patch-nextjs.js
Labels: enhancement, technical debt

#2939 fix(chat): hide disabled edit button on mobile (Issue #2784)
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
Labels: bug

#2940 feat(chat): refactoring of QuickApps (Issue #2936)
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/constants/quick-apps.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/types/applications.ts
  apps/chat/src/types/models.ts
  apps/chat/src/types/quick-apps.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/data/defaults-service.ts
  apps/chat/src/utils/server/get-common-page-props.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
Labels: enhancement, _priority_1

#2942 fix(chat): remove endpoint from payload if applicationTypeSchemaId was specified (Issue #2936)
  apps/chat/src/types/applications.ts
  apps/chat/src/utils/app/application.ts
Labels: bug, _priority_1

#2944 fix(chat): show full QuickApp description (Issue #2936)
  apps/chat/src/constants/quick-apps.ts
  apps/chat/src/utils/app/application.ts
Labels: bug

#2946 feat(chat): refactoring of QuickApps (Issue #2936)
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/constants/quick-apps.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/types/applications.ts
  apps/chat/src/types/models.ts
  apps/chat/src/types/quick-apps.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/data/defaults-service.ts
  apps/chat/src/utils/server/get-common-page-props.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
Labels: enhancement, _priority_1, PATCH

#2951 fix(chat): update recent models when agents added to workspace from chat (Issue #2822)
  apps/chat/src/components/Chat/ChatInput/AddModelsControl.tsx
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
Labels: bug

#2909 feat(chat): Add opportunity to share applications (Issue #2044)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat/.env.development
  apps/chat/public/images/icons/unshare-user.svg
  apps/chat/public/locales/en/sidebar.json
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizard.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizardFooter.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/view-props.ts
  apps/chat/src/components/Common/UnshareDialog.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/pages/marketplace/index.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/types/applications.ts
  apps/chat/src/types/common.ts
  apps/chat/src/types/models.ts
  apps/chat/src/types/share.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/share.ts
  libs/shared/src/types/chat.ts
  libs/shared/src/types/features.ts
Labels: enhancement, _priority_1

#2931 feat(chat): add chat starter buttons (Issue #2922, #2927)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputControls.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/SchemaCompareWarning.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/AssistantSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/UserSchema.tsx
  apps/chat/src/components/Chat/ChatStarters.tsx
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/store/chat/chat.epics.ts
  apps/chat/src/store/chat/chat.reducer.ts
  apps/chat/src/store/chat/chat.selectors.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/styles/globals.css
  apps/chat/src/types/chat.ts
  apps/chat/src/types/common.ts
  apps/chat/src/types/models.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/application-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/application-api-storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
  apps/chat/src/utils/app/form-schema.ts
  apps/chat/src/utils/app/merge-streams.ts
  apps/chat/src/utils/app/models.ts
  apps/chat/src/utils/server/api.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
  apps/chat/src/utils/server/index.ts
  libs/shared/src/types/chat.ts
  libs/shared/src/types/message-form-schema.ts
Labels: enhancement

#2947 feat(chat): add opportunity to use Marketplace-share link
  apps/chat/next.config.js
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/index.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/settings/settings.epic.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/types/store.ts
Labels: enhancement

#2958 chore(chat): split `models.reducers.ts` to types, selectors and reducers
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/models/models.selectors.ts
  apps/chat/src/store/models/models.types.ts
Labels: technical debt

#2953 fix(chat): keep application wizard open on failed save request (Issue #2949)
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizard.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/application/application.selectors.ts
Labels: bug, _priority_2

#2970 fix(chat): change description and icon for playback and replay as is conversations start screen (Issues #2756, #2757)
  apps/chat-e2e/src/tests/chatExportImportWithAttachment.test.ts
  apps/chat-e2e/src/tests/messageTemplate.test.ts
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/utils/app/conversation.ts
  startup.sh
Labels: bug, _priority_2

#2976 fix(chat): minor UI fixes (Issue #2941, #2827, #2766, #2963, #2964)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Chat/ChatStarters.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Marketplace/CardsList.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/tailwind.config.js
Labels: bug, enhancement, _priority_2, _priority_3

#2871 fix(chat): increase max headers size (Issue #2852)
  .dockerignore
  Dockerfile
  apps/chat/README.md
  package.json
  startup.sh
Labels: bug, _priority_1

#2969 fix(chat): reset Marlketplace state for "DIAL Marketplace" link (Issue #2614)
  apps/chat/src/pages/marketplace/index.tsx
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
Labels: bug

#2945 feat(chat): Add share icon in applications, sources filters (Issue #2915)
  apps/chat/public/images/icons/arrow-up-right.svg
  apps/chat/src/components/Chat/MainModalManager.jsx
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Common/ShareIcon.tsx
  apps/chat/src/components/Common/UnshareDialog.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/pages/marketplace/index.tsx
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/models/models.selectors.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/types/marketplace.ts
Labels: enhancement

#2982 fix(chat): revert login/logout changes
  apps/chat-e2e/src/tests/announcementBanner.test.ts
  apps/chat-e2e/src/tests/overlay/overlayAuth.ts
  apps/chat-e2e/src/ui/actions/auth0Login.ts
  apps/chat-e2e/src/ui/actions/azureADLogin.ts
  apps/chat-e2e/src/ui/actions/keycloakLogin.ts
  apps/chat-e2e/src/ui/actions/providerLogin.ts
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  apps/chat/src/pages/api/auth/federated-logout.ts
  apps/chat/src/pages/auth/signin/index.tsx
  apps/chat/src/utils/auth/auth-callbacks.ts
  apps/chat/src/utils/auth/auth-pages.ts
  apps/chat/src/utils/auth/auth-providers.ts
  apps/chat/src/utils/auth/signOut.ts
  apps/chat/src/utils/server/get-common-page-props.ts
  package-lock.json
  package.json
Labels: bug, PATCH

#2981 fix(chat): revert login/logout changes
  apps/chat-e2e/src/tests/announcementBanner.test.ts
  apps/chat-e2e/src/tests/overlay/overlayAuth.ts
  apps/chat-e2e/src/ui/actions/auth0Login.ts
  apps/chat-e2e/src/ui/actions/azureADLogin.ts
  apps/chat-e2e/src/ui/actions/keycloakLogin.ts
  apps/chat-e2e/src/ui/actions/providerLogin.ts
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  apps/chat/src/pages/api/auth/federated-logout.ts
  apps/chat/src/pages/auth/signin/index.tsx
  apps/chat/src/utils/auth/auth-callbacks.ts
  apps/chat/src/utils/auth/auth-pages.ts
  apps/chat/src/utils/auth/auth-providers.ts
  apps/chat/src/utils/auth/signOut.ts
  apps/chat/src/utils/server/get-common-page-props.ts
  package-lock.json
  package.json
Labels: bug

#2977 fix(chat): add 'back to publication request' button if model is not allowed and fix 'organization conversations highlighting' (Issues #2183, #2978)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
Labels: bug

#2998 feat(chat): add new application type filters (Issue #2996)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Files/FileItemContextMenu.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/marketplace.ts
Labels: enhancement

#2985 fix(chat): increase max headers size (Issue #2852)
  .dockerignore
  Dockerfile
  apps/chat/README.md
  package.json
  startup.sh
Labels: bug, _priority_1

#2992 fix(chat): Change nested folders error placement (Issue #2974)
  apps/chat-e2e/src/tests/conversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/errorUploadFromDevice.test.ts
  apps/chat-e2e/src/tests/publishConversationToOrganisation.test.ts
  apps/chat-e2e/src/tests/publishPrompt.test.ts
  apps/chat-e2e/src/tests/selectUploadFolder.test.ts
  apps/chat-e2e/src/ui/webElements/attachFilesModal.ts
  apps/chat-e2e/src/ui/webElements/modalError.ts
  apps/chat-e2e/src/ui/webElements/selectFolderModal.ts
  apps/chat-e2e/src/ui/webElements/uploadFromDeviceModal.ts
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/SelectFolderModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug

#2961 feat(chat): Add the application shared with the user to a "My workspace" (Issue 2955, 2965)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/models/models.types.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/store/share/share.selectors.ts
  apps/chat/src/store/share/share.types.ts
Labels: enhancement

#3006 feat(chat): refactoring source filters (Issue #2994, #3009)
  apps/chat/src/components/Chat/ChatSettings/ConversationSettings.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/types/applications.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/marketplace.ts
Labels: enhancement

#3003 fix(chat): fix chat/folder disappearing after approving unpublish request (Issue #2727)
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/utils/app/publications.ts
  apps/chat/src/utils/server/api.ts
Labels: bug

#3010 fix(chat): fix reset filters after logout (Issue #2989, #2952)
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  apps/chat/src/constants/default-ui-settings.ts
  apps/chat/src/hooks/useLogout.ts
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug

#3011 fix(chat): get rid of redundant models requests, fix duplications from approve required section, fix organization section and folders highlight (Issues #2978, #2183)
  apps/chat-e2e/src/ui/webElements/chatHeader.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatSettings/ConversationSettings.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
Labels: bug

#3005 feat(chat): handle required schema buttons, fix name regenerate, improve schema validation (Issue #2980, #2901, #2972, #2986)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/AssistantSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/MessageSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/UserSchema.tsx
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/form-schema.ts
  apps/chat/src/utils/app/typeValidator.ts
Labels: bug, enhancement, _priority_1

#3021 fix(chat): fix settings tooltip (Issue #3020)
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/ChatHeader/HeaderSettingsTooltip.tsx
Labels: bug

#3022 fix(chat): fix mobile menu popup on custom button click (Issue #2986)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
Labels: bug

#3026 fix(chat): fix Marketplace filters and navigation (Issue #3023, #3018)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/pages/marketplace/index.tsx
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/settings/settings.epic.ts
Labels: bug, _priority_1

#3015 fix(chat): fix max headers size (Issue #2983)
  apps/chat/.env.development
Labels: bug

#3008 feat(chat): Add the application shared with the user to a "My workspace" (Issue #2955, #2965, #2971, #3004)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeEditor.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Files/FileItemContextMenu.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/codeEditor/codeEditor.epics.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/models/models.types.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/store/share/share.selectors.ts
  apps/chat/src/store/share/share.types.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/text-file-service.ts
  apps/chat/src/utils/app/folders.ts
Labels: enhancement

#3032 fix(chat): fix conversation requests during message generation (Issue #3031)
  apps/chat-e2e/src/ui/webElements/conversationToCompare.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/baseSideBarConversationTree.ts
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1

#3038 fix(chat): fix review chat crash, hide unpublish option, adjust marketplace grid (Issue #3029, #3016, #3014)
  apps/chat/src/components/Chat/ChatCompareSelect.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Marketplace/CardsList.tsx
Labels: bug

#3039 fix(chat): fix conversation requests during message generation (Issue #3031)
  apps/chat-e2e/src/ui/webElements/conversationToCompare.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/baseSideBarConversationTree.ts
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1, PATCH

#3041 fix(chat): fix conversation requests during message generation (Issue #3031)
  apps/chat-e2e/src/ui/webElements/conversationToCompare.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/baseSideBarConversationTree.ts
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1, PATCH

#3033 fix(chat): disable fields after editing shared app (Issue #3017)
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizard.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/view-props.ts
Labels: bug

#3035 fix(chat): fix custom buttons in playback mode, hide templates in schema chats (Issue #3002, #3013)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Chat/ChatStarters.tsx
  apps/chat/src/components/Chat/Playback/PlaybackControls.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug

#3027 fix(chat): fix version groups cleanup after approving unpublish request (Issue #2727)
  apps/chat/src/components/Chat/Publish/PublicVersionSelector.tsx
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug

#3030 fix(chat): add models models and files uploading if approved request has such resources (Issue #2048)
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
Labels: bug

#3037 fix(chat): add sharing revoke if change code app source folder (Issue# 2962)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/pages/marketplace/index.tsx
Labels: bug

#3057 feat(chat): add document_relative_url and model fields to quick app editor (Issue #3053)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat/src/components/Chat/ChatSettings/AssistantSubModelSelector.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/components/Common/ModelsSelector.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/types/quick-apps.ts
  apps/chat/src/utils/app/application.ts
Labels: enhancement, _priority_1

#3064 fix(chat): save input content during UI manipulations (Issue #3063)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug, _priority_1

#3066 fix(chat): fix Code Apps editing (Issue #3059)
  apps/chat/src/store/models/models.reducers.ts
Labels: bug, _priority_1

#3068 fix(chat): sort filters and "Add app" options (Issue #3067)
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/constants/marketplace.ts
Labels: enhancement

#3025 fix(chat): fix card design, add copy link and share in context menu, correct mobile icon size (Issues #2943, #2991)
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationCopyLink.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/CardsList.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/constants/marketplace.ts
Labels: enhancement

#3074 fix(chat): add warning messages for published or shared application icon (Issue #3047)
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/store/share/share.epics.ts
Labels: bug, enhancement
