Repository epam/ai-dial-chat, pull requests merged in 2025-02, with the labels that each got.

#3076 feat(overlay-sandbox): improve UI navigation in Overlay Sandbox (Issue #3072)
  apps/overlay-sandbox/app/cases/components/backToSelectOverlayMode.tsx
  apps/overlay-sandbox/app/cases/components/chatOverlayManagerWrapper.tsx
  apps/overlay-sandbox/app/cases/components/chatOverlayWrapper.tsx
  apps/overlay-sandbox/app/cases/overlay-manager/page.tsx
  apps/overlay-sandbox/app/global.css
  apps/overlay-sandbox/app/page.tsx
Labels: enhancement, technical debt

#3070 fix(chat): fix replay as is start screen for not available modelId (Issue #2847)
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
Labels: bug

#3078 feat(chat): add document_relative_url to application sharing/publishing flow (Issue #3054)
  apps/chat/src/components/Chat/Publish/ApplicationPublishItems.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/publications.ts
Labels: enhancement, _priority_1

#3081 fix(overlay-sandbox): fix `removeOverlay` conditions (Issue #3072)
  apps/overlay-sandbox/app/cases/components/chatOverlayManagerWrapper.tsx
Labels: bug

#3087 chore(chat): refactore modal imports
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/ChatMessageTemplatesModal.tsx
  apps/chat/src/components/Chat/ChatSettings/AddonsDialog.tsx
  apps/chat/src/components/Chat/ChatSettings/ChatSettingsModal.tsx
  apps/chat/src/components/Chat/MainModalManager.jsx
  apps/chat/src/components/Chat/Publish/CompareRulesModal.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog.tsx
  apps/chat/src/components/Chat/Publish/TargetAudienceFilterComponent.tsx
  apps/chat/src/components/Chat/RenameConversationModal.tsx
  apps/chat/src/components/Chat/ReportIssueDialog.tsx
  apps/chat/src/components/Chat/RequestApiKeyDialog.tsx
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chatbar/ExportModal.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizard.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
  apps/chat/src/components/Common/FullPageLoader.tsx
  apps/chat/src/components/Common/FullScreenImages.tsx
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Common/MoveToFolderMobileModal.tsx
  apps/chat/src/components/Common/OptionsDialog.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolder.tsx
  apps/chat/src/components/Files/AttachLinkDialog.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationLogs.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/components/Settings/SettingDialog.tsx
  apps/overlay-sandbox/app/cases/components/chatOverlayManagerWrapper.tsx
  apps/overlay-sandbox/app/cases/components/chatOverlayWrapper.tsx
Labels: enhancement, technical debt

#3082 fix(chat): fix 'cancel' button when change source folder (Issue #3075)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
Labels: bug, _priority_2

#3099 fix: Hide 'Logs' button for the shared code application (Issue #3086)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
Labels: bug, _priority_1

#3105 fix(chat): fix cancel button when change document relative url for shared app (Issue #3075)
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
Labels: bug

#3088 fix(chat): fix modal displaying logic (Issue #2878)
  apps/chat/src/components/Chat/ChatInput/ChatInputFooter.tsx
  apps/chat/src/components/Chat/ChatModalsManager.jsx
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/components/Chat/RenameConversationModal.tsx
  apps/chat/src/components/Chat/ReportIssueDialog.tsx
  apps/chat/src/components/Chat/RequestApiKeyDialog.tsx
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chat/__tests__/FooterMessage.test.tsx
  apps/chat/src/components/Chatbar/ImportExportLoader.tsx
  apps/chat/src/components/Common/FooterMessage.tsx
  apps/chat/src/components/Common/RenderWhen.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
  apps/chat/src/components/Common/ScreenRender.tsx
  apps/chat/src/components/Common/UnshareDialog.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  apps/chat/src/pages/index.tsx
  apps/chat/src/pages/marketplace/index.tsx
  apps/chat/src/store/share/share.selectors.ts
Labels: bug, enhancement, technical debt

#3100 feat(chat): implement `use prompt` context menu (Issue #3065)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat/public/images/icons/insert-prompt.svg
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatCompareRotate.tsx
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/ChatInput/ChatControls.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/PromptVariablesForApplyDialog.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/AssistantMessage.tsx
  apps/chat/src/components/Chat/ChatModalsManager.jsx
  apps/chat/src/components/Chat/ChatSettings/ChatSettingsModal.tsx
  apps/chat/src/components/Chat/ChatSettings/ConversationSettings.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  apps/chat/src/components/Chat/MessageAttachment.tsx
  apps/chat/src/components/Chat/MessageAttachments.tsx
  apps/chat/src/components/Chat/MessageStage.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/Combobox.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Common/NoResultsFound.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Header/User/ProfileButton.tsx
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Markdown/CodeBlock.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/store/chat/chat.reducer.ts
  apps/chat/src/store/chat/chat.selectors.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
  apps/chat/src/utils/app/data/storages/api/prompt-api-storage.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/server/api.ts
Labels: enhancement

#3097 fix(chat): add context menu copy link, fix deploy dot spacing (Issues #3089, #3090)
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationCopyLink.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/utils/marketplace.ts
Labels: bug

#3108 feat(chat): auto focus on chat input on first page load (Issue #3051)
  apps/chat/src/components/Chat/Chat.tsx
Labels: enhancement, _priority_3

#3062 feat(chat): move from `edit` to `move` endpoint for conversations/prompts rename (Issue #3052)
  apps/chat-e2e/src/assertions/api/apiAssertion.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/testData/expectedMessages.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/chatBarFolderConversation.test.ts
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat-e2e/src/tests/conversationNameNumeration.test.ts
  apps/chat-e2e/src/tests/duplicateSharedConversations.test.ts
  apps/chat-e2e/src/tests/folderNameNumeration.test.ts
  apps/chat-e2e/src/tests/folderPrompts.test.ts
  apps/chat-e2e/src/tests/messageTemplate.test.ts
  apps/chat-e2e/src/tests/parametrizedReplay.test.ts
  apps/chat-e2e/src/tests/promptFolderNamesakes.test.ts
  apps/chat-e2e/src/tests/promptFolderNumeration.test.ts
  apps/chat-e2e/src/tests/promptFoldersSpecialChars.test.ts
  apps/chat-e2e/src/tests/promptMaximumNameLength.test.ts
  apps/chat-e2e/src/tests/promptUsage.test.ts
  apps/chat-e2e/src/tests/publishConversationToOrganisation.test.ts
  apps/chat-e2e/src/tests/publishFolderWithConversation.test.ts
  apps/chat-e2e/src/tests/publishPrompt.test.ts
  apps/chat-e2e/src/tests/scrolling.test.ts
  apps/chat-e2e/src/tests/selectUploadFolder.test.ts
  apps/chat-e2e/src/tests/shareConversationWithContent.test.ts
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat-e2e/src/tests/sharedPromptFolderIcons.test.ts
  apps/chat-e2e/src/tests/sharedPromptIcons.test.ts
  apps/chat-e2e/src/tests/sharedPromptView.test.ts
  apps/chat-e2e/src/ui/webElements/chatMessages.ts
  apps/chat-e2e/src/ui/webElements/entityTree/folders.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/baseSideBarConversationTree.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/sideBarEntitiesTree.ts
  apps/chat-e2e/src/ui/webElements/promptModalDialog.ts
  apps/chat-e2e/src/ui/webElements/renameConversationModal.ts
  apps/chat-e2e/src/ui/webElements/talkToAgentDialog.ts
  apps/chat/public/locales/en/sidebar.json
  apps/chat/src/components/Chat/RenameConversationModal.tsx
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/utils/app/data/conversation-service.ts
  apps/chat/src/utils/app/data/prompt-service.ts
Labels: enhancement, technical debt

#3104 fix(chat): fix external attachments checking for folders (Issue #2930)
  apps/chat/src/constants/folders.ts
  apps/chat/src/utils/app/file.ts
Labels: bug, _priority_1

#3122 fix(chat): recognition of the accepted shared resource (Issue #2652)
  apps/chat/src/store/share/share.epics.ts
Labels: bug

#3120 feat(chat): focus and scroll after applying of prompt (Issue #3056)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Files/FileItemContextMenu.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/hooks/useHandler.ts
  apps/chat/src/hooks/usePromptSelection.ts
  apps/chat/src/store/chat/chat.epics.ts
  apps/chat/src/store/chat/chat.reducer.ts
  apps/chat/src/store/chat/chat.selectors.ts
Labels: enhancement

#3118 fix(chat): fix sharing of source folder after changing it and optimize marketplace components rendering (Issue #3083)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/Forms/DynamicFormFields.tsx
  apps/chat/src/components/Marketplace/CardsList.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
Labels: bug, _priority_2

#3134 chore(chat): upgrade node docker image version
  Dockerfile
Labels: bug

#3139 fix(chat): fix code app dot gap (Issue #3090)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
Labels: bug

#3136 fix(chat): adds last conversation temperature setting retrieving from the local storage (Issue #3116)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1

#3127 fix(chat): fix chat server error handling (Issue #2914)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug

#3160 fix(chat): fix message template replacement (Issue #2271)
  apps/chat/src/components/Chat/ChatInput/ReplayVariables.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageTemplatesModal/ChatMessageTemplatesModal.tsx
  apps/chat/src/utils/app/prompts.ts
  package-lock.json
Labels: bug

#3094 fix(chat): update custom buttons view in playback, fix replay deleted model, update apps wizard (Issue #3002, #2911, #2898)
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/AssistantSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Chat/ChatStarters.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizardFooter.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
Labels: bug, enhancement

#3119 fix(chat): reflect changes in the file list within the "Manage attachments" modal, without refreshing the page (Issue #2685, #3093)
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/utils/app/publications.ts
Labels: bug, _priority_2

#3129 fix(chat): hide quick app document in publish modal, add quick & code app fields in review modal (Issue #3107, #3109, #3112)
  apps/chat/src/components/Chat/Publish/ApplicationPublishItems.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewApplicationDialog.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewApplicationPropsSection.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewCodeAppSection.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewQuickAppSection.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/FormCodeEditor.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/components/Common/CodeEditor.tsx
  apps/chat/src/components/Common/MonacoEditor.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/store/codeEditor/codeEditor.epics.ts
  apps/chat/src/types/files.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/publications.ts
Labels: bug

#3169 fix(chat): fix word wrapping (Issue #3161)
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/styles/globals.css
Labels: bug, _priority_2

#3165 feat(chat): add counter to tags (Issue #3034)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/ApplicationTopic.tsx
  apps/chat/src/components/Marketplace/TopicsList.tsx
Labels: enhancement

#3173 fix(chat): fix schema validity check in not empty chat (Issue #3172)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
Labels: bug

#3177 fix(chat): disable prompt use when chat input is hidden (Issue #3159)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/store/chat/chat.reducer.ts
  apps/chat/src/store/chat/chat.selectors.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug, _priority_2

#3182 feat(chat): fix tags tooltip distances (Issue #3034)
  apps/chat/src/components/Marketplace/TopicsList.tsx
  apps/chat/tailwind.config.js
Labels: enhancement

#3191 fix(chat): fix topic plus click for mobile (Issue #3183)
  apps/chat/src/components/Marketplace/TopicsList.tsx
Labels: bug

#3193 feat(chat): open and close tooltip with topics (Issue #3194)
  apps/chat/src/components/Marketplace/TopicsList.tsx
Labels: enhancement

#3184 fix(chat): fix topics sorting (Issue #3183)
  apps/chat/src/store/models/models.selectors.ts
Labels: bug

#3196 feat(chat): close tooltip when click inside (Issue #3194)
  apps/chat/src/components/Marketplace/TopicsList.tsx
Labels: enhancement

#3176 feat(chat): implement table view (Issue #2039)
  apps/chat/.env.development
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTable.tsx
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTableLeftSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsTable/HeaderItem.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationTopic.tsx
  apps/chat/src/components/Marketplace/CardsList.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/components/Marketplace/ViewToggler.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/types/models.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
  libs/shared/src/types/features.ts
Labels: enhancement, _priority_1

#3200 fix(chat): fix model version and use button fonts (Issue #2374)
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
Labels: bug

#3204 fix(chat): fix select agent topic collapse (Issue #3202)
  apps/chat/src/components/Marketplace/TopicsList.tsx
Labels: bug

#3207 fix(chat): fix click inside tooltip on iOS (Issue #3206)
  apps/chat/src/components/Marketplace/TopicsList.tsx
Labels: bug

#3157 fix(chat): hide like/dislike in external chat, fix renaming newly added folder in manage attachments (Issue #1272, #3115)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/folders.ts
Labels: bug, _priority_1

#3199 feat(chat): implement table view (Part 2) (Issue #2039)
  apps/chat-e2e/src/tests/myWorkspaceSearch.test.ts
  apps/chat-e2e/src/ui/selectors/marketplaceSelectors.ts
  apps/chat-e2e/src/ui/webElements/marketplace/agentDetailsModal.ts
  apps/chat/src/components/Marketplace/AgentBookmark.tsx
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTable.tsx
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTableLeftSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/hooks/useSyncXScroll.ts
Labels: enhancement, _priority_1

#3219 feat(chat): show publication author in the review modal (Issue #3211)
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Common/InfoModal.tsx
  apps/chat/src/types/publication.ts
  apps/chat/src/utils/app/common.ts
Labels: enhancement, _priority_1

#3224 fix: update prompt's 'Last updated' date without refresh, remove 'Last updated' from published (Issues #3216, #3220)
  apps/chat/src/components/Common/InfoModal.tsx
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug

#3222 feat(chat): implement table view sorting (Issue #2040)
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTable.tsx
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTableLeftSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsTable/HeaderItem.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/types/common.ts
Labels: enhancement, _priority_2

#3209 fix(chat): fix use & export of prompts from shared with me listing (Issue #3190)
  apps/chat/src/components/Chat/ChatInput/PromptVariablesDialog.tsx
  apps/chat/src/store/share/share.epics.ts
Labels: bug, _priority_2

#3231 fix(chat): fix long app name displaying (Issue #3228)
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  apps/chat/src/types/applications.ts
Labels: bug

#3243 fix(chat): fix Quick App editing (Issue #3234)
  apps/chat/src/components/AppsEditor/Settings/form.ts
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Common/ApplicationWizard/QuickAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/utils/app/application.ts
Labels: bug, _priority_1

#3249 fix(chat): fix saving shared with me app (Issue #3245)
  apps/chat/src/store/application/application.epics.ts
Labels: bug, _priority_1

#3250 fix(chat): fix saving shared with me application (Issue #3245)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
Labels: bug, _priority_1

#3252 fix(chat): hide context menu on preview (Issue #3233)
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
Labels: bug

#3236 feat(chat): hide banner when starting scroll table (Issue #2039)
  apps/chat/src/components/IframeRenderer/index.tsx
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTable.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/styles/globals.css
  apps/chat/src/types/applications.ts
Labels: enhancement, _priority_1

#3253 fix(chat): fix App Editor UI issues (Issue #3235, #3244)
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/Previews/ApplicationPreviewChat.tsx
  apps/chat/src/components/AppsEditor/Settings/Previews/CustomChatViewer.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizard.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizardFooter.tsx
  apps/chat/src/components/Common/ApplicationWizard/ApplicationWizardHeader.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppView.tsx
  apps/chat/src/components/Common/ApplicationWizard/CustomAppView.tsx
  apps/chat/src/components/Header/Logo.tsx
  apps/chat/src/components/IframeRenderer/index.tsx
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/constants/routes.ts
  apps/chat/src/hooks/useLogout.ts
  apps/chat/src/pages/marketplace/index.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/utils/app/route.ts
Labels: bug, _priority_3

#3264 fix(chat): fix application context menu (Issue #3262)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/utils/app/share.ts
Labels: bug, _priority_1

#3266 chore(chat): update default app date
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationContent.tsx
  apps/chat/src/store/auth/auth.reducers.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
Labels: enhancement

#3271 fix(chat): add hover for 'General info' and 'App settings' steps (Issue #3260)
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
Labels: bug

#3272 fix(chat): fix editing shared application (Issue #3263)
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/store/application/application.epics.ts
Labels: bug, _priority_1

#3276 fix(chat): fix sudden refreshes in development mode (Issue #3132)
  apps/chat/next.config.js
  apps/chat/src/pages/_app.tsx
  apps/chat/src/pages/_document.tsx
Labels: bug, _priority_1
