Repository epam/ai-dial-chat, pull requests merged in 2025-10, with the labels that each got.

#4787 fix(chat): delete action fails with error for toolset with special symbols in name and OAuth type of authentication (Issues #4771, #4777)
  apps/chat/src/components/Chat/Publish/PublicationItem.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/toolset/toolset.epics.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/types/toolsets.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/application-api-storage.ts
  apps/chat/src/utils/app/data/storages/api/toolset-api-storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
  apps/chat/src/utils/app/data/toolset-service.ts
  apps/chat/src/utils/app/epics-helpers/toolset.epic-helpers.ts
  apps/chat/src/utils/app/publications.ts
  apps/chat/src/utils/app/toolsets.ts
  apps/chat/src/utils/server/api.ts
Labels: bug, technical debt, _priority_2

#4779 chore(chat): refactor apiKey parsers (Issue #4788)
  apps/chat/src/components/Chat/Publish/PublicationItem.tsx
  apps/chat/src/hooks/useToolsetEditorValidation.ts
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/types/common.ts
  apps/chat/src/types/parse-entity.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/data/storages/api/application-api-storage.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
  apps/chat/src/utils/app/data/storages/api/prompt-api-storage.ts
  apps/chat/src/utils/app/data/storages/api/toolset-api-storage.ts
  apps/chat/src/utils/app/prompts.ts
  apps/chat/src/utils/app/publications.ts
  apps/chat/src/utils/server/api.ts
Labels: technical debt

#4807 fix(chat): revert send configuration model request based on modelId (Issue #4730)
  apps/chat/src/components/Chat/Chat.tsx
Labels: _priority_1

#4811 fix(chat): update default icon and warning text from 'application' to 'toolset' on the publication request creation form (Issues #4715, #4724)
  apps/chat/src/components/Chat/Publish/MarketplaceEntityPublishItem.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/TabResults.tsx
Labels: bug, enhancement, _priority_3

#4769 fix(chat): change agents and toolsets modal selected items (Issue #4676)
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewApplicationDialog/ReviewQuickApp2Section.tsx
  apps/chat/src/components/Common/AgentAndToolsetSelector/AgentAndToolsetModal.tsx
  apps/chat/src/components/Common/AgentAndToolsetSelector/OverflowButton.tsx
  apps/chat/src/components/Common/AgentAndToolsetSelector/OverflowListItem.tsx
  apps/chat/src/components/Common/AgentAndToolsetSelector/SelectedItemsContainer.tsx
  apps/chat/src/components/Common/OverflowContainer.tsx
  apps/chat/src/components/Common/OverflowIndicator.tsx
  apps/chat/src/components/Common/SliderGrid/SliderDots.tsx
  apps/chat/src/components/Marketplace/EntityDetailsHeader.tsx
  apps/chat/src/components/Marketplace/TopicsList.tsx
Labels: bug

#4828 fix(chat): applications custom icons are not rounded (Issue #4527)
  apps/chat/src/components/Chatbar/ModelIcon.tsx
Labels: bug
