Repository epam/ai-dial-chat, pull requests merged in 2025-04, with the labels that each got.

#3501 fix(chat): fix pop-up paddings (Issue #3500)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/ButtonsSchemaModal.tsx
  apps/chat/src/components/Chat/ChatStarters.tsx
Labels: bug

#3505 fix(chat): fix widgets button highlight and hide chat panel if widget selected (Issue #3499)
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Header/BackToChat.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/index.ts
  apps/chat/src/components/Widgetbar.tsx
Labels: bug, _priority_1

#3511 fix(chat): fix new panel icon sizes (Issue #3499)
  apps/chat/src/components/NavigationWrapper.tsx
Labels: bug, _priority_1

#3504 fix(chat): fix app edit autosave (Issue #3502)
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/Previews/ApplicationPreviewChat.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
Labels: bug

#3513 fix(chat): remove scrollbar from new panel and remove widgets from talk to (Issue #3499)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1

#3512 fix(chat): fix agents sorting in Marketplace (Issue #3508)
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.selectors.ts
Labels: bug

#3529 fix(chat): fix mobile chat scroll, promptbar for tablets, widgets selection for admin (Issues #3523, #3526, #3530)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Layout.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
Labels: bug, _priority_1

#3534 fix(chat): fix mobile chat scroll, promptbar for tablets, widgets selection for admin (Issues #3523, #3526, #3530)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Layout.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  package-lock.json
  package.json
Labels: PATCH

#3537 fix(chat): fix error appears when admin clicks on request from Approve required when an app with starters ( Issue#3533)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Common/ErrorBoundary.tsx
Labels: bug, _priority_1

#3519 fix(chat): fix version max allowed symbol count in each slot (Issue #3364)
  apps/chat/src/components/AppsEditor/GeneralInfoView/form.ts
Labels: bug

#3340 fix(chat): update folder share/unshare modals and context menus (Issues #3096, #3295)
  apps/chat-e2e/src/assertions/shareModalAssertion.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/newConversation.test.ts
  apps/chat-e2e/src/tests/shareConversationWithContent.test.ts
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat-e2e/src/tests/sharedFilesAttachments.test.ts
  apps/chat-e2e/src/tests/sharedPromptFolderIcons.test.ts
  apps/chat-e2e/src/tests/sharedPromptIcons.test.ts
  apps/chat-e2e/src/tests/sharedWithMeConversations.test.ts
  apps/chat-e2e/src/tests/sharedWithMePromptFolders.test.ts
  apps/chat-e2e/src/tests/sharedWithMePrompts.test.ts
  apps/chat-e2e/src/ui/selectors/dialogSelectors.ts
  apps/chat-e2e/src/ui/webElements/shareModal.ts
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Common/UnshareDialog.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Files/FileItemContextMenu.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/store/share/share.selectors.ts
  apps/chat/src/store/share/share.types.ts
Labels: bug, enhancement

#3539 fix(chat): fix starters paddings to avoid horizontal scroll (Issue #3538)
  apps/chat/src/components/Chat/ChatStarters.tsx
Labels: bug

#3542 fix(chat): fix starters paddings to avoid horizontal scroll (Issue #3538)
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Common/Buttons/ToggleSidebarButtor.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
Labels: bug

#3541 fix(chat): fix error appears when admin clicks on request from Approve required when an app with starters ( Issue#3533)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Common/ErrorBoundary.tsx
Labels: PATCH

#3545 fix(chat): fix overlay when filterbar is opened, fix starters margins (Issues #3521, #3546)
  apps/chat/src/components/Chat/ChatStarters.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
Labels: bug

#3548 fix(chat): fix delete button redeploying disable (Issue #3517)
  apps/chat/src/utils/app/application.ts
Labels: bug

#3549 fix(chat): fix edit stop sharing dialog appearance (Issue #3535)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
Labels: bug

#3551 fix(chat): fix margins for mobile starters (Issue #3546)
  apps/chat/src/components/Chat/ChatStarters.tsx
Labels: bug

#3567 fix(chat): fix mobile user settings in App Editor (Issue #3564)
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/pages/apps-editor/[slug]/index.tsx
  apps/chat/src/pages/apps-editor/[slug]/settings/index.tsx
Labels: bug

#3566 fix(chat): fix compare blocking, fix sidebar toggle icon (Issue #3436, #3554)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Common/Buttons/ToggleSidebarButtor.tsx
  apps/chat/src/components/Header/Header.tsx
Labels: bug, _priority_2

#3543 fix(chat): fix preview disappear, hide x-icon (Issues #3514, #3515)
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/pages/apps-editor/[slug]/settings/index.tsx
Labels: bug

#3569 fix(chat): fix apps unshare (Issue #3563)
  apps/chat/src/components/Common/UnshareDialog.tsx
Labels: bug

#3570 fix(chat): fix max starters buttons lines (Issue #3546)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
Labels: bug

#3571 fix(chat): fix input width for tablets (Issue #3560)
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: bug, _priority_1

#3490 feat(chat): implement prompt view (Issue #3149)
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/tests/promptExportImport.test.ts
  apps/chat-e2e/src/tests/promptMaximumNameLength.test.ts
  apps/chat-e2e/src/tests/promptNumeration.test.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat-e2e/src/tests/promptsNames.test.ts
  apps/chat-e2e/src/tests/sharedPromptIcons.test.ts
  apps/chat-e2e/src/tests/sharedPromptView.test.ts
  apps/chat-e2e/src/ui/selectors/dialogSelectors.ts
  apps/chat-e2e/src/ui/webElements/promptPreviewModalWindow.ts
  apps/chat/public/images/icons/unpublish.svg
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/ChatInput/PromptList.tsx
  apps/chat/src/components/Chat/ChatModalsManager.jsx
  apps/chat/src/components/Chat/ConversationCompareItem.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/Publish/PublicVersionSelector.tsx
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Common/EmptyRequiredInputMessage.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Common/MoveToFolderModal.tsx
  apps/chat/src/components/Header/CreateNewEntity.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Promptbar/components/EditPrompt.tsx
  apps/chat/src/components/Promptbar/components/PreviewPromptModal.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptDialogs.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/components/Promptbar/components/ViewPrompt.tsx
  apps/chat/src/components/Promptbar/components/ViewPromptButtons.tsx
  apps/chat/src/hooks/usePromptActions.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/utils/app/prompts.ts
  apps/chat/src/utils/app/publications.ts
Labels: enhancement, _priority_2

#3582 feat(chat): change navigation text and icon (Issue #3581, #3573)
  apps/chat/src/components/Common/SidebarMenu.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  package-lock.json
Labels: enhancement, _priority_2

#3587 fix(chat): fix hovering in navigation panel and add icon text back (Issue #3581)
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/tailwind.config.js
Labels: bug

#3594 fix(chat): fix exiting widget mode (Issue #3583)
  apps/chat/src/components/NavigationWrapper.tsx
Labels: bug, _priority_1

#3597 fix(chat): fix tooltip for navigation buttons (Issue #3592, #3596)
  apps/chat/src/components/NavigationWrapper.tsx
Labels: bug

#3584 fix(chat): fix view prompt UI issues (Issues #3580, #3154)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/prompts.test.ts
  apps/chat-e2e/src/tests/publishPrompt.test.ts
  apps/chat-e2e/src/tests/selectChatPanelEntity.test.ts
  apps/chat-e2e/src/tests/sharedPromptView.test.ts
  apps/chat-e2e/src/tests/sharedWithMePromptFolders.test.ts
  apps/chat-e2e/src/tests/sharedWithMePrompts.test.ts
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Promptbar/components/EditPrompt.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/components/Promptbar/components/ViewPrompt.tsx
  apps/chat/src/components/Promptbar/components/ViewPromptButtons.tsx
  apps/chat/src/hooks/usePromptActions.ts
Labels: bug

#3600 fix(chat): cancel configuration request on selecting conversation (Issue #3423)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/store/chat/chat.epics.ts
Labels: bug, _priority_1

#3602 feat(chat): adapt navigation for overlay (Issue #3599)
  apps/chat/src/components/Common/Buttons/ToggleSidebarButtor.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
Labels: enhancement

#3601 fix(chat): fix returning to chat (Issue #3592)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/hooks/useWidgets.ts
Labels: bug

#3610 feat(chat): enable full screen for Configure toolset (Issue #3585)
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
Labels: enhancement

#3616 fix(chat): fix preview panel displaying (Issue #3614)
  apps/chat/src/components/AppsEditor/Settings/index.tsx
Labels: bug

#3590 fix(chat): Update autosave logic, remove confirmations, add warning (Issue #3589)
  apps/chat-e2e/src/tests/agentSelection.test.ts
  apps/chat-e2e/src/tests/customApplications.test.ts
  apps/chat-e2e/src/tests/marketplaceFilters.test.ts
  apps/chat-e2e/src/tests/marketplaceSearch.test.ts
  apps/chat-e2e/src/tests/marketplaceSourceFilter.test.ts
  apps/chat-e2e/src/tests/marketplaceTopicFilter.test.ts
  apps/chat-e2e/src/tests/marketplaceTypeFilter.test.ts
  apps/chat-e2e/src/tests/myWorkspaceSearch.test.ts
  apps/chat-e2e/src/tests/newConversation.test.ts
  apps/chat-e2e/src/ui/webElements/appEditor/appEditorHeader.ts
  apps/chat-e2e/src/ui/webElements/marketplace/marketplaceContainer.ts
  apps/chat-e2e/src/ui/webElements/navigationPanel.ts
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/Previews/ApplicationPreviewChat.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/pages/apps-editor/[slug]/settings/index.tsx
Labels: bug

#3603 fix(chat): fix 'use prompt' after new chat creation (Issue #3154)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Header/CreateNewEntity.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/components/Promptbar/components/ViewPromptButtons.tsx
Labels: bug

#3619 fix(chat): fix conversation & prompt context menu on mobile (Issue #3606)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/hooks/useContextMenuTrigger.ts
Labels: bug, _priority_1

#3620 fix(chat): disable name & version editing in deployed app (Issue #3598)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoView.tsx
Labels: bug

#3623 fix(chat): fix share modal styles to fit QR-code (Issue #3588)
  apps/chat/src/components/Chat/ShareModal.tsx
Labels: bug, _priority_1

#3618 fix(chat): fix footer displaying logic (Issue #3465)
  apps/chat/src/components/Chat/ChatInput/ChatInputFooter.tsx
  apps/chat/src/components/Chat/ChatModalsManager.jsx
  apps/chat/src/components/Chat/__tests__/FooterMessage.test.tsx
  apps/chat/src/components/Common/FooterMessage.tsx
  apps/chat/src/components/Common/RenderWhen.tsx
  apps/chat/src/components/Common/SystemDialogs.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  package-lock.json
Labels: bug

#3625 fix(chat): fix folder context menu, update model on revoking access, fix bold text (Issue #3301, #3401, #3606)
  apps/chat/src/components/Common/CollapsibleSection.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/store/share/share.epics.ts
Labels: bug, _priority_1

#3626 fix(chat): fix context menu trigger position and padding (Issue 3612)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug

#3628 fix(chat): fix app editor next button (Issue #3624)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
Labels: bug

#3629 fix(chat): fix overlay header displaying (Issue #3627)
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
Labels: bug

#3617 feat(chat): add ability to attach array of document_relative_url (Issue #3605)
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/form.ts
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewQuickAppSection.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/components/Common/FilesSelector/FilesSelector.tsx
  apps/chat/src/components/Common/FilesSelector/NoFiles.tsx
  apps/chat/src/components/Common/FilesSelector/SelectedFile.tsx
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/types/quick-apps.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/publications.ts
Labels: enhancement, _priority_1

#3635 fix(chat): fix header height (Issue #3627)
  apps/chat/src/components/Marketplace/MarketplaceFilterbar.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
Labels: bug

#3636 fix(chat): long touch on nested item triggers parent context menu open (Issue #3606)
  apps/chat/src/hooks/useContextMenuTrigger.ts
Labels: bug, _priority_1

#3643 fix(chat): fix source file save and unnecessary error (Issues #3638, #3475)
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
Labels: bug

#3644 fix(chat): fix incorrect mapping of the visualizers (Issue #3613)
  apps/chat/src/store/settings/__tests__/selectors.test.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/utils/app/common.ts
Labels: bug, _priority_1

#3646 fix(chat): fix logo alignment (Issue #3642)
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Header/Logo.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
Labels: bug, _priority_2

#3649 fix(chat): fix issues with document relative url (Issues #3429, #3640)
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
  apps/chat/src/components/Common/FilesSelector/FilesSelector.tsx
  apps/chat/src/components/Common/FilesSelector/SelectedFile.tsx
Labels: bug, _priority_1

#3657 fix(chat): fix logo alignment (Issue #3642)
  apps/chat/src/components/Header/BaseHeader.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
  apps/chat/src/components/NavigationWrapper.tsx
Labels: bug

#3656 fix(chat): fix infinity spinner in Chat Preview on Quick App settings form (Issue #3645)
  apps/chat/src/components/Chat/Chat.tsx
Labels: bug, _priority_1

#3667 fix(chat): fix review document relative urls displaying (Issue #3655, #3668, #3653)
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewQuickAppSection.tsx
  apps/chat/src/components/Common/FilesSelector/SelectedFile.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/constants/applications.ts
Labels: bug

#3662 fix(chat): add constant reference field for conversations to prevent chatId changing (Issue #3345)
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/pages/api/rate.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/migration/migration.epics.ts
  apps/chat/src/types/chat.ts
  apps/chat/src/utils/app/__tests__/importExports.test.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/server/get-headers.ts
  apps/chat/src/utils/server/index.ts
  libs/shared/src/types/chat.ts
  package-lock.json
  package.json
Labels: bug, _priority_1

#3670 chore(chat): fix check warnings
  Dockerfile
Labels: technical debt

#3673 fix(chat): add constant reference field for conversations to prevent chatId changing (Issue #3345)
  .gitignore
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/pages/api/rate.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/migration/migration.epics.ts
  apps/chat/src/types/chat.ts
  apps/chat/src/utils/app/__tests__/importExports.test.ts
  apps/chat/src/utils/app/clean.ts
  apps/chat/src/utils/server/get-headers.ts
  apps/chat/src/utils/server/index.ts
  libs/shared/src/types/chat.ts
Labels: PATCH

#3675 fix(chat): fix context menu trigger for file manager items (Issue #3661)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Files/FileItemContextMenu.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/hooks/useContextMenuTrigger.ts
  package-lock.json
  package.json
Labels: bug, _priority_1

#3681 fix(chat): fix spacing for the share modal (Issue# 3680)
  apps/chat/src/components/Chat/ShareModal.tsx
Labels: bug

#3677 fix(chat): fix route back from app editor keeping workspace filters (Issue #3654)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
Labels: bug

#3683 fix(chat): fix displaying of env variables on review (Issue #3679)
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewApplicationPropsSection.tsx
Labels: bug

#3678 fix(chat): add save logic on tab switch (Issue #3658)
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/application/application.selectors.ts
  apps/chat/src/store/application/applications.types.ts
Labels: bug

#3682 fix(chat): fix incorrect mapping of the visualizers (Issue #3613)
  apps/chat/src/store/settings/__tests__/selectors.test.ts
  apps/chat/src/store/settings/settings.selectors.ts
Labels: PATCH

#3639 fix(chat): fix message selecting (Issue #3634)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/AssistantMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
Labels: bug

#3676 fix(chat): set max width to tooltips (Issue #3507, #3671, 3540)
  apps/chat/src/components/Chat/ShareModal.tsx
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/NavigationWrapper.tsx
Labels: bug

#3686 fix(chat): folder & files long touch issues on mobile (Issue #3641)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Files/FileItemContextMenu.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug, _priority_1

#3687 fix(chat): fix save and exit issue (Issue #3654)
  apps/chat/src/components/AppsEditor/Settings/index.tsx
Labels: bug

#3692 fix(chat): fix the exit functionality for the App editor. (Issue #3684)
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
Labels: bug, _priority_1

#3672 fix(chat): Change the placement and text of warnings for shared applications (Issue #3574)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Common/FilesSelector/FilesSelector.tsx
  apps/chat/src/components/Common/Forms/FieldWarningMessage.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderHeader.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/SelectFolderModal.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/constants/applications.ts
  apps/chat/src/types/common.ts
Labels: bug

#3691 fix(chat): fix context menu displaying (Issue #3612)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ContextMenu.tsx
Labels: bug

#3698 fix(chat): disable navigation during loading (Issue #3669)
  apps/chat/src/components/NavigationWrapper.tsx
Labels: bug

#3695 fix(chat): hide folder tooltips on mobile (Issue #3641)
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Common/CollapsibleSection.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug, _priority_1

#3704 fix(chat): fix file context menu displaying (Issue #3697)
  apps/chat/src/components/Files/FileItem.tsx
Labels: bug

#3707 fix(chat): fix "Use prompt" if prompt has variables (Issue #3706)
  apps/chat/src/components/Promptbar/components/ViewPrompt.tsx
Labels: bug, _priority_1

#3709 fix(chat): hide prompt panel after click on Use (Issue #3607, #3664)
  apps/chat/src/components/Common/Buttons/ToggleSidebarButtor.tsx
  apps/chat/src/components/Promptbar/components/ViewPrompt.tsx
  apps/chat/src/store/prompts/prompts.epics.ts
Labels: bug

#3701 fix(chat): fix "close window" icon overlaps title (Issue #3689)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/ShareModal.tsx
Labels: bug

#3710 fix(chat): fix create conversation in the inner folder in Overlay (Issue #2746)
  apps/chat/src/store/overlay/overlay.epics.ts
Labels: bug, _priority_2

#3712 fix(chat): fix mobile search sizes (Issue #3632)
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: bug

#3719 fix(chat): fix createdAt and updatedAt when create duplicate (Issue #3268)
  apps/chat/src/constants/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
Labels: bug, PATCH

#3730 fix(chat): display "Add app" only for desktop (1280px) (Issue #3729)
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: bug

#3725 fix(chat): fix prompt context menu displaying (Issue #3724)
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug

#3737 feat(chat): add LaTeX support (Issue #2925)
  apps/chat/src/components/Markdown/ChatMDComponent.tsx
  package-lock.json
  package.json
Labels: enhancement, _priority_3

#3740 fix(chat): reset selected version after close View prompt (Issue #3491)
  apps/chat/src/components/Chat/Publish/PublicationChatControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/hooks/usePromptActions.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/share/share.epics.ts
Labels: bug

#3741 fix(chat): fix issues with LaTeX rendering (Issue #2925)
  apps/chat/src/components/Markdown/ChatMDComponent.tsx
  apps/chat/src/styles/globals.css
  apps/chat/src/utils/app/converters.ts
Labels: bug

#3745 fix(chat): remove manage attachments file limit (Issue #3258)
  apps/chat/src/components/Chatbar/ChatbarSettings.tsx
Labels: bug

#3746 fix(chat): fix issues with LaTeX (Issue #2925)
  apps/chat/src/components/Markdown/ChatMDComponent.tsx
  apps/chat/src/utils/app/__tests__/latex.test.ts
  apps/chat/src/utils/app/converters.ts
  apps/chat/src/utils/app/latex.ts
Labels: bug

#3743 feat(chat): remove unnecessary tooltips from modals (Issues #3713, #1689)
  apps/chat-e2e/src/tests/sharedChatIcons.test.ts
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Common/ConfirmDialog.tsx
  apps/chat/src/components/Common/Modal.tsx
  apps/chat/src/components/Common/OptionsDialog.tsx
  apps/chat/src/components/Files/FileItem.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: enhancement

#3578 feat(chat): move widgetsbar & widget view to separate route (Issue #3553, #3669)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chatbar/Chatbar.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Header/User/ProfileButton.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Promptbar/Promptbar.tsx
  apps/chat/src/components/Widgetbar.tsx
  apps/chat/src/components/WidgetsHeader.tsx
  apps/chat/src/constants/routes.ts
  apps/chat/src/hooks/useWidgets.ts
  apps/chat/src/pages/widgets/[slug].tsx
  apps/chat/src/pages/widgets/index.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/application/application.selectors.ts
  apps/chat/src/store/application/applications.types.ts
  apps/chat/src/store/settings/settings.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/store/ui/ui.selectors.ts
  apps/chat/src/store/ui/ui.types.ts
  apps/chat/src/types/storage.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
Labels: bug, enhancement, _priority_1

#3752 fix(chat): fix widgets and mobile user settings displaying (Issue #3750, #3751)
  apps/chat/src/components/Common/SystemDialogs.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/hooks/useWidgets.ts
  apps/chat/src/pages/apps-editor/[slug]/index.tsx
  apps/chat/src/pages/apps-editor/[slug]/settings/index.tsx
  apps/chat/src/pages/index.tsx
  apps/chat/src/pages/marketplace/index.tsx
  apps/chat/src/pages/widgets/[slug].tsx
  apps/chat/src/pages/widgets/index.tsx
Labels: bug

#3742 fix(overlay): fix create conversation in the inner folder, autoscroll for the duplication (Issues #2746, #2423)
  apps/chat-e2e/src/testData/conversationHistory/conversationData.ts
  apps/chat-e2e/src/testData/conversationHistory/folderBuilder.ts
  apps/chat-e2e/src/testData/folders/folderData.ts
  apps/chat-e2e/src/testData/prompts/promptData.ts
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/ConversationsList.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/FilesList.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/PromptsList.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/ReplaceConfirmationModal.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/hooks/useScrollToEntity.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/import-export/importExport.reducers.ts
  apps/chat/src/store/import-export/importExport.types.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/store/ui/ui.selectors.ts
  apps/chat/src/store/ui/ui.types.ts
  apps/chat/src/types/common.ts
  apps/chat/src/types/folder.ts
  apps/chat/src/types/import-export.ts
  apps/chat/src/utils/app/__tests__/importExports.test.ts
  apps/chat/src/utils/app/data/file-service.ts
  apps/chat/src/utils/app/data/storages/browser-storage.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/app/mappers.ts
  apps/overlay-sandbox/app/cases/components/chatOverlayManagerWrapper.tsx
Labels: bug, _priority_2
