Repository epam/ai-dial-chat, pull requests merged in 2025-07, with the labels that each got.

#4230 fix(chat): remove version validation for the file at the publication request edit form (Issue #4127)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandlerFooter.tsx
Labels: bug, _priority_1

#4199 fix(chat): disable 'approve' button if there is conversation with no messages (Issue #4176)
  apps/chat-e2e/src/tests/marketplaceSearch.test.ts
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandlerFooter.tsx
Labels: bug, _priority_3

#4231 fix(chat): fix review prompt update (Issue #4213)
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug, _priority_2

#4238 fix(chat): fix approve required conversation renaming (Issue #4209)
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
Labels: bug

#4243 fix(chat): fix 'Tab' symbol pasted into name's field is treated as restricted symbol (Issue #4240)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandlerFooter.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewRowItems/PublicationFolderRow.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewRowItems/PublicationItemRow.tsx
  apps/chat/src/components/Common/EditableField.tsx
  apps/chat/src/utils/app/common.ts
Labels: bug

#4249 fix(chat): review only selected items (Issue #4149)
  apps/chat/README.md
  apps/chat/src/store/publication/publication.selectors.ts
Labels: bug

#4045 feat(chat): change available agent error message (Issue #4034)
  apps/chat-e2e/src/assertions/chatAssertion.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatExportImportWithAttachment.test.ts
  apps/chat-e2e/src/tests/replay.test.ts
  apps/chat-e2e/src/tests/talkToAgentCard.test.ts
  apps/chat-e2e/src/tests/usePromptNewConversation.test.ts
  apps/chat-e2e/src/ui/webElements/baseElement.ts
  apps/chat/public/locales/en/chat.json
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputFooter.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/NotAllowedModel.tsx
  apps/chat/src/store/chat/chat.selectors.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/types/chat.ts
  apps/chat/src/utils/app/models.ts
Labels: enhancement

#4252 fix(chat): fix review conversation/prompt update (Issue #4213)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/import-export.ts
Labels: bug, _priority_3

#4269 fix: fix after save changes to app user is redirected to 'My workspace' (Issue #4162)
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewApplicationDialog/ReviewApplicationDialogView.tsx
  apps/chat/src/constants/publication.ts
  apps/chat/src/store/application/application.epics.ts
Labels: bug, _priority_2

#4289 fix(chat): hide `display_author` field for publications with unpublish resources only (Issue #3461)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
Labels: bug, _priority_3

#4237 fix(chat): fix existing version validation (Issue #4207)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandlerFooter.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewRowItems/PublicationItemRow.tsx
  apps/chat/src/utils/app/common.ts
Labels: bug

#4279 feat(chat): add 'review files' section to the files manager (Issue #4270)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/components/Files/AttachLinkDialog.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/FilesSectionWrapper.tsx
  apps/chat/src/components/Files/ReviewBucketFilesSection.tsx
  apps/chat/src/store/files/files.selectors.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/app/publications.ts
Labels: enhancement

#4296 fix(chat): fix even number of underscores ('_') in the application name leads to an error. ( Issue #4232)
  apps/chat/src/utils/server/api.ts
Labels: bug, _priority_2

#4301 fix(chat): fix the incorrect version of the app displayed when creating a publish request ( Issue #4207)
  apps/chat/src/utils/server/api.ts
Labels: bug

#4304 fix(chat): fix selected items to approve state handling (Issue #4213)
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/epics-helpers/publications.epic-helpers.ts
Labels: bug

#4282 fix(chat): fix no check for the entity's same name in the folder (Issue #4258)
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewRowItems/PublicationFolderRow.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewRowItems/PublicationItemRow.tsx
  apps/chat/src/components/Common/EditableField.tsx
  apps/chat/src/constants/form-errors.ts
  apps/chat/src/types/translation.ts
  apps/chat/src/utils/app/forms.ts
  apps/chat/src/utils/app/publications.ts
Labels: bug, _priority_2

#4308 fix(chat): replace 'ADD' action with 'ADD_IF_ABSENT' for new files (Issue #4193)
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug

#4321 fix(chat): fix review applications update (Issue #4313)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoView.tsx
Labels: bug, _priority_1

#4326 fix(chat): fix there is no validation for the equal folder names if to rename a folder through context menu (Issue #4318)
  apps/chat/src/components/Chat/Publish/PublicationSidebarResources.tsx
Labels: bug, _priority_2

#4332 fix(chat): fix typo in the publication request view for the application
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewApplicationDialog/ReviewQuickAppSection.tsx
Labels: bug, _priority_1

#4337 fix(chat): fix 'approve selected' checkbox state (Issue #4334, #4293)
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug, _priority_1

#4340 fix(chat): fix 'review files' section display condition (Issue #4270)
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/ReviewBucketFilesSection.tsx
  apps/chat/src/types/files.ts
Labels: bug

#4250 fix(chat): fix issue with unselecting attachment types, add form saving on chat input focusing (Issue #4225)
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Chat/ChatMessage/AdjustedTextarea.tsx
  apps/chat/src/components/Common/ApplicationWizard/view-props.ts
  apps/chat/src/components/Common/MultipleComboBox.tsx
  apps/chat/src/constants/chat.ts
Labels: bug

#4320 fix(chat): hide share and unshare icons from application footer (Issue #3857)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
Labels: bug

#4267 fix(chat): hide three dots from side bars for mobile (Issue #4022)
  apps/chat/src/components/Chatbar/Conversation.tsx
  apps/chat/src/components/Common/ContextMenu.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/types/menu.ts
Labels: bug

#4344 fix(chat): fix after save 'General info' changes to app user is redirected to My workspace (Issue #4162)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/store/application/application.epics.ts
Labels: bug, _priority_2

#4345 fix(chat): put generated by agent files in review bucket (Issue #4341)
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/utils/app/epics-helpers/publications.epic-helpers.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/shared-utils.ts
Labels: bug, _priority_2

#4354 fix(chat): disable 'approve selected' button if there are no changes (Issue #4110)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandlerFooter.tsx
Labels: bug

#4355 feat(chat): add tabs to admin view quick app (Issue #4333)
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewApplicationDialog/ReviewQuickAppSection.tsx
  apps/chat/src/components/Common/MonacoEditor.tsx
Labels: enhancement

#4377 chore(chat): fix stylus dependency (partial regeneration)
  .ort.yml
  package-lock.json
  package.json
Labels: bug, technical debt

#4372 fix(chat): fix unselecting publication when open prompt (Issue #4295)
  apps/chat/src/components/Promptbar/components/Prompt.tsx
Labels: bug

#4373 fix(chat): fix comparing of rule changes (Issue #4315)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
Labels: bug, _priority_2

#4369 fix(chat): display publication 'author' and 'createdAt' fields for review applications in edit mode (Issue #4303)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationContent.tsx
Labels: bug

#4362 fix(chat): add tooltip for the technical folders button (Issue #4012)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Common/Buttons/HiddenItemsToggler.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderFooter.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug, _priority_2

#4359 fix(chat): update review application icons along with publication request (Issues #4317, #4374)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoView.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Files/FileItemContextMenu.tsx
  apps/chat/src/components/Promptbar/components/ViewPromptButtons.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/utils/app/epics-helpers/publications.epic-helpers.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/app/shared-utils.ts
  package-lock.json
  package.json
Labels: bug

#4383 fix(chat): fix a single theme from the configuration is not applied unless it was the last one used in the DIAL chat. (Issue #4382)
  apps/chat/src/store/ui/ui.epics.ts
Labels: bug

#4402 fix(chat): hide 'Add agent to My workspace to continue' button for publication request chats (Issue #4353)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputControls.tsx
Labels: bug

#4404 fix(chat): enhance error handling with proper status codes and message validation (Issue #3666)
  apps/chat/src/utils/server/chat.ts
Labels: enhancement, _priority_2

#4406 chore(chat): add 410 Gone status code error handling (Issue #4403, #4391)
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/utils/server/chat.ts
Labels: enhancement

#4411 chore(chat): add 410 Gone status code error handling (Issue #4403)
  apps/chat/src/constants/errors.ts
  apps/chat/src/utils/server/chat.ts
Labels: bug

#4424 fix(chat): revert `error.message` and log 429 token limits (Issue #3666)
  apps/chat/src/utils/server/chat.ts
Labels: bug

#4442 fix(chat): fix publication review error icons position (Issue #4415)
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewRowItems/PublicationItemRow.tsx
  apps/chat/src/components/Common/EditableField.tsx
Labels: bug

#4433 feat: add support of AzureB2CProvider next auth provider (Issue #4437)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/src/utils/auth/auth-providers.ts
Labels: enhancement, _priority_2
