Repository epam/ai-dial-chat, pull requests merged in 2025-05, with the labels that each got.

#3753 chore(chat): refactor components to simplify admin view implementation (Issue #3755)
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
  apps/chat/src/components/Common/AgentDialogs.tsx
  apps/chat/src/components/Common/ConfirmAgentDeleteDialog.tsx
  apps/chat/src/components/Common/PublishAgentDialog.tsx
  apps/chat/src/components/Marketplace/AgentBookmark.tsx
  apps/chat/src/components/Marketplace/AgentContextMenu.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTable.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/AgentsTiles.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/AgentsList/view-props.ts
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationLogs.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/hooks/useApplicationActions.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/application/application.selectors.ts
  apps/chat/src/store/application/applications.types.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/store/marketplace/marketplace.types.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/store/publication/publication.types.ts
  apps/chat/src/utils/app/latex.ts
Labels: enhancement

#3764 fix(chat): add deploy button to agent footer (Issue #3763)
  apps/chat/src/components/Marketplace/AgentContextMenu.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
Labels: bug, _priority_2

#3770 fix(chat): refactoring of mapping updating (Issue #3766)
  apps/chat/src/components/Chat/ChatSettings/Addons.tsx
  apps/chat/src/store/addons/addons.reducers.ts
  apps/chat/src/store/addons/addons.types.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/types/models.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/models.ts
Labels: bug

#3633 fix(chat): review link is available for already unpublished app (Issue #3433)
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug, _priority_3

#3779 fix(chat): implement validation of permissions when open App Editor for specific application id (Issue #3766)
  apps/chat/src/components/AppsEditor/Settings/CustomApplicationEditorView/index.tsx
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputControls.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Chat/ChatInput/SendMessageButton.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/components/Layout.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/ViewPrompt.tsx
  apps/chat/src/components/Title.tsx
  apps/chat/src/hooks/useAppEditorValidation.ts
  apps/chat/src/pages/404.tsx
  apps/chat/src/pages/apps-editor/[slug]/index.tsx
  apps/chat/src/pages/apps-editor/[slug]/settings/index.tsx
  apps/chat/src/pages/widgets/[slug].tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/models/models.selectors.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/utils/app/route.ts
Labels: bug, enhancement

#3781 fix(chat): fix issue with alignment for items without bookmark (Issue #3780)
  apps/chat/src/components/Marketplace/AgentBookmark.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableLeftSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
Labels: bug, _priority_2

#3760 feat(chat): add paste/drop files into chat feature (Issue #3731)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatDropArea.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInput.tsx
  apps/chat/src/components/Files/FIleDropArea.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/constants/file.ts
  apps/chat/src/hooks/useChatUploadFiles.ts
  apps/chat/src/hooks/useFilePaste.ts
  apps/chat/src/hooks/useUploadFilesHandler.ts
  apps/chat/src/types/files.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/tailwind.config.js
Labels: enhancement, _priority_1

#3788 chore(chat): remove unused code (Issue #3782)
  apps/chat/src/store/addons/addons.selectors.ts
  apps/chat/src/store/auth/auth.selectors.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/files/files.selectors.ts
  apps/chat/src/store/import-export/importExport.selectors.ts
  apps/chat/src/store/models/models.selectors.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/settings/settings.epics.ts
  apps/chat/src/store/settings/settings.selectors.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/store/share/share.selectors.ts
  apps/chat/src/store/share/share.types.ts
  apps/chat/src/store/ui/ui.selectors.ts
Labels: enhancement, technical debt

#3792 fix(chat): disable drop files in playback, replay and external chats, fix drop area blinking (Issue #3790, #3785, #3787)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatDropArea.tsx
  apps/chat/src/components/Files/FileDropArea.tsx
  apps/chat/src/utils/app/conversation.ts
Labels: bug, _priority_3

#3801 fix(chat): fix admin app view (Issues #3798, 3800)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
Labels: bug

#3812 chore(chat): bump koa from 2.15.4 to 2.16.1 (dependabot suggestion)
  package-lock.json
  package.json
Labels: enhancement, technical debt

#3811 fix(chat): fix message streaming displaying (Issue #3807)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1

#3810 chore(chat): bump @tabler/icons-react from 2.9.0 to 3.31.0
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
  apps/chat/src/components/Common/IconButton.tsx
  apps/chat/src/components/Markdown/Table.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Promptbar/components/ViewPromptButtons.tsx
  apps/chat/src/types/menu.ts
  package-lock.json
  package.json
Labels: enhancement, technical debt

#3795 fix(chat): fix alignment of label "suggested results" (Issue #3789, #3766)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTable.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/AgentsList/SuggestedMessage.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/hooks/useAppEditorValidation.ts
  apps/chat/src/pages/apps-editor/[slug]/index.tsx
  apps/chat/src/pages/apps-editor/[slug]/settings/index.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/applicationTypeSchemas/applicationTypeSchemas.epics.ts
  apps/chat/src/utils/app/application-type-schema.ts
  apps/chat/src/utils/app/route.ts
Labels: bug

#3820 fix(chat): fix message streaming displaying (Issue #3807)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1, PATCH

#3809 feat(chat): add paste files feature for editable user message, fix drop area issues (Issue #3786)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Files/AttachButton.tsx
  apps/chat/src/components/Files/FileDropArea.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/hooks/useChatUploadFiles.ts
  apps/chat/src/hooks/useUploadFilesHandler.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/store/files/files.reducers.ts
Labels: bug, enhancement, _priority_1

#3825 fix(chat): hide widgets button, fix quick app publish request (Issue #3767, #3818)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/utils/app/publications.ts
Labels: bug, _priority_1

#3819 fix(chat): fix only last Plotly attachment rendered if to set all attachments to be open (Issue #3778)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug

#3835 feat(chat): show suggestions into Change Agent (Issue #3771)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
  apps/chat/src/components/Common/NoResultsFound.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/marketplace/marketplace.epics.ts
Labels: enhancement, _priority_1

#3826 fix(chat): fix App Editor indicator displaying (Issue #3369)
  apps/chat-e2e/src/tests/customApplications.test.ts
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
Labels: bug

#3840 feat(chat): set auto-focus for search input (Issue #3771)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
Labels: enhancement

#3841 feat(chat): add model into installed after clicking into All agents (Issue #3771)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
Labels: enhancement

#3842 fix(chat): fix style of suggestion card (Issue #3771)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
Labels: bug

#3850 fix(chat): hide navigation panel for isolated view (Issue #3849)
  apps/chat/src/components/NavigationWrapper.tsx
Labels: bug, _priority_1

#3759 feat(chat): add app editor tablet design, move header logo to center (Issues #3733, #3558)
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoView.tsx
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/types/marketplace.ts
Labels: enhancement

#3837 fix(chat): redeploy button is disabled in edit mode (Issue #3799)
  apps/chat/src/store/files/files.epics.ts
Labels: bug, _priority_2

#3806 feat(chat): add new move to modal (Issues #3802, #2884)
  apps/chat-e2e/src/assertions/folderAssertion.ts
  apps/chat-e2e/src/assertions/selectFolderModalAssertion.ts
  apps/chat-e2e/src/core/dialSharedWithMeFixtures.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/chatSelectionFunctionality.test.ts
  apps/chat-e2e/src/tests/conversationNameNumeration.test.ts
  apps/chat-e2e/src/tests/duplicateSharedPrompts.test.ts
  apps/chat-e2e/src/tests/folderNameNumeration.test.ts
  apps/chat-e2e/src/tests/folderPrompts.test.ts
  apps/chat-e2e/src/tests/promptFolderNumeration.test.ts
  apps/chat-e2e/src/tests/promptNumeration.test.ts
  apps/chat-e2e/src/ui/domData/colors.ts
  apps/chat-e2e/src/ui/selectors/folderSelectors.ts
  apps/chat-e2e/src/ui/webElements/entityTree/folders.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/approveRequiredEntitiesTree.ts
  apps/chat-e2e/src/ui/webElements/entityTree/sidebar/sideBarEntitiesTree.ts
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Common/MoveToDialog.tsx
  apps/chat/src/components/Common/MoveToFolderModal.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderFooter.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderHeader.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Files/SelectFolderModal.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/PromptDialogs.tsx
  apps/chat/src/components/Promptbar/components/PromptDialogs/PromptDeleteDialog.tsx
  apps/chat/src/components/Promptbar/components/PromptDialogs/PromptMoveToDialog.tsx
  apps/chat/src/components/Promptbar/components/PromptDialogs/PromptPublishDialog.tsx
  apps/chat/src/components/Promptbar/components/PromptDialogs/index.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/components/Promptbar/components/ViewPromptButtons.tsx
  apps/chat/src/hooks/usePromptActions.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/prompts/prompts.types.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/types/folder.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/app/mappers.ts
  package-lock.json
Labels: enhancement, _priority_2

#3838 fix(overlay): fix auto-signin is not working if no session (Issue #3409)
  apps/chat/src/components/Layout.tsx
  apps/chat/src/pages/auth/signin/index.tsx
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/utils/auth/auth-overlay.ts
  libs/overlay/README.md
  libs/shared/src/types/overlay/overlay.ts
Labels: bug

#3860 fix(chat): code apps turn into custom apps after saving changes on general info step (Issue #3853)
  apps/chat/src/store/application/application.epics.ts
Labels: bug, _priority_1

#3851 feat(chat): add app editor mobile design (Issue #3733)
  apps/chat-e2e/src/tests/overlay/marketplaceFeature.test.ts
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoView.tsx
  apps/chat/src/components/AppsEditor/Settings/ApplicationSettingsFormFooter.tsx
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Common/ToggleSwitch/ToggleSwitchLabeled.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: enhancement

#3852 fix(chat): add breakpoints for talk to slider (Issues #3794, #3772, #3834)
  apps/chat/src/components/Chat/Migration/MigrationFailedModal.tsx
  apps/chat/src/components/Chat/TalkTo/SliderDots.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/constants/talkTo.ts
  apps/chat/src/hooks/useSwipe.ts
  apps/chat/src/hooks/useWindowResizeEvent.ts
  apps/chat/src/types/talkTo.ts
Labels: bug

#3854 fix(chat): fix drop & paste files problems (Issue #3828, #3836, #3830)
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Files/FileDropArea.tsx
  apps/chat/src/hooks/useFilePaste.ts
  apps/chat/src/hooks/useUploadFilesHandler.ts
  apps/chat/src/store/files/files.epics.ts
  apps/chat/src/utils/app/file.ts
Labels: bug, _priority_2

#3871 fix(chat): fix navigation panel displaying (Issue #3861)
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/pages/marketplace/index.tsx
  apps/chat/src/store/ui/ui.selectors.ts
Labels: bug

#3874 chore(chat): move CONTRIBUTING.md into root folder (Issue #3348)
  CONTRIBUTING.md
Labels: enhancement, technical debt

#3872 chore(chat): refactore the navigation (Issue #3873)
  .eslintrc.json
  apps/chat/.eslintrc.json
  apps/chat/src/components/Chat/ChatModalsManager.tsx
  apps/chat/src/components/Chat/ReportIssueDialog.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Layout.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Navigation/MarketplaceNavigation.tsx
  apps/chat/src/components/Navigation/Navigation.tsx
  apps/chat/src/components/Navigation/NavigationButton.tsx
  apps/chat/src/components/Navigation/NavigationWrapper.tsx
  apps/chat/src/components/Navigation/WidgetsNavigation.tsx
  apps/chat/src/components/NavigationWrapper.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/hooks/useWidgets.ts
  apps/chat/src/store/application/application.selectors.ts
  apps/chat/src/store/chat/chat.selectors.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/files/files.selectors.ts
  apps/chat/src/store/models/models.selectors.ts
  apps/chat/src/store/models/widgets.selectors.ts
  apps/chat/src/store/settings/settings.selectors.ts
  apps/chat/src/store/ui/ui.selectors.ts
  apps/chat/src/utils/app/id.ts
Labels: enhancement, technical debt

#3868 chore(chat): update ai-dial-chat picture
  docs/ai-dial-chat.png
Labels: technical debt

#3887 fix(chat): fix clearing of topics (Issue #3876)
  apps/chat/src/components/Common/DropdownSelector.tsx
Labels: bug

#3894 fix(chat): set auto-focus only on non-touchable devices (Issue #3889)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
Labels: bug

#3892 chore(chat): upgrade NX from 20.5.0 to 21.0.3 (Issue #3890)
  .ort.yml
  apps/chat/src/components/Chatbar/Conversations.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  nx.json
  package-lock.json
  package.json
  tsconfig.json
Labels: technical debt

#3877 fix(chat): fix move to folder modal issues (Issues #3862, #3863, #3864)
  apps/chat/src/components/Common/MoveToDialog.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderFooter.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
Labels: bug

#3870 fix(chat): fix unnecessary error appearance (Issue #3745)
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
Labels: bug

#3895 chore(chat): upgrade NX from 20.6.2 to 21.0.3 for e2e-tests (Issue #3890)
  package-lock.json
  package.json
Labels: bug

#3898 feat(chat): show suggestions into Change Agent (Issue #3771)
  apps/chat/.env.development
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
  apps/chat/src/components/Common/NoResultsFound.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/pages/index.tsx
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/overlay-sandbox/app/cases/overlay/enabled-marketplace-sandbox/page.tsx
  docs/ENABLED_FEATURES_ROLES.md
  libs/shared/src/types/features.ts
Labels: enhancement, _priority_1, PATCH

#3903 fix(chat): fix auto-focus logic for change agent (Issue #3889)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/utils/app/mobile.ts
  package-lock.json
  package.json
Labels: bug, _priority_1

#3907 fix(chat): fix sorting of All agents (Issue #3902)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
Labels: bug, _priority_1

#3918 fix(chat): should hide Playback and Replay as is on All agents (Issue #3902)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
Labels: bug

#3916 fix(chat): fix issue with 'Talk To' modal resizing (Issue #3900)
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
  apps/chat/src/hooks/useWindowResizeEvent.ts
Labels: bug, _priority_1

#3913 fix(chat): fix detailed toggle visibility (Issue #3888)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoView.tsx
Labels: bug

#3925 fix(chat): fix deleting of application (Issue #3917)
  apps/chat/src/utils/app/models.ts
Labels: bug, _priority_1

#3938 fix(chat): fix sorting of All agents (Issue #3902)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/utils/app/mobile.ts
  package-lock.json
  package.json
Labels: bug, _priority_1, PATCH

#3911 fix(chat): fix unnecessary error appearance in app editor (Issue #3745)
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
Labels: bug

#3935 fix(chat): optimise 'select agent' slider rendering (#Issue 3936)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
  apps/chat/src/components/Common/FullScreenImages.tsx
  apps/chat/src/hooks/useSwipe.ts
Labels: bug

#3944 fix(chat): add click to tablet preview text (Issue #3929)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoView.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
Labels: bug

#3968 fix(chat): fix uploading conversation for external `conversation-id` (Issue #3961)
  apps/chat/src/utils/app/data/storages/api/conversation-api-storage.ts
Labels: bug

#3972 fix(chat): fix unnecessary error appearance in mind map (Issue #3475)
  apps/chat/src/components/AppsEditor/Settings/CustomApplicationEditorView/index.tsx
Labels: bug

#3979 fix(chat): remove useless marketplace filter sorting (Issue #3978)
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
Labels: enhancement, technical debt

#3983 fix(chat): fix deply/undeploy buttons dispaying (Issue #3817)
  apps/chat/src/components/Common/ContextMenu.tsx
  apps/chat/src/components/Common/IconButton.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/hooks/useAgentMenuItems.ts
Labels: bug, _priority_1

#3946 chore(chat): remove useless filtering of versions
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
Labels: technical debt

#3954 chore(chat): change "custom-applications" behavior (Issue #3948)
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Common/FullScreenImages.tsx
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  libs/shared/src/types/features.ts
Labels: enhancement

#3998 feat(chat): add manifest file for PWA (Issue #3997)
  apps/chat/README.md
  apps/chat/src/pages/_document.tsx
  apps/chat/src/pages/api/manifest.ts
Labels: enhancement, _priority_1

#3958 fix(chat): fix the logic to use both agent ID and reference when handling the `DEFAULT_MODEL` and `RECENT_MODELS_IDS` environmental variables. (Issue #3905)
  apps/chat/README.md
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/store/settings/settings.reducers.ts
  apps/chat/src/store/settings/settings.selectors.ts
  apps/chat/src/store/settings/settings.types.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/server/get-common-page-props.ts
  apps/chat/src/utils/server/get-sorted-entities.ts
  libs/overlay/README.md
Labels: bug, _priority_1
