Repository epam/ai-dial-chat, pull requests merged in 2025-08, with the labels that each got.

#4434 feat: added env variable AUTH_DEBUG_ENABLED (Issue #4438)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/src/pages/api/auth/[...nextauth].ts
Labels: enhancement, _priority_2

#4405 fix(chat): disable delete button if some review bucket file selected (Issue #4358)
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/ReviewBucketFilesSection.tsx
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/utils/app/id.ts
Labels: bug

#4445 fix(overlay): fix it's impossible to login in browser2 if the user has been logged in browser1 (Issue #4432, #4427)
  apps/chat-e2e/src/tests/overlay/events.test.ts
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/AssistantMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/OverlayMessageCustomButtons.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageButtons.tsx
  apps/chat/src/components/Common/DropdownMenu.tsx
  apps/chat/src/pages/auth/signin/index.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/store/overlay/overlay.reducers.ts
  apps/chat/src/store/overlay/overlay.selectors.ts
  apps/chat/src/utils/auth/session.ts
  apps/overlay-sandbox/app/cases/components/chatOverlayManagerWrapper.tsx
  apps/overlay-sandbox/app/cases/components/chatOverlayWrapper.tsx
  apps/overlay-sandbox/app/cases/overlay/custom-message-buttons/page.tsx
  apps/overlay-sandbox/app/cases/overlay/disabled-default-buttons/page.tsx
  apps/overlay-sandbox/app/page.tsx
  libs/overlay/src/index.ts
  libs/shared/src/constants/overlay.ts
  libs/shared/src/types/features.ts
  libs/shared/src/types/overlay/events.ts
  libs/shared/src/types/overlay/overlay.ts
Labels: bug, enhancement, PATCH

#4448 fix(chat): fix marketplace filterbar default open state (Issue #4446)
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/utils/app/data/data-service.ts
Labels: bug

#4440 fix(chat): allow to attach images from 'review files' section to review applications (Issue #4421)
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/components/Files/ReviewBucketFilesSection.tsx
  apps/chat/src/utils/app/publications.ts
Labels: bug, _priority_3

#4412 feat(chat): make 'publish to' field editable in publication handler (Issues #4286, #4031)
  apps/chat-e2e/src/tests/publishFolderWithConversation.test.ts
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandlerFooter.tsx
  apps/chat/src/components/Chat/Publish/PublishToSection.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/FolderContextMenu.tsx
  apps/chat/src/components/Common/MoveToDialog.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolder.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/constants/folders.ts
  apps/chat/src/hooks/usePublicVersionGroupIdFromPublicEntity.ts
  apps/chat/src/store/actions.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/conversations/conversations.types.ts
  apps/chat/src/store/files/files.selectors.ts
  apps/chat/src/store/folders/folders.reducers.ts
  apps/chat/src/store/folders/folders.selectors.ts
  apps/chat/src/store/folders/folders.types.ts
  apps/chat/src/store/index.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/store/publication/publication.selectors.ts
  apps/chat/src/store/publication/publication.types.ts
  libs/shared/src/types/chat.ts
Labels: bug, enhancement

#4441 feat(chat): allow to edit files if publication request has application (Issue #4419)
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewRowItems/PublicationFileRow.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewRowItems/PublicationItemRow.tsx
  apps/chat/src/store/publication/publication.epics.ts
Labels: enhancement

#4458 fix(chat): fix marketplace filterbar default open state (Issue #4446)
  apps/chat/src/components/Marketplace/MarketplaceHeader.tsx
  apps/chat/src/store/settings/settings.epics.ts
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/store/ui/ui.reducers.ts
  apps/chat/src/utils/app/data/data-service.ts
Labels: bug

#4467 fix(chat): fix 'review files' section for conversations (Issue #4464)
  apps/chat/src/components/Files/ReviewBucketFilesSection.tsx
Labels: bug, _priority_1

#4425 fix(admin): enable 'Approve selected' when all rules are removed in (un)publish request (Issue #4395)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandlerFooter.tsx
Labels: bug

#4478 fix(chat): fix select files issues (Issue #3976, #1276)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
  apps/chat/src/components/Files/FileManagerModal.tsx
  apps/chat/src/store/files/files.reducers.ts
Labels: bug

#4481 feat(chat): support monaco themes (Issue epam/ai-dial-chat-themes#73)
  apps/chat/src/components/Common/MonacoEditor.tsx
  apps/chat/src/store/ui/ui.selectors.ts
  apps/chat/src/types/themes.ts
Labels: enhancement

#4486 fix(chat): rename admin duplicate button (Issues #4469, #4470)
  apps/chat/src/components/Chat/ChatInput/ChatExternalControls.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputControls.tsx
Labels: bug

#4497 feat(chat): display tools in Markeplace (part 1, feature flags) (Issue #4401)
  libs/shared/src/types/features.ts
Labels: enhancement

#4517 fix(chat): abort connection if user stops response generation (#2954)
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/utils/server/index.ts
Labels: bug, _priority_2

#4518 feat(chat): implement toolset details card in the marketplace (Issue #4401)
  apps/chat/src/components/Chat/ModelVersionSelect.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationContent.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/EntityDetailsContent.tsx
  apps/chat/src/components/Marketplace/EntityDetailsHeader.tsx
  apps/chat/src/components/Marketplace/EntityInfo.tsx
  apps/chat/src/components/Marketplace/ToolsTabRenderer.tsx
  apps/chat/src/components/Marketplace/ToolsetsDetails/ToolsetDetails.tsx
  apps/chat/src/components/Marketplace/ToolsetsDetails/ToolsetDetailsContent.tsx
  apps/chat/src/components/Marketplace/ToolsetsDetails/ToolsetDetailsFooter.tsx
  apps/chat/src/components/Marketplace/ToolsetsDetails/ToolsetDetailsHeader.tsx
  apps/chat/src/store/toolset/toolset.reducer.ts
  apps/chat/src/store/toolset/toolset.selectors.ts
  apps/chat/src/store/toolset/toolset.types.ts
  apps/chat/src/types/toolsets.ts
Labels: enhancement

#4537 fix(chat): disable 'publish to' edit if publication contains at least one unpublish resource (Issue #4286)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
Labels: bug, _priority_3

#4539 feat(chat): add possibility to customize default banners (Issue #4367)
  apps/chat/src/components/Marketplace/MarketplaceBanner.tsx
  apps/chat/src/pages/api/themes/styles.ts
  apps/chat/src/types/themes.ts
Labels: enhancement

#4540 fix(chat): the 'Sign In' page is missing some headers. (Issue #4534)
  .trivyignore
  apps/chat/src/pages/auth/signin/index.tsx
  apps/chat/src/utils/server/get-common-page-props.ts
  package-lock.json
  package.json
Labels: bug, PATCH

#4548 fix(chat): fix toolset icons & version display issues (Issue #4542, #4543, #4544)
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/ToolsetEditor/ToolsetPreview.tsx
  apps/chat/src/components/ToolsetEditor/form.ts
Labels: bug
