Repository epam/ai-dial-chat, pull requests merged in 2025-06, with the labels that each got.

#4016 chore(chat): refactoring of ops-routes
  apps/chat/src/utils/app/data/publication-service.ts
  apps/chat/src/utils/app/data/storages/api-storage.ts
  apps/chat/src/utils/app/data/storages/api/application-api-storage.ts
  apps/chat/src/utils/server/__tests__/api.test.ts
  apps/chat/src/utils/server/api.ts
Labels: technical debt

#4007 fix(chat): fix change path search regression, 'No results found' position, scroll and error displaying (Issues #3922, #4000, #4001, #4002)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Common/SelectFolder/SelectFolderList.tsx
  apps/chat/src/utils/app/search.ts
Labels: bug

#4025 chore(chat): restore permission flag until issue resolved (Issue #4003)
  apps/chat/src/pages/api/listing/[...listing].ts
Labels: bug, _priority_1, investigation

#4044 fix(chat): fix naming of DIAL_ROLES_FIELD and ADMIN_ROLE_NAMES for Azure AD and Ping ID (Issue #4043)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: bug, technical debt, _priority_1

#4040 feat(chat): improve search on marketplace and tolk to modal (Issue #172)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/constants/search.ts
  apps/chat/src/hooks/useFuseSearch.ts
  apps/chat/src/utils/marketplace.ts
  package-lock.json
  package.json
Labels: enhancement, _priority_2

#4052 fix(chat): search does not work correctly for version and name (Issue #4051)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/constants/search.ts
  apps/chat/src/hooks/useFuseSearch.ts
Labels: bug, _priority_1

#4061 fix(chat): fix iOS PWA installation (Issue #4059)
  apps/chat/src/pages/_document.tsx
Labels: bug, PATCH

#4066 fix(chat): fix max sidebar width (Issue #4053)
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/constants/default-ui-settings.ts
Labels: bug

#4072 fix(chat): fix displaying selected agent in search results (Issue #4069)
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
Labels: bug, _priority_1

#4088 feat(chat): add new Quick app field: MCP toolset ( Issue #4077)
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/form.ts
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewQuickAppSection.tsx
  apps/chat/src/components/Common/ApplicationWizard/form.ts
  apps/chat/src/types/quick-apps.ts
  apps/chat/src/utils/app/application.ts
Labels: enhancement, _priority_1

#4086 fix(chat): remove repeating files request (Issue #4032)
  apps/chat/src/hooks/useChatUploadFiles.ts
  apps/chat/src/hooks/useUploadFilesHandler.ts
  apps/chat/src/store/files/files.epics.ts
Labels: bug, _priority_1

#4115 fix(chat): fix mobile agent card paddings (Issue #4079)
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
Labels: bug

#4126 fix(chat): fix agent fullname tooltip with version displaying (Issue #4083, #4120)
  apps/chat/src/components/Common/Combobox.tsx
  apps/chat/src/components/Common/ModelsSelector.tsx
Labels: bug

#4119 fix(chat): fix 'Send Request' button validation during publication form load ( Issue #4112)
  apps/chat-e2e/src/tests/compareMode.test.ts
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandlerFooter.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/form.ts
  apps/chat/src/constants/publication.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/forms.ts
Labels: bug, _priority_2

#4147 fix(chat): paste plain text along with files (Issue #4124)
  apps/chat/src/components/Chat/ChatInput/ChatInput.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/UserMessage.tsx
  apps/chat/src/hooks/useFilePaste.ts
  apps/chat/src/utils/app/common.ts
Labels: bug, _priority_1

#4159 fix(chat): fix identification of prompts from unpublish request (Issue #4139)
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/ViewPromptButtons.tsx
Labels: bug, _priority_2

#4171 fix(chat): replace isExternal with areReadOnly for conversation blocks input selector (Issue #4166)
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug, _priority_1

#4169 fix(chat): fix editing unpublish request with nested folders (Issue #4144, #4103)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationFilters.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandler.tsx
  apps/chat/src/store/publication/publication.epics.ts
Labels: bug, _priority_2

#4164 fix(chat): enable message field of chat under review, hide edit button on unpublish request (Issue #4135, #4136)
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/Publish/PublicationControls/ChatPublicationControls.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewApplicationDialog/ReviewApplicationDialogView.tsx
  apps/chat/src/store/publication/publication.selectors.ts
Labels: bug, _priority_2

#4187 fix(chat): update attachment titles if update file names when editing publish request (Issue #4138)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/RuleListItem.tsx
  apps/chat/src/components/Common/CodeEditor.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/common.ts
Labels: bug, _priority_2

#4180 fix(chat): hide rename of an approve required items (Issue #4140, #4028, 4103)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessage.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationFilters.tsx
  apps/chat/src/components/Chat/Publish/PublicationHandler/ReviewApplicationDialog/ReviewApplicationDialogView.tsx
  apps/chat/src/components/Common/ItemContextMenu.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/hooks/useAgentMenuItems.ts
Labels: bug

#4189 fix(chat): enable 'use' button if conversation and publication selected simultaneosely (Issue #4139)
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Promptbar/components/ViewPrompt.tsx
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug, _priority_2

#4198 fix(chat): fix changing review button naming (Issue #4137)
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/types/publication.ts
Labels: bug

#4202 fix(chat): hide thin white border for agent icon in dark theme (Issue #4195)
  apps/chat/src/components/Chatbar/ModelIcon.tsx
  apps/chat/src/components/Common/ShareIcon.tsx
Labels: bug

#4206 fix(chat): enable input of conversation that is edited by admin (Issue #4135)
  apps/chat/src/store/conversations/conversations.selectors.ts
Labels: bug

#4208 fix(chat): fix agent content alignment (Issue #4205)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
Labels: bug

#4210 fix(chat): filter attachable files of a chat when being reviewed by admin (Issue #4200)
  apps/chat/src/components/Files/AttachButton.tsx
Labels: bug

#4216 fix(chat): fix 'Back to publication request' button disappearing if update prompt through the 'Edit modal' (Issue #4213)
  apps/chat/src/components/Promptbar/components/EditPrompt.tsx
  apps/chat/src/components/Promptbar/components/PromptModal.tsx
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/prompts.ts
Labels: bug, _priority_2

#4214 fix(chat): change 'Approve' button to 'Approve selected' (Issue #4109)
  apps/chat/src/components/Chat/Publish/PublicationHandler/PublicationHandlerFooter.tsx
Labels: bug

#4217 fix(chat): fix updating of playback attachment titles (Issue #4108)
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/utils/app/conversation.ts
Labels: bug
