Repository epam/ai-dial-chat, pull requests merged in 2025-03, with the labels that each got.

#3277 fix(chat): fix exit and save loader when returning to the 'Marketplace' page (Issue #3241)
  apps/chat/src/store/application/application.epics.ts
Labels: bug, _priority_3

#3261 feat(chat): sync tiles view with table view and fix 'my apps' owner and sort icon color + banner hide logic (Issues #3237, #3267, #3273, #3281)
  apps/chat-e2e/src/assertions/talkToAgentDialogAssertion.ts
  apps/chat-e2e/src/core/dialFixtures.ts
  apps/chat-e2e/src/core/dialOverlayFixtures.ts
  apps/chat-e2e/src/core/dialSharedWithMeFixtures.ts
  apps/chat-e2e/src/tests/defaultModelSettings.test.ts
  apps/chat-e2e/src/tests/entityIcon.test.ts
  apps/chat-e2e/src/tests/marketplaceSearch.test.ts
  apps/chat-e2e/src/tests/myWorkspaceSearch.test.ts
  apps/chat-e2e/src/ui/domData/attributes.ts
  apps/chat-e2e/src/ui/selectors/marketplaceSelectors.ts
  apps/chat-e2e/src/ui/webElements/marketplace/marketplace.ts
  apps/chat-e2e/src/ui/webElements/marketplace/marketplaceAgents.ts
  apps/chat-e2e/src/ui/webElements/marketplace/marketplaceAgentsSection.ts
  apps/chat-e2e/src/ui/webElements/marketplace/marketplaceContainer.ts
  apps/chat-e2e/src/ui/webElements/talkToAgentDialog.ts
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
  apps/chat/src/components/Chat/ChatHeader/Header.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputFooter.tsx
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToSlider.tsx
  apps/chat/src/components/Header/Header.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsListWrapper.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTable.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableHeader.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableLeftSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/HeaderItem.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/AgentsTiles.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/AgentsList/SuggestedMessage.tsx
  apps/chat/src/components/Marketplace/AgentsList/view-props.ts
  apps/chat/src/components/Marketplace/AgentsTable/AgentsTable.tsx
  apps/chat/src/components/Marketplace/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/CardsList.tsx
  apps/chat/src/components/Marketplace/Marketplace.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/components/Sidebar/Sidebar.tsx
  apps/chat/src/constants/marketplace.ts
  apps/chat/src/hooks/useMarketplaceBannerVisibility.ts
  apps/chat/src/hooks/useSyncXScroll.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/ui/ui.epics.ts
  apps/chat/src/types/common.ts
  apps/chat/src/utils/app/data/data-service.ts
  apps/chat/src/utils/app/mobile.ts
Labels: bug, enhancement, _priority_2

#3278 fix(chat): fix code app indicator (Issue #3242)
  apps/chat/src/components/Marketplace/FunctionStatusIndicator.tsx
Labels: bug

#3283 fix(chat): show author for the conversation and prompt inside publication request in Approve required (Issue #3214)
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/RequestApiKeyDialog.tsx
  apps/chat/src/components/Common/DateRenderer.tsx
  apps/chat/src/components/Common/InfoModal.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationInfo.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/store/chat/chat.reducer.ts
  apps/chat/src/types/common.ts
  apps/chat/src/utils/app/common.ts
Labels: bug

#3279 feat(chat): install set of models together (Issue #3150)
  apps/chat-e2e/src/tests/agentSelection.test.ts
  apps/chat-e2e/src/tests/myWorkspaceSearch.test.ts
  apps/chat-e2e/src/ui/webElements/marketplace/marketplaceAgents.ts
  apps/chat-e2e/src/ui/webElements/marketplace/marketplaceAgentsSection.ts
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Chat/EmptyChatDescription.tsx
  apps/chat/src/components/Chat/ModelList.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Common/ShareIcon.tsx
  apps/chat/src/components/Marketplace/AgentBookmark.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableLeftSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
  apps/chat/src/store/codeEditor/codeEditor.epics.ts
  apps/chat/src/store/codeEditor/codeEditor.reducer.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.reducers.ts
  apps/chat/src/store/models/models.selectors.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/models.ts
  apps/chat/src/utils/server/api.ts
  package-lock.json
Labels: enhancement, _priority_2

#3274 feat(chat): redesign publish/unpublish modals (Issue #3229, #3254)
  apps/chat-e2e/src/assertions/publishing/publishingApprovalModalAssertion.ts
  apps/chat-e2e/src/testData/expectedConstants.ts
  apps/chat-e2e/src/tests/publishConversation.test.ts
  apps/chat-e2e/src/tests/unpublishConversation.test.ts
  apps/chat-e2e/src/tests/unpublishFolderWithConversations.test.ts
  apps/chat-e2e/src/ui/selectors/dialogSelectors.ts
  apps/chat-e2e/src/ui/webElements/publishingApprovalModal.ts
  apps/chat-e2e/src/ui/webElements/publishingRequestModal.ts
  apps/chat-e2e/src/utils/dateUtil.ts
  apps/chat/src/components/Chat/Publish/PublicationHandler.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Chat/Publish/PublishWizardComponents.tsx
  apps/chat/src/components/Common/CollapsibleSection.tsx
  apps/chat/src/components/Common/InfoModal.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationInfo.tsx
  apps/chat/src/store/chat/chat.reducer.ts
  apps/chat/src/types/publication.ts
Labels: enhancement

#3291 feat(chat): add code apps creation access by specific roles (Issue #3290)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/environment.d.ts
  apps/chat/index.d.ts
  apps/chat/src/components/Marketplace/SearchHeader.tsx
  apps/chat/src/store/auth/auth.reducers.ts
  apps/chat/src/utils/auth/auth-callbacks.ts
Labels: enhancement, _priority_1

#3289 feat(chat): improve application icon displaying (Issue #3150)
  apps/chat/src/components/Chat/TalkTo/TalkToCard.tsx
  apps/chat/src/components/Common/ShareIcon.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableLeftSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
Labels: enhancement

#3292 feat(chat): implement `hide-user-settings` flag (Issue #3223)
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  libs/shared/src/types/features.ts
Labels: enhancement, _priority_1

#3294 fix(chat): restrict code app router for users who are not allowed to create code apps (Issue #3290)
  apps/chat/src/pages/apps-editor/[slug]/index.tsx
  libs/shared/src/types/features.ts
Labels: bug, _priority_1

#3300 fix(3299): fix model group migration (Issue #3299)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/store/models/models.epics.ts
Labels: bug, _priority_1

#3302 fix(chat): fix tiles list background and bookmark hover (Issues #3297, #3280)
  apps/chat/src/components/Marketplace/AgentBookmark.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/AgentsTiles.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationFooter.tsx
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug, _priority_2

#3309 fix(chat): fix opening Select agent if HideEmptyChatChangeAgent feature is enabled (Issue #3307)
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1

#3312 fix(chat): remove horizontal scroll on marketplace (Issue #3311)
  apps/chat/src/components/Marketplace/AgentsList/AgentsListWrapper.tsx
Labels: bug

#3324 feat(chat): change grouping of models (Issue #3323)
  apps/chat/src/utils/app/models.ts
Labels: enhancement, _priority_1

#3327 feat(chat): change grouping of models (Issue #3323)
  apps/chat/src/utils/app/models.ts
Labels: enhancement, _priority_1, PATCH

#3329 fix(chat): fix scroll on Title View (Issue #3328)
  apps/chat/src/components/Marketplace/AgentsList/AgentsListWrapper.tsx
Labels: bug, _priority_1

#3330 fix(chat): fix scroll on Title View (Issue #3328)
  apps/chat/src/components/Marketplace/AgentsList/AgentsListWrapper.tsx
Labels: bug, _priority_1, PATCH

#3293 feat(chat): allow additional types for custom buttons (Issue #3270)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  libs/shared/src/types/message-form-schema.ts
Labels: enhancement, _priority_2

#3338 fix(chat): fix creating new conversation for assistant (Issue #3337)
  apps/chat/src/constants/errors.ts
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1

#3344 fix(chat): fix creating new conversation for assistant (Issue #3337)
  apps/chat/src/constants/errors.ts
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/store/conversations/conversations.epics.ts
Labels: bug, _priority_1, PATCH

#3342 fix(chat): hide chat starters in replay (Issue #3318)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/UserSchema.tsx
  apps/chat/src/components/Chat/ChatStarters.tsx
Labels: bug

#3358 fix(chat): fix `ENABLED_FEATURES_ROLES` documentation (Issue #3319)
  apps/chat/.env.development
  docs/ENABLED_FEATURES_ROLES.md
Labels: bug

#3363 fix(chat): prevent saving application when navigating to app editor (Issue #3334)
  apps/chat-e2e/src/testData/publishing/publishRequestBuilder.ts
  apps/chat-e2e/src/tests/agentSelection.test.ts
  apps/chat-e2e/src/tests/playBack.test.ts
  apps/chat-e2e/src/tests/publishConversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/unpublishFolderWithConversations.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat/src/components/Marketplace/SearchHeader.tsx
Labels: bug, PATCH

#3361 chore(chat): Remove useless createSelector from selectors (Issue #3360)
  apps/chat/src/store/application/application.selectors.ts
  apps/chat/src/store/auth/auth.selectors.ts
  apps/chat/src/store/chat/chat.selectors.ts
  apps/chat/src/store/codeEditor/codeEditor.selectors.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/files/files.selectors.ts
  apps/chat/src/store/import-export/importExport.selectors.ts
  apps/chat/src/store/marketplace/marketplace.selectors.ts
  apps/chat/src/store/migration/migration.selectors.ts
  apps/chat/src/store/models/models.selectors.ts
  apps/chat/src/store/overlay/overlay.selectors.ts
  apps/chat/src/store/service/service.selectors.ts
  apps/chat/src/store/share/share.selectors.ts
  apps/chat/src/store/ui/ui.selectors.ts
Labels: enhancement, technical debt

#3353 feat(chat): add versions for applications to create publication request form (Issue #2025)
  apps/chat/src/components/Chat/Publish/ApplicationPublishItems.tsx
  apps/chat/src/components/Chat/Publish/PublicationItem.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/utils/server/api.ts
Labels: enhancement, _priority_1

#3373 fix(chat): fix columns displaying on Card view (Issue #3372)
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/AgentsTiles.tsx
Labels: bug, _priority_1

#3374 feat(chat): implement flexible column calculation for Card view (Issue #3372)
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/AgentsTiles.tsx
Labels: enhancement

#3379 fix(chat): fix columns displaying on Card view (Issue #3372)
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/AgentsTiles.tsx
Labels: bug, _priority_1, PATCH

#3380 fix(chat): fix application name width on publish requests (Issue #2025)
  apps/chat/src/components/Chat/Publish/ApplicationPublishItems.tsx
  apps/chat/src/components/Chat/Publish/PublicationResources.tsx
Labels: bug

#3384 feat(chat): change input placeholder (Issue #3383)
  apps/chat/src/components/Chat/ChatInput/ChatInputMessage.tsx
Labels: enhancement, _priority_1

#3385 feat(chat): add request url into error log (Issue #3168)
  apps/chat/src/pages/api/[entitytype]/[...slug].ts
  apps/chat/src/pages/api/application-type-schemas/schema.ts
  apps/chat/src/pages/api/application-type-schemas/schemas.ts
  apps/chat/src/pages/api/bucket.ts
  apps/chat/src/pages/api/chat.ts
  apps/chat/src/pages/api/listing/[...listing].ts
  apps/chat/src/pages/api/listing/multiple.ts
  apps/chat/src/pages/api/metadata/[entitytype]/[...slug].ts
  apps/chat/src/pages/api/ops/[...slug].ts
  apps/chat/src/pages/api/publication/[entitytype]/[...slug].ts
  apps/chat/src/pages/api/publication/approve.ts
  apps/chat/src/pages/api/publication/create.ts
  apps/chat/src/pages/api/publication/delete.ts
  apps/chat/src/pages/api/publication/details.ts
  apps/chat/src/pages/api/publication/listing.ts
  apps/chat/src/pages/api/publication/reject.ts
  apps/chat/src/pages/api/publication/resourceListing.ts
  apps/chat/src/pages/api/publication/rulesList.ts
  apps/chat/src/pages/api/share/accept.ts
  apps/chat/src/pages/api/share/create.ts
  apps/chat/src/pages/api/share/details.ts
  apps/chat/src/pages/api/share/discard.ts
  apps/chat/src/pages/api/share/listing.ts
  apps/chat/src/pages/api/share/revoke.ts
  apps/chat/src/types/error.ts
  apps/chat/src/utils/app/share.ts
  apps/chat/src/utils/server/chat.ts
  apps/chat/src/utils/server/index.ts
Labels: enhancement, technical debt, _priority_2

#3256 fix(chat): add shared app field warnings and confirmation modals (Issues #3077, #3144)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Common/Forms/FieldWarningMessage.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/constants/applications.ts
  apps/chat/src/types/files.ts
Labels: bug

#3382 fix(chat): fix renaming in folder selector modal (Issue #3189)
  apps/chat-e2e/src/tests/selectUploadFolder.test.ts
  apps/chat/src/components/Files/SelectFolderModal.tsx
  apps/chat/src/components/Folder/Folder.tsx
Labels: bug, _priority_3

#3335 fix(chat): remove a single shared file if there are no shared files in the listing. (Issue#3093)
  apps/chat-e2e/src/tests/newConversationOnRefresh.test.ts
  apps/chat/src/store/share/share.epics.ts
Labels: bug

#3411 fix(chat): fix chat starters scrollbar (Issue #3343)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/ButtonsSchemaModal.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
Labels: bug

#3398 feat(chat): add detailed preview for app editor (Issue #3240)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoPreview.tsx
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoView.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationHeader.tsx
  apps/chat/src/constants/applications.ts
  apps/chat/src/pages/apps-editor/[slug]/index.tsx
  apps/chat/src/pages/apps-editor/[slug]/settings/index.tsx
  apps/chat/src/types/application-type-schema.ts
  apps/chat/src/utils/app/application-type-schema.ts
  apps/chat/src/utils/app/application.ts
  apps/chat/src/utils/app/id.ts
Labels: enhancement, _priority_1

#3414 fix(chat): starters modal window size (Issue #3343)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/ButtonsSchemaModal.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Chat/ChatStarters.tsx
Labels: bug

#3417 feat(chat): change federated logout logic (Issue #3275)
  apps/chat/.env.development
  apps/chat/README.md
  apps/chat/src/pages/api/auth/federated-logout.ts
  apps/chat/src/utils/auth/auth-providers.ts
Labels: enhancement, _priority_1

#3415 fix(chat): fix shared app icon & document url warning on edit (Issue #3406)
  apps/chat/src/components/AppsEditor/GeneralInfoView/GeneralInfoEditor.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
Labels: bug, _priority_2

#3419 chore: update README.md
  README.md
Labels: documentation

#3424 fix(chat): fix confirm icon change text (Issue #3408)
  apps/chat/src/constants/applications.ts
Labels: bug

#3428 fix(chat): fix callback url for marketplace (Issue #3426)
  apps/chat-e2e/src/tests/marketplaceFilters.test.ts
  apps/chat/src/pages/auth/signin/index.tsx
Labels: bug

#3439 fix(chat): do not hide button on the last line if it's a single button (Issue #3343)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
Labels: bug, _priority_1

#3443 fix(chat): fix double footer for mindmap custom viewer (Issue #3441)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputControls.tsx
Labels: bug, _priority_1

#3438 fix(chat): fix form schema validator & const value types (Issue #3270)
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/SchemaButton.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/UserSchema.tsx
  apps/chat/src/components/Chat/Playback/PlaybackControls.tsx
  apps/chat/src/utils/app/form-schema.ts
  apps/chat/src/utils/app/typeValidator.ts
  libs/shared/src/types/message-form-schema.ts
Labels: bug, _priority_2

#3354 feat(chat): include an additional field, `displayAuthor`, in the publication request. (Issues #3229, #1661)
  apps/chat/src/components/Chat/ConversationContextMenu.tsx
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
  apps/chat/src/components/Common/InfoModal.tsx
  apps/chat/src/components/Promptbar/components/Prompt.tsx
  apps/chat/src/store/chat/chat.reducer.ts
  apps/chat/src/types/chat.ts
  apps/chat/src/types/common.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/data/publication-service.ts
Labels: enhancement

#3446 fix(chat): fix double footer in chat & offset of replay button in wide layout (Issue #3441)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatInput/ChatInputControls.tsx
Labels: bug, PATCH

#3285 fix(chat): fix API request when manipulating side panel folders (Issue #3133)
  apps/chat-e2e/src/assertions/base/baseAssertion.ts
  apps/chat-e2e/src/assertions/sendMessageAssertion.ts
  apps/chat-e2e/src/tests/chatBarConversation.test.ts
  apps/chat-e2e/src/tests/conversationNameNumeration.test.ts
  apps/chat-e2e/src/tests/conversationWithAttachment.test.ts
  apps/chat-e2e/src/tests/folderNameNumeration.test.ts
  apps/chat-e2e/src/tests/promptFolderNamesakes.test.ts
  apps/chat-e2e/src/tests/promptNumeration.test.ts
  apps/chat-e2e/src/tests/publishConversationToOrganisation.test.ts
  apps/chat-e2e/src/tests/publishFolderWithConversation.test.ts
  apps/chat-e2e/src/tests/publishPrompt.test.ts
  apps/chat-e2e/src/tests/selectUploadFolder.test.ts
  apps/chat-e2e/src/tests/sharedPromptFolderIcons.test.ts
  apps/chat-e2e/src/tests/sidePanelEntityDragAndDrop.test.ts
  apps/chat-e2e/src/tests/workWithModels.test.ts
  apps/chat-e2e/src/ui/domData/colors.ts
  apps/chat-e2e/src/ui/pages/marketplacePage.ts
  apps/chat-e2e/src/ui/webElements/entityTree/folders.ts
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Folder/Folder.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/types/folder.ts
Labels: bug, technical debt, _priority_1

#3432 fix(chat): fix versions sorting for all entities (Issue #3138)
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/SourceFilesEditor.tsx
  apps/chat/src/components/Settings/CustomLogoSelect.tsx
  apps/chat/src/constants/applications.ts
  apps/chat/src/store/models/models.epics.ts
  apps/chat/src/store/models/models.selectors.ts
  apps/chat/src/store/publication/publication.reducers.ts
  apps/chat/src/types/common.ts
  apps/chat/src/types/files.ts
  apps/chat/src/utils/app/common.ts
Labels: bug, _priority_3

#3449 chore(chat): refactor folders revoke epic (Issue #3133)
  apps/chat/src/components/Chatbar/ChatFolders.tsx
  apps/chat/src/components/Promptbar/components/PromptFolders.tsx
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/index.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
Labels: technical debt

#3416 fix(chat): fix DIAL chat hangs if the custom application have been unpublished (Issue #2914)
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/constants/errors.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/utils/server/chat.ts
Labels: bug, _priority_1

#3457 fix(chat): can not type space in the end of string in Request name and author fields (Issue #3450)
  apps/chat/src/components/Chat/Publish/PublishWizard.tsx
Labels: bug, _priority_2

#3464 fix(chat): fix infinite callback occurring when the first user attempts to log in (Issue #3463)
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: bug, _priority_1

#3468 fix(chat): fix infinite callback occurring when the first user attempts to log in (Issue #3463)
  apps/chat/src/utils/server/get-common-page-props.ts
Labels: bug, PATCH

#3460 fix(chat): fix selected agent version in Talk To Modal (Issue #3213)
  apps/chat/src/components/AppsEditor/Settings/ApplicationView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/QuickAppView/index.tsx
  apps/chat/src/components/Chat/ChatMessage/ChatMessageContent/ChatMessageContent.tsx
  apps/chat/src/components/Chat/ChatMessage/MessageSchema/FormSchema.tsx
  apps/chat/src/components/Chat/MessageStage.tsx
  apps/chat/src/components/Chat/MessageStages.tsx
  apps/chat/src/components/Chat/TalkTo/TalkToModal.tsx
  apps/chat/src/components/Chat/__tests__/FooterMessage.test.tsx
  apps/chat/src/components/Common/FooterMessage.tsx
  apps/chat/src/components/Common/ReplaceConfirmationModal/Components.tsx
  apps/chat/src/components/Common/ToggleSwitch/ToggleSwitch.tsx
  apps/chat/src/components/Common/ToggleSwitch/ToggleSwitchLabeled.tsx
  apps/chat/src/components/Common/ToggleSwitch/view-props.ts
  apps/chat/src/components/Common/Tooltip.tsx
  apps/chat/src/components/Markdown/ChatMDComponent.tsx
  apps/chat/src/components/Markdown/CodeBlock.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTable/AgentsTableRightSideRow.tsx
  apps/chat/src/components/Marketplace/AgentsList/AgentsTiles/ApplicationCard.tsx
  apps/chat/src/constants/footer.ts
Labels: bug, _priority_2

#3455 chore(chat): refactor and sync folders update, clean old utils (Issue #792)
  apps/chat/src/components/Chat/ChangePathDialog.tsx
  apps/chat/src/components/Chat/Publish/PublicationItem.tsx
  apps/chat/src/components/Chat/Publish/PublicationItemsList.tsx
  apps/chat/src/components/Chat/Publish/ReviewApplicationDialog/ReviewQuickAppSection.tsx
  apps/chat/src/components/Common/ApplicationWizard/CodeAppView/CodeAppExampleLink.tsx
  apps/chat/src/components/Common/CodeEditor.tsx
  apps/chat/src/components/Files/PreUploadModal.tsx
  apps/chat/src/components/Files/SelectFolderModal.tsx
  apps/chat/src/components/Settings/SettingDialog.tsx
  apps/chat/src/store/codeEditor/codeEditor.epics.ts
  apps/chat/src/store/conversations/conversations.epics.ts
  apps/chat/src/store/conversations/conversations.reducers.ts
  apps/chat/src/store/conversations/conversations.selectors.ts
  apps/chat/src/store/import-export/importExport.epics.ts
  apps/chat/src/store/overlay/overlay.epics.ts
  apps/chat/src/store/prompts/prompts.epics.ts
  apps/chat/src/store/prompts/prompts.reducers.ts
  apps/chat/src/store/prompts/prompts.selectors.ts
  apps/chat/src/store/publication/publication.epics.ts
  apps/chat/src/store/share/share.epics.ts
  apps/chat/src/store/share/share.reducers.ts
  apps/chat/src/types/models.ts
  apps/chat/src/utils/app/__tests__/importExports.test.ts
  apps/chat/src/utils/app/common.ts
  apps/chat/src/utils/app/components-helpers.ts
  apps/chat/src/utils/app/conversation.ts
  apps/chat/src/utils/app/data/share-service.ts
  apps/chat/src/utils/app/data/storages/api/api-entity-storage.ts
  apps/chat/src/utils/app/data/storages/api/prompt-api-storage.ts
  apps/chat/src/utils/app/file.ts
  apps/chat/src/utils/app/folders.ts
  apps/chat/src/utils/app/id.ts
  apps/chat/src/utils/app/import-export.ts
  apps/chat/src/utils/app/mappers.ts
  apps/chat/src/utils/app/models.ts
  apps/chat/src/utils/app/prompts.ts
  apps/chat/src/utils/app/publications.ts
Labels: technical debt

#3482 fix(chat): Remove the version from the bookmark deletion confirmation (Issue #3305)
  apps/chat/src/components/Marketplace/TabRenderer.tsx
Labels: bug

#3493 fix(chat): save marketplace filters if returning from apps-editor route (Issue #3221)
  apps/chat-e2e/src/tests/marketplaceSourceFilter.test.ts
  apps/chat/public/images/icons/log-out.svg
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/components/Header/User/UserDesktop.tsx
  apps/chat/src/components/Header/User/UserMobile.tsx
  apps/chat/src/store/marketplace/marketplace.epics.ts
  apps/chat/src/store/marketplace/marketplace.reducers.ts
Labels: bug, _priority_2

#3480 fix(chat): save settings data when redirecting to general info tab (Issue #3326, #3477, #3479)
  apps/chat/src/components/AppsEditor/Settings/Previews/ApplicationPreviewChat.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/components/Chat/Chat.tsx
  apps/chat/src/components/Chat/ChatStarters.tsx
Labels: bug, _priority_2

#3474 fix(chat): remove temporary chat when exiting editor mode (Issue #3238)
  apps/chat/src/components/AppsEditor/AppsEditorHeader.tsx
  apps/chat/src/components/AppsEditor/Settings/Previews/ApplicationPreviewChat.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
  apps/chat/src/pages/apps-editor/[slug]/settings/index.tsx
  apps/chat/src/store/application/application.epics.ts
  apps/chat/src/store/application/application.reducers.ts
  apps/chat/src/store/application/application.selectors.ts
  apps/chat/src/store/application/applications.types.ts
Labels: bug, _priority_2

#3494 fix(chat): fix code app edit toast (Issue #3246)
  apps/chat/src/components/AppsEditor/Settings/CodeAppView/index.tsx
  apps/chat/src/components/AppsEditor/Settings/Previews/ApplicationPreviewChat.tsx
  apps/chat/src/components/AppsEditor/Settings/index.tsx
Labels: bug

#3497 fix(chat): fix application version sorting (Issue #3467)
  apps/chat/src/components/Marketplace/ApplicationDetails/ApplicationDetails.tsx
Labels: bug
